### ISSUE TITLE
support path/file/extension/regexpr based exclusion

### ISSUE THREAD

**Issue by AminLA** [ritwickdey/vscode-live-server#10]
due to some files(scss) are complied outside of vscode
once we change a scss file then Koala(http://koala-app.com/) will compile scss to target css
but vscode-live-server monitoring every file changes, 
so browser will refresh twice, one for scss the other for compiled css

NOTE: 
we did try your Live Sass Compiler to compile https://github.com/Dogfalo/materialize/releases/download/v0.100.1/materialize-src-v0.100.1.zip 
but it gave me a syntax error

**Comment by ritwickdey** [comment]
Okay! Thanks a lot for the suggestion. I'll try my best to add the feature. 

[ About the Live Sass Compiler : yep! I noticed. This is a issue of Sass.js library. I opened a issue on there github page & I'm waiting for there response https://github.com/medialize/sass.js/issues/91    ]

**Comment by ritwickdey** [comment]
Hi, I added this feature under a settings (`liveServer.settings.ignoreFiles`). Update the extension to v1.6.8 and please give a try. Let me know, if you like it or not. 

For now, I am closing the issue.

And I open a new issue regarding the Sass problem.  https://github.com/ritwickdey/vscode-live-sass-compiler/issues/6 .  That is completely Known Sass Library issue. I will update the extension when a new Stable update will be released. For now, you can check out the `Workaround` section.

**Comment by AminLA** [comment]
it worked perfectly, thanks m8
