### ISSUE TITLE
Bug after multiple backups

### ISSUE THREAD

**Issue by jdbruxelles** [ritwickdey/vscode-live-server#100]
Hi, I think that this extension causes issues in my VS Code.
When I use VS code to write my project which contains `107 files` (including compressed files) and makes about `6 MB`, I'm having problems with the app performance. I don't know if it's caused by the low memory system (`0.89GB free/3.89GB`) or just the server extensions.
The problem is that: The most used files (no compressed) contains about 3000 lines each. When I code, I need to open 2 to 4 files.

I noticed that, if the server extension, `Live Server` isn't active, VS Code works very well, else, the VS Code performance decreases after many changes and backups, and It's so slow that even saving the file becomes slow and the localhost server stops working, hint, autocompletion, emmet and other functionalities stop working too. In this case, I can't continue and I'm forced to restart the app. And sometimes, I have to change the proxy.

I have tried two localhost server extensions and I have reboot my computer too (for another reason) but the problems persist.

**Comment by jdbruxelles** [comment]
@rjoydip This issue reopened at [48451](https://github.com/Microsoft/vscode/issues/48451).

**Comment by rjoydip** [comment]
Thank you for share the details

**Comment by jdbruxelles** [comment]
You're welcome
