### ISSUE TITLE
cannot open the index file

### ISSUE THREAD

**Issue by atilav** [ritwickdey/vscode-live-server#101]
When I go to Right Click on Open with Live Server

got in the browser address bar the following  http://prntscr.com/j2fev1

and this on the page http://prntscr.com/j2ffaa

**Comment by doogood** [comment]
I have the same problem. 
![listing directory _ - google chrome_2018_04_13 00 43 59](https://user-images.githubusercontent.com/36864125/38705969-22a6f21c-3eb4-11e8-9eeb-bf8d0cb7723a.jpg)

**Comment by doogood** [comment]
I realized what the problem was. Changed the order and now everything works :) Thanks! [#43](https://github.com/ritwickdey/vscode-live-server/issues/43)

**Comment by rjoydip** [comment]
@atilav Because there is no html file in your root directory.
