### ISSUE TITLE
Bug: browser reloading everytime for php project

### ISSUE THREAD

**Issue by secato** [ritwickdey/vscode-live-server#103]
Hello,

My browser is reloading like a crazy with live server and php, without do some edit.
I believe that happened after vs code update.
I tested in different SOs (linux and windows) and in both (Firefox and Chrome)

Is anyone with this problem too?
VSCODE: Version 1.22.1

**Comment by ritwickdey** [comment]
Sorry for the late! 
Can you explain furthur?
What do you mean by 'reloading like a crazy'?

**Comment by rjoydip** [comment]
@secato Are you still facing this issue? I have tested this it's working fine on windows with vscode version 1.22.1. I am closing this issue now. Reopen it if issue not solved.
