### ISSUE TITLE
liveserver on asp.net mvc ?

### ISSUE THREAD

**Issue by nicho1991** [ritwickdey/vscode-live-server#105]
Hello, i have a problem trying to launch the liveserver when using mvc pattern. i don't know why, but with a complelete new default asp.net mvc default project, liveserver shows this immage:
![image](https://user-images.githubusercontent.com/30076665/38721765-a82bb3fe-3efb-11e8-815e-c4652a81f5ab.png)
Any ideas for this? im thinking maybe its routing? just a guess tho.

if i debug, and run it shows the correct site, if i set the setting to go localhost and port 5000 while debugging, the liveserver will look corret, but not work with like it usually does with the live updates to the server

**Comment by ritwickdey** [comment]
Live Server can't compile your Dynamic Pages.

Use Live Server Web Extension (https://github.com/ritwickdey/live-server-web-extension) which is built top of Live Server.

Setup help : https://github.com/ritwickdey/live-server-web-extension/blob/master/docs/Setup.md

**Comment by rjoydip** [comment]
@nicho1991 If @ritwickdey 's solution doesn't helps you then reopen it. i am closing it now. Thank you for this report.
