### ISSUE TITLE
Context menu "Open with Live Server" on html file is not working in GitHub Codespaces

### ISSUE THREAD

**Issue by shinyzhu** [ritwickdey/vscode-live-server#1054]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

I'm using GitHub Codespaces to develop a web app. 
And installed Live Server extension in Codespaces environment.
I can start the Live Server by clicking Go Live.
Because GitHub Codespaces is an online environment so I can not directly open `localhost` to view the live web.

## Expected behavior

I assume that I can click the context menu "Open with Live Server" on an html file to open the live app.

## Environment

```html
Browser:

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [x] Edge version 86.0.622.11 (Official build) Beta (64-bit)

For Tooling issues:

- Live Server: v5.6.1<!-- Check which version is installed --> 
- Platform:  Mac <!-- Mac, Linux, Windows -->
- Visual Studio Code: Version: 1.49.0-insider <!-- `code --version` -->
```

**Comment by maweeks** [comment]
A way around this is to start liveserver, go to "Remote Explorer" in the sidebar, then add the port to "Forwarded Ports" at the bottom, with live server running it'll allow you to "Open in Browser"
