### ISSUE TITLE
Does not work with workspace

### ISSUE THREAD

**Issue by dylanh724** [ritwickdey/vscode-live-server#106]
If I have worskpaces
A
B
C

Opening C:/index.html will actually open the live server with A/ as a file index with no way around to opening C

Expected it to open C/index.html

Settings in any of these folders seem to be ignored. Perhaps it's looking for a .vscode/settings.json in some workspace location...?

EDIT: Adding a .vscode/settings.json workspace dir to root doesn't do anything. Still defaults to A/

**Comment by oppoic** [comment]
multi root is not supported, you can change the order of your workspaces in vs code to visit C/inde.html
see: #43
