### ISSUE TITLE
Proxy settings not accessing my backend server

### ISSUE THREAD

**Issue by Sacrekin** [ritwickdey/vscode-live-server#108]
I use Live-Server proxy to proxy REST API calls which is not in my workspace to my backend system. Live-Server removes the port but does not use the server's url. Following is my setting:

"liveServer.settings.proxy": {
    "enable": true, //set it true to enable the feature.
    "baseUri": "/REST", //from where you want to proxy. 
    "proxyUri": "http://myServer.url.com/REST/" //the actual url.
},
PS: if I use https, the settings is ignored, using http, the port is removed but it tries to access it on https://127.0.0.1/REST/

**Comment by rjoydip** [comment]
HTTPS wouldn't work on localhost (127.0.0.1).

**Comment by rjoydip** [comment]
Is this solved? Need your feedback.

**Comment by Sacrekin** [comment]
Not sure about this answer. My configuration is to execute all tested scripts & html from localhost but access all REST API from my https server. 
I am now using lite-server with a proxy middleware that does the trick (source: https://scotch.io/bar-talk/a-fast-and-convenient-development-server-with-lite-server)
