### ISSUE TITLE
Exclamation point in anywhere in the path name will prevent reloading

### ISSUE THREAD

**Issue by oliku** [ritwickdey/vscode-live-server#11]
This seems to be a general issue with all (at least with the ones I've tested) of the live preview extensions for VS Code, so it's not directly related to this extension in particular.

If you remove all exclamation points in any of the folders containing your files, live preview works fine.

Just wanted to let you know, because it took me a good portion of time to find out why none of the live preview extensions, including yours, didn't work for me.

**Comment by ritwickdey** [comment]
Sorry, can you explain more about  "exclamation points in any of the folders containing your files". I don't get the point. 

Alternatively , please make some fakes folders-subfolders-files with same folder structure & send me by zipping the folder(- I think it is best way). It will help me to debug.

**Comment by oliku** [comment]
Sure, I'll try to explain it.

If your path to your documents is something like:

C:\users\user\web\!!!Project\httpdocs\index.html

live preview will not work, because the path contains exclamations points (!!!). If you remove the !!! in front of the folder and rename it to "Project" instead of "!!!Project" live preview works.

Hope this helps!

**Comment by ritwickdey** [comment]
yep! I noticed `[chokidar](https://github.com/paulmillr/chokidar)` does not detecting file changes at this situation. Lot of node.js extension depends on `[chokidar](https://github.com/paulmillr/chokidar)` , that why none of them works for you.

I opened a new issue request on `[chokidar](https://github.com/paulmillr/chokidar)` github repo. https://github.com/paulmillr/chokidar/issues/630

Lets wait for their response.

**Comment by ritwickdey** [comment]
A workaround for now: 

Make a folder (suppose 'NewFolder') and Move the dir `web!!!Project\httpdocs\index.html`  to `NewFolder`. and Open vscode from `NewFolder`. It is working fine....

**Comment by ritwickdey** [comment]
Hi, You said me that none of Live Server works for you because there was issue in library. I've edited main library file of the extension to added the feature. I'll test few more days before publish it to marketplace. 

Meanwhile if you want to use the version, [please download it from here](https://drive.google.com/open?id=0BzfcsRr9yrpdYmNER3FtTWpRVHM) and before installing the new version make a sure that you've uninstalled previous one.


Hope this will work for you. Please test it :)

**Comment by ritwickdey** [comment]
This issue has been fixed with v2.0.0 update. Please update it from vscode marketplace 😄.
Let me know if it like it or not.

If you really like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).
