### ISSUE TITLE
Not working between multiple files

### ISSUE THREAD

**Issue by beerens20** [ritwickdey/vscode-live-server#110]
Scenario: I begin the morning working on website A, I start live server and everything is working great.  Later in the morning I transition to work on website B, disconnect live server and attempt to start it again for the new page but it continues to load website A.  I imagine that clearing my cache in Chrome may solve this but I was hoping to avoid having to do that every time I switch sites that I am editing.  Any ideas on how I can get live sever to properly show the site I am currently working on?

**Comment by mxschmitt** [comment]
Are you using multi-root workspaces?
We could add a header to the responses, so that chrome won't cache the responses.

**Comment by beerens20** [comment]
I was not however I just went ahead and created a workspace and added my different folders to it in order to try live server that way.  It still caches and brings up website A even after I close it out, disconnect live server, and begin working with website B.

**Comment by mxschmitt** [comment]
We are currently not supporting multi-root workspaces. See #43 for more information.

**Comment by rjoydip** [comment]
this is happening for caching

**Comment by rjoydip** [comment]
@beerens20 Still are you facing this issue? Can you please check with newly released version?

**Comment by rjoydip** [comment]
I am closing this issue due to new feedback. Feel free to reopen it.
