### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by Matteo-Fattorini** [ritwickdey/vscode-live-server#1101]
When i run live server and modify CSS file the screen with live server on it begins flickering/flashing until i F5 manually on it?

Does not happen when modifying HTML file.

**Comment by JK82NL** [comment]
I have the same problem. Whenever I save the html or js file I get a flickering screen. When I go to the css (unchanged) file and save it, the flickering stops. 

How did you fix this?

**Comment by feepssouza** [comment]
No meu esta dando a mesma coisa conseguiu resolver no seu
