### ISSUE TITLE
i'm not getting my browser open using live server in vscode

### ISSUE THREAD

**Issue by syamkakarla98** [ritwickdey/vscode-live-server#111]
hi,
i tried many times by clicking the live server option after installing the extension , it's connecting but my browser is not opening.
can anybody solve this problem

**Comment by syamkakarla98** [comment]
i'm using windows7 o.s

**Comment by rjoydip** [comment]
@syamkakarla98 Can you tell me in which browser you have tried and getting error?

**Comment by ritwickdey** [comment]
Try to set browser manually with `liveServer.settings.CustomBrowser` settings or `liveServer.settings.AdvanceCustomBrowserCmdLine`.

Example: 
> settings.json (User settings)
```json
{
   "liveServer.settings.CustomBrowser":"chrome"
}
```
or,
```json
{
   "liveServer.settings.AdvanceCustomBrowserCmdLine":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
}
```

For more details: https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

**Comment by rjoydip** [comment]
I am closing this issue due to new feedback. Feel free to reopen it.

**Comment by lchugh74** [comment]
not able to open the live browser..please help

**Comment by ayeza-khan** [comment]
please help #
when i click on open with live server but the site says
This site can’t be reached
127.0.0.1 took too long to 
![Screenshot (343)](https://user-images.githubusercontent.com/65211526/85979830-a9cd7b80-b9fa-11ea-9854-671754ec32a6.png)

**Comment by Ishaprof0510** [comment]
My live server extension shows "No Internet" on Chrome when I save a file and open my console. Internet is working perfecting fine with my other websites in Chrome.

Can anyone help me with this?

<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/468ee306-c28b-4beb-8a0b-06e4763e3092" />
