### ISSUE TITLE
Can't use Live Server with my favorite browser

### ISSUE THREAD

**Issue by Kelvin-Hey** [ritwickdey/vscode-live-server#1112]
<h2>I'm submitting a...</h2>

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Other: 

<h4>Current behavior</h4>
No option to use Vivaldi Browser

<h4>Expected behavior</h4>
An option to add Vivaldi as browser 

Environment: Linux, Ubuntu
Browser: Vivaldi

For Tooling issues:

- Live Server:  
- Platform:  
- Visual Studio Code: 
Others

**Comment by dougwl** [comment]
You can use 'liveServer.settings.AdvanceCustomBrowserCmdLine' to launch unsupported browsers.
Example: 

liveServer.settings.AdvanceCustomBrowserCmdLine: "C:\\yourinstalationfolder\\vivaldi.exe"

**Comment by Kelvin-Hey** [comment]
Many thanks!
