### ISSUE TITLE
Cannot install Live Server from marketplace as well as vsix

### ISSUE THREAD

**Issue by sdb7** [ritwickdey/vscode-live-server#112]
Hi, got this problem, and as usual not sure whats happening, trying to install from marketplace and fail, had to download manually and install from vsix helper popup from visual studio code but no response so far.

![capture](https://user-images.githubusercontent.com/6058513/39610757-c25a0ed8-4f7c-11e8-9a33-ca06e7cbd079.JPG)

suggested manually install
![manually install from vsix](https://user-images.githubusercontent.com/6058513/39610774-d56a9de4-4f7c-11e8-9fe6-7168f2d36f30.JPG)

do what asked and no response, trying to restart and no effect.

my vscode :
 
![vscode-version](https://user-images.githubusercontent.com/6058513/39610803-0d55b360-4f7d-11e8-88c1-03cd702c96d8.JPG)

Thanks.

**Comment by rjoydip** [comment]
@sdb7 Can you check where liveserver previously installed or not in your system. Please drive into `C:\Users\<USER_NAME>\.vscode\extensions\ritwickdey.liveserver-3.2.0\...`. If it is in there remove that folder completely and reinstall then. 
If it works then confirm us.

**Comment by drew0530** [comment]
I was having the exact same issue and I can confirm that @rjoydip's solution works. I had three different versions backed up and upon removing them all, reinstalling from VSCode, and then reloading that it works.

**Comment by ajtechy** [comment]
I am having the issue "Failed to install ritwickdey.liveserver.
please tell me how i download it

**Comment by AJxerxes** [comment]
Worked for me.
