### ISSUE TITLE
Slow response when opening large projects

### ISSUE THREAD

**Issue by windy0220** [ritwickdey/vscode-live-server#114]

**Comment by rjoydip** [comment]
Can you give more information on it?

**Comment by ritwickdey** [comment]
Try to exclude folders which you don't want for change detection

**Comment by rjoydip** [comment]
@windy0220 Have you checked with below solution?

> Try to exclude folders which you don't want for change detection

Is this working for you?

**Comment by rjoydip** [comment]
@windy0220 please give us your feedback on this issue

**Comment by rjoydip** [comment]
I am closing this issue due to new feedback. Feel free to reopen it.
