### ISSUE TITLE
Cant open tab in chrome with live server

### ISSUE THREAD

**Issue by Missangay** [ritwickdey/vscode-live-server#120]
Hi! I'm new at coding, been using vscode with live server extension and i had no issue, the problem starts when i installed it in a different computer. 
Every time i tried to open with live server there is a message "http://127.0.0.1:5500/index.html application not found"
I have already tried uninstalling both live server and vscode, also every other suggestion that i could find here. 
I cant either use chrome console with js using script command (console.log)
Thank you in advance!

**Comment by rjoydip** [comment]
@Missangay are you sure that getting this?
>  "http://127.0.0.1:5500/index.html application not found"
If you lunch server and unfortunately it isn't open on the browser and you trying to get `index.html` and if it isn't in the application then you can get `Cannot GET /index.html`

**Comment by Missangay** [comment]
![visual github](https://user-images.githubusercontent.com/39138868/41047947-0dbd0b0c-6984-11e8-938d-1c4b472033f4.png)

**Comment by Missangay** [comment]
Also console is not giving me back commands that i send
![chrome github](https://user-images.githubusercontent.com/39138868/41048367-f1584160-6984-11e8-8e3c-c2900ca7d1b7.png)

**Comment by ritwickdey** [comment]
set the settings ` "liveServer.settings.CustomBrowser":"chrome"`

**Comment by rjoydip** [comment]
@Missangay Is this issue solved?

**Comment by rjoydip** [comment]
Closing this issue due to no feedback.

**Comment by Lims-Paces** [comment]
set your default browser to chrome
