### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by lzy2014love** [ritwickdey/vscode-live-server#123]
when i use proxy like this 
![image](https://user-images.githubusercontent.com/23011780/39980305-ce423ece-577d-11e8-81ba-0ccb1c4cd298.png), it does not work : 
![image](https://user-images.githubusercontent.com/23011780/39980384-446d767c-577e-11e8-8865-7c7213c9c359.png).
But when i use nginx like this 
![image](https://user-images.githubusercontent.com/23011780/39980419-6a4d2b44-577e-11e8-9a8a-38e4edd78132.png), it work.

environment： window7， vscode version v1.22.2, live-server version  v3.2.1

**Comment by rjoydip** [comment]
Can you check your ongoing request URL both the cases?

**Comment by lzy2014love** [comment]
yes. I think it probably doesn't carry a cookie and then redirects to login. Nginx may carry cookies and no redirects

**Comment by rjoydip** [comment]
I am not sure that nginix carry cookies. But I  saw in the first screenshot that your request URL is different from proxy URL

**Comment by rjoydip** [comment]
@lzy2014love is this issue has been solved?

**Comment by lzy2014love** [comment]
yeah.It `s my mistake

**Comment by webKity** [comment]
@lzy2014love 请问下, 你这个代理的问题是怎么解决的, 我也碰到了同样的问题, 配置了代理, 但是出现302错误

**Comment by FinchJohnRen** [comment]
> @lzy2014love 请问下, 你这个代理的问题是怎么解决的, 我也碰到了同样的问题, 配置了代理, 但是出现302错误

我配置了代理不生效， 请问这个到底咋配的

**Comment by Yuan-Hang** [comment]
same problem. nginx works, but live server not
