### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by konraddysput** [ritwickdey/vscode-live-server#124]
Hi,

when I share terminal with my Visual Studio Code my collaborator receive weird characters while typing in terminal.

![image](https://user-images.githubusercontent.com/9386268/39994682-4ab4762e-577a-11e8-804f-dc8adb377661.png)

he want to type "exec chrome" but actually type some weirds characters

**Comment by ritwickdey** [comment]
Ops! Wrong direction. This is `Live Server`, not Microsoft's [live share](https://github.com/MicrosoftDocs/live-share).

**Comment by konraddysput** [comment]
Sorry, my fault.
