### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Fudgedup** [ritwickdey/vscode-live-server#126]
I'm on windows 7using Visual Studio Code. When I click go live or right click open with live server I get "Extension host terminated unexpectedly" I've tried mozilla and chrome as default browsers.

Extension host terminated unexpectedly. Code:  3221226356  Signal:  null
w._onExtensionHostCrashed @ extensionService.ts:382
notificationsAlerts.ts:39 Extension host terminated unexpectedly.
e.onDidNotificationChange @ notificationsAlerts.ts:39

**Comment by ritwickdey** [comment]
Share a screenshot of the vscode console... (help => toggle developer tools)

**Comment by rjoydip** [comment]
Please check this one https://stackoverflow.com/a/47314908

**Comment by rjoydip** [comment]
Can you try starting code with --disable-extensions to figure out whether one of your extensions is causing this issue?

Do you have a launch.json file?

**Comment by Fudgedup** [comment]
I didn't have a launch.json file. When I created one it started to work, though it doesn't auto reload.
