### ISSUE TITLE
Browser Does Not Open After Going Live

### ISSUE THREAD

**Issue by matt-zhrani** [ritwickdey/vscode-live-server#13]
I am running Ubuntu on Virtual Box. After installing the extension on VS Code and hitting Go Live,
it prompt me with two messages: one is: "Server is started", the other is: "Error to open browser. See error on console".
Please note that the server is successfully started and I verified that it is working by typing the IP Address on my Google Chrome.

**Comment by ritwickdey** [comment]
Yep! I've just noticed that it is not working in linux but no such issue in Windows. 


Btw, Thanks a lot for report on GitHub repo. :)

**Comment by matt-zhrani** [comment]
You are very welcome. 
So I updated my installation after you pushed the fix.
This time I am getting this error message: "Server is started at 5500 but failed to open browser. See error on console."

**Comment by ritwickdey** [comment]
Okay. Let me check. 
One workaround : set `liveServer.settings.CustomBrowser: chrome `. 

let me know that after doing so, are you still facing the issue?

**Comment by matt-zhrani** [comment]
It works well now!
Thank you for your quick help

**Comment by ritwickdey** [comment]
Please remove `liveServer.settings.CustomBrowser: chrome` and Try v1.6.11. Hope it will open system's default browser without giving any error. 

Let me know if it works for you or not.

**Comment by matt-zhrani** [comment]
I just removed the custom settings and reinstalled Live Server. 
It works perfectly now! thanks

**Comment by muhayminul96** [comment]
Server is started at 5500 but failed to open in Browser Preview. Got Browser Preview extension installed?

**Comment by patelrohan750** [comment]
Server is started at 5500 but failed to open in Browser Preview. Got Browser Preview extension installed?

**Comment by BIRBAHADUR07** [comment]
please still getting this problem tried everything

**Comment by BrianJ-27** [comment]
![image](https://user-images.githubusercontent.com/45458265/111405611-2f877900-86a7-11eb-8da3-960498e06338.png)

This is what i see when i click this the go live option in the bottom bar, but it doesn't trigger the browser preview is there a setting i need to add in my json file. What should the jSON file look like for it to work? Please help thanks

**Comment by suryauppalapati** [comment]
> ![image](https://user-images.githubusercontent.com/45458265/111405611-2f877900-86a7-11eb-8da3-960498e06338.png)
> 
> This is what i see when i click this the go live option in the bottom bar. However it doesn't trigger the browser preview. Is there a setting i need to add in my json file? What should the jSON file look like for it to work? Please help thanks

Same problem here too. Please provide some solution!

**Comment by Sreelayavuyyuru** [comment]
> > ![image](https://user-images.githubusercontent.com/45458265/111405611-2f877900-86a7-11eb-8da3-960498e06338.png)
> > This is what i see when i click this the go live option in the bottom bar. However it doesn't trigger the browser preview. Is there a setting i need to add in my json file? What should the jSON file look like for it to work? Please help thanks
> 
> Same problem here too. Please provide some solution!

Same problem!!

**Comment by saurabh1505717** [comment]
server is started at port 5500 but failed to open browser. try to change the custom browser........ Is there any solution for this error

**Comment by BIRBAHADUR07** [comment]
> server is started at port 5500 but failed to open browser. try to change the custom browser........ Is there any solution for this error

Try starting server at port 80 by that you don't have to type the port number

**Comment by saurabh1505717** [comment]
> > server is started at port 5500 but failed to open browser. try to change the custom browser........ Is there any solution for this error
> 
> Try starting server at port 80 by that you don't have to type the port number
> 
> go to browser and type localhost:5500

So i should change the port mannually from 5500 to 80 ? Or is there any technical procedure.

**Comment by BIRBAHADUR07** [comment]
> > > server is started at port 5500 but failed to open browser. try to change the custom browser........ Is there any solution for this error
> > 
> > 
> > Try starting server at port 80 by that you don't have to type the port number
> > go to browser and type localhost:5500
> 
> So i should change the port mannually from 5500 to 80 ? Or is there any technical procedure.

There may be other way but I am telling you the easy way to save time 1. change port to 80 OR 2. type localhost:5500 on your browser search bar

**Comment by BIRBAHADUR07** [comment]
> > > > server is started at port 5500 but failed to open browser. try to change the custom browser........ Is there any solution for this error
> > > 
> > > 
> > > Try starting server at port 80 by that you don't have to type the port number
> > > go to browser and type localhost:5500
> > 
> > 
> > So i should change the port mannually from 5500 to 80 ? Or is there any technical procedure.
> 
> There may be other way but I am telling you the easy way to save time 1. change port to 80 OR 2. type localhost:5500 on your browser search bar

https://stackoverflow.com/questions/55429643/where-to-set-value-of-liveserver-settings-port-in-live-server-extension-of-visua

This is also a way to solve your problem.

**Comment by saurabh1505717** [comment]
> > > > > server is started at port 5500 but failed to open browser. try to change the custom browser........ Is there any solution for this error
> > > > 
> > > > 
> > > > Try starting server at port 80 by that you don't have to type the port number
> > > > go to browser and type localhost:5500
> > > 
> > > 
> > > So i should change the port mannually from 5500 to 80 ? Or is there any technical procedure.
> > 
> > 
> > There may be other way but I am telling you the easy way to save time 1. change port to 80 OR 2. type localhost:5500 on your browser search bar
> 
> https://stackoverflow.com/questions/55429643/where-to-set-value-of-liveserver-settings-port-in-live-server-extension-of-visua
> 
> This is also a way to solve your problem.

This solution is Not working. .... I changed the port number but after searching the same u instructed to search...... Giving me a blank. Page as output. 
Please help.

**Comment by Shamim49** [comment]
> # VS-code-live-server-problem-solve.. windows 10
> # Server is started at 5500 but failed to open in Browser Preview. Got Browser Preview extension installed?
> step 1- open vs code go to extension (ctrl+shift+x) then search live server then go to live server manage / extension setting then + Edit in setting.json
> step 2- "liveServer.settings.useBrowserPreview": true, [ if u see that line u need to replace true to false ]. "liveServer.settings.useBrowserPreview": false,
> your problem is solved! enjoy vs code :)

**it's working, thanks bro!**

**Comment by ashribad9871** [comment]
please bro help am facing the same issue
