### ISSUE TITLE
Error on port...

### ISSUE THREAD

**Issue by robertgrzonka** [ritwickdey/vscode-live-server#134]
Hi, I've got this error all the time; sometimes it happens after few minutes, sometimes I get maybe one hour before it force me to switch ports. And then again the same, neverending story. 

<img width="373" alt="zrzut ekranu 2018-05-23 o 08 56 32" src="https://user-images.githubusercontent.com/35585466/40408352-82f12372-5e67-11e8-9546-a6beed69b60f.png">

**Comment by Mintonne** [comment]
I am also getting this error. It started this week.

It seems the extension is crashing a lot. I found around 10 instances of Code.exe running after changing the port and restarting VS Code a few times.

If you are on Windows, try running

> netstat -a -b

 in an elevated command line. Look for the process using running at 127.0.0.01:<PORT NUMBER> 

Alternatively, you can use the Resource Monitor.

**Comment by rjoydip** [comment]
@robertgrzonka and @Mintonne can you guys give us which version of `liveserver` and `vscode` using?

**Comment by Mintonne** [comment]
@rjoydip I am on v4.0.0

**Comment by rjoydip** [comment]
@Mintonne you right there are couple of instance running. 
When closing `vscode` without closing `liveserver` instance is not closing.

**Comment by robertgrzonka** [comment]
@rjoydip ```vscode```: v1.23.1 and ```liveserver```: v4.0.0. Today I didn't have any troubles with it for the whole night, which surprise me kindly :)

**Comment by rjoydip** [comment]
@robertgrzonka Same here. Today i investigate this issue again but didn't arias.
