### ISSUE TITLE
not opening in chrome browser

### ISSUE THREAD

**Issue by AzmayenSabil** [ritwickdey/vscode-live-server#1352]
Issue Type: <b>Bug</b>

it's not opening in the browser . just showing the notification that "server started at port 5500". thats it.  

Extension version: 5.6.1
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.62GB free)|
|Process Argv|--crash-reporter-id dd0835b4-6bbf-4135-b9dd-dd5db646d633|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244cf:30250196
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by Leogarcru** [comment]
have you try typing in the browser
127.0.0.1:5500 (5501, 5502, 5503) ??

**Comment by AzmayenSabil** [comment]
yah thanks man. It worked. I opened it with "localport:5500".
