### ISSUE TITLE
The page reloads few times

### ISSUE THREAD

**Issue by devrafalko** [ritwickdey/vscode-live-server#139]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
```

## Current behavior
When I type `ctrl` + `s` to save changes in my file, the `live-server` reloads the opened page immediately. Then, after ~8sec it reloads the page **again** and in the next ~1sec reloads **another time**.
It works fine when I run `live-server` first time (click `Go live` option in the vscode editor) (it opens the page in the browser and do not reload it next times).
I've tried to change the `liveServer.settings.CustomBrowser`, `liveServer.settings.wait` and `liveServer.settings.port` with no result.
I do not use any bundlers, only `.html`, `.css` and `.js` file. This behavior occurs regardless of which file I modify.

## Expected behavior
I expect the `live-server` to reload the page just once, right after the modified file is saved (`ctrl` + `s`).

## Environment

```html
Browser:

- [x ] Chrome (desktop) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Node version: v8.11.2
- Npm version: 5.6.0
- Platform: Windows 10
- Visual Studio Code: 1.23.1
```

**Comment by rjoydip** [comment]
If your project is a typescript or webpack then ignore typescript output file on liveserver

**Comment by rjoydip** [comment]
@devrafalko please give us your feedback

**Comment by devrafalko** [comment]
Finally I've figured out that my Google Drive is responsible for that problem. I store my project on Google Drive and update it automatically each time any file is modified. The `live-server` refreshes the web browser right after I save the modified file, and the second time when the Google Drive finishes to upload the file to the cloud *(with few seconds delay)*. When I switched off the automatic synchronization, the `live-server` refreshes the browser once.

**Comment by Szasz1989** [comment]
> Finally I've figured out that my Google Drive is responsible for that problem. I store my project on Google Drive and update it automatically each time any file is modified. The `live-server` refreshes the web browser right after I save the modified file, and the second time when the Google Drive finishes to upload the file to the cloud _(with few seconds delay)_. When I switched off the automatic synchronization, the `live-server` refreshes the browser once.

Hi there, 

I have exactly the same problem. Where did you turn the automatic synchronization off? 

Thanks
