### ISSUE TITLE
CSS file doesn't load

### ISSUE THREAD

**Issue by Icomanman** [ritwickdey/vscode-live-server#142]
Hi!
I am running live-server to quickly see changes in my web page trials. Changes in html are reloaded well. However, it appears that the CSS file does not load. If I use the "file://" on the browser, it works just fine.

**Comment by rjoydip** [comment]
Have you tried this option `liveServer.settings.fullReload`?

**Comment by ritwickdey** [comment]
> appears that the CSS file does not load


What you mean by this? Any error? Or live reload is not working?

**Comment by rjoydip** [comment]
@Icomanman Is this issue solved? Please give us your feedback.

**Comment by rjoydip** [comment]
duplicate #85

**Comment by Icomanman** [comment]
Thank you for your responses... I am running the node live-server via the integrated terminal in VS Code.

**Comment by rjoydip** [comment]
@Icomanman Check this one
```
`liveServer.settings.fullReload` : By Default Live Server inject CSS changes without full reloading of browser. You can change this behviour by making this setting as true.

Default: false
```

**Comment by rjoydip** [comment]
@Icomanman `fullReload` should be there.

**Comment by Icomanman** [comment]
Hi rjoydip, unfortunately, I still do... I really can't find the liveServer.settings, or any of it. Even if I put it straight into the user settings, I get a message that it is an unknown configuration.

However, I am curious, is there any other liverserver out there that we might be talking of two different things? I had setup the liveserver through npm install.

**Comment by Shema05** [comment]
@Icomanman,go settings ,open command pallete and type in **full reload**,you will get the option.

**Comment by Nemachtilli** [comment]
Enter file-preferences-configuration

![vs code](https://user-images.githubusercontent.com/40610542/53281960-9cadc780-36f6-11e9-9f06-7014c8acda8c.png)

open configuration.json

![vs code3](https://user-images.githubusercontent.com/40610542/53281984-0f1ea780-36f7-11e9-86aa-973087c0ce89.png)

add the following:

"liveServer.settings.ChromeDebuggingAttachmen": true,
    "liveServer.settings.useLocalIp":true,
    "liveServer.settings.fullReload":true,
    "liveServer.settings.port": 8080,

![vs code2](https://user-images.githubusercontent.com/40610542/53281992-2c537600-36f7-11e9-84f9-85aea53fbf05.png)

save Changes and close vs code.

open again vs code and check if the CSS works.

It worked for me

I work for me because of the following: the default settings are false

En español el archivo de ccs no carga en live server
1.-Abrir archivo-preferencias-configuración (imagen 1)
2.-Abrir configuracion (imagen 2 cuadro rojo)
3.-Agregar lo siguiente:

"liveServer.settings.ChromeDebuggingAttachmen": true,
    "liveServer.settings.useLocalIp":true,
    "liveServer.settings.fullReload":true,
    "liveServer.settings.port": 8080,
4.- guardar cambios.
5.- salir de vs code.
6.-Abrir vs code y verificar si funciona.

Me funciono a mi por lo siguiente: las configuraciones están por defecto en false.

Viva México y mi presidente Andrés Manuel Lopez Obrador saludos

**Comment by henriquetbp** [comment]
> Enter file-preferences-configuration
> 
> ![vs code](https://user-images.githubusercontent.com/40610542/53281960-9cadc780-36f6-11e9-9f06-7014c8acda8c.png)
> 
> open configuration.json
> 
> ![vs code3](https://user-images.githubusercontent.com/40610542/53281984-0f1ea780-36f7-11e9-86aa-973087c0ce89.png)
> 
> add the following:
> 
> "liveServer.settings.ChromeDebuggingAttachmen": true,
> "liveServer.settings.useLocalIp":true,
> "liveServer.settings.fullReload":true,
> "liveServer.settings.port": 8080,
> 
> ![vs code2](https://user-images.githubusercontent.com/40610542/53281992-2c537600-36f7-11e9-84f9-85aea53fbf05.png)
> 
> save Changes and close vs code.
> 
> open again vs code and check if the CSS works.
> 
> It worked for me
> 
> I work for me because of the following: the default settings are false
> 
> En español el archivo de ccs no carga en live server
> 1.-Abrir archivo-preferencias-configuración (imagen 1)
> 2.-Abrir configuracion (imagen 2 cuadro rojo)
> 3.-Agregar lo siguiente:
> 
> "liveServer.settings.ChromeDebuggingAttachmen": true,
> "liveServer.settings.useLocalIp":true,
> "liveServer.settings.fullReload":true,
> "liveServer.settings.port": 8080,
> 4.- guardar cambios.
> 5.- salir de vs code.
> 6.-Abrir vs code y verificar si funciona.
> 
> Me funciono a mi por lo siguiente: las configuraciones están por defecto en false.
> 
> Viva México y mi presidente Andrés Manuel Lopez Obrador saludos

This worked for me! Thanks @Nemachtilli

**Comment by m1ghtyju4n** [comment]
> Enter file-preferences-configuration
> 
> ![vs code](https://user-images.githubusercontent.com/40610542/53281960-9cadc780-36f6-11e9-9f06-7014c8acda8c.png)
> 
> open configuration.json
> 
> ![vs code3](https://user-images.githubusercontent.com/40610542/53281984-0f1ea780-36f7-11e9-86aa-973087c0ce89.png)
> 
> add the following:
> 
> "liveServer.settings.ChromeDebuggingAttachmen": true,
> "liveServer.settings.useLocalIp":true,
> "liveServer.settings.fullReload":true,
> "liveServer.settings.port": 8080,
> 
> ![vs code2](https://user-images.githubusercontent.com/40610542/53281992-2c537600-36f7-11e9-84f9-85aea53fbf05.png)
> 
> save Changes and close vs code.
> 
> open again vs code and check if the CSS works.
> 
> It worked for me
> 
> I work for me because of the following: the default settings are false
> 
> En español el archivo de ccs no carga en live server
> 1.-Abrir archivo-preferencias-configuración (imagen 1)
> 2.-Abrir configuracion (imagen 2 cuadro rojo)
> 3.-Agregar lo siguiente:
> 
> "liveServer.settings.ChromeDebuggingAttachmen": true,
> "liveServer.settings.useLocalIp":true,
> "liveServer.settings.fullReload":true,
> "liveServer.settings.port": 8080,
> 4.- guardar cambios.
> 5.- salir de vs code.
> 6.-Abrir vs code y verificar si funciona.
> 
> Me funciono a mi por lo siguiente: las configuraciones están por defecto en false.
> 
> Viva México y mi presidente Andrés Manuel Lopez Obrador saludos

Hi I did all of this and still have the same problem, CSS still wont load, I am using Live Server v5.6.1, VSCode on Linux Mint.

**Comment by gvirus21** [comment]
hey guys , looks like I found an another Fix. I don't know it will work for everyone or not but hear me out.

My Problem :- live server loads html file perfectly but doesn't load the css with it. But my linking was right. And without live server my page loads fine.

I am on latest version of windows 10 Home edition , version 2004 
and my VS code version is 1.52

My Solution :-
so I usually copy path of the css file by right clicking on it and paste it on html.

ex :-     <link rel="stylesheet" type="text/css" href="E:\projects\portfolio-site\New folder\design.css">

I didn't put much attention in that as that is syntactically correct and without liveserver , my page seems to work fine.

But to make liveserver work, you have to paste only name of the css file (Assuming  that you have all html and css files are in same location).

 ex :-     <link rel="stylesheet" type="text/css" href="design.css">

then just try to refresh,
It should Start loading css again .

**Comment by CodeMachineDesu** [comment]
@Icomanman Was your issue resolved? I am currently facing the same issue and really appreciate the solution that you found to this problem if any.

**Comment by ritwickdey** [comment]
Can you please open a new issue request if you're facing any problems? @CodeMachineDesu

**Comment by behzadahmady** [comment]
The problem not solved for me. I get this error yet.```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at refreshCSS (http://127.0.0.1:8080/:36:11)
    at WebSocket.socket.onmessage (http://127.0.0.1:8080/:50:40)
```
I have to refresh the page manually.

**Comment by Halibayyb** [comment]
I just solved the problem. You only have to rewrite href = "./style.css" in your tag link, because live server is running your root folder.

**Comment by jyshaki** [comment]
> I just solved the problem. You only have to rewrite href = "./style.css" in your tag link, because live server is running your root folder.

It worked for me, everything what was above have not. Thank you!

**Comment by kartiksubaiah** [comment]
@Nemachtilli @gvirus21 @Halibayyb Thanks guys for the solutions. you guys are awesome. Looks like it considers the folder of the html file as the root.

**Comment by devharshmehta** [comment]
> hey guys , looks like I found an another Fix. I don't know it will work for everyone or not but hear me out.
> 
> My Problem :- live server loads html file perfectly but doesn't load the css with it. But my linking was right. And without live server my page loads fine.
> 
> I am on latest version of windows 10 Home edition , version 2004 and my VS code version is 1.52
> 
> My Solution :- so I usually copy path of the css file by right clicking on it and paste it on html.
> 
> ex :-
> 
> I didn't put much attention in that as that is syntactically correct and without liveserver , my page seems to work fine.
> 
> But to make liveserver work, you have to paste only name of the css file (Assuming that you have all html and css files are in same location).
> 
> ex :-
> 
> then just try to refresh, It should Start loading css again .

broo thankssssssssss, my head was about to burst, thank you so much, it worked
