### ISSUE TITLE
Sorry, I'm a noob, but I don't understand how to change settings

### ISSUE THREAD

**Issue by cohn17** [ritwickdey/vscode-live-server#146]
I'm trying to change the default browser for Live Server. Where do I type the line "liveServer.settings.CustomBrowser:chrome"?

Please explain in some detail, because I'm only learning how to code, so nothing is obvious to me ... 

Thank you!

**Comment by ritwickdey** [comment]
Have you read FAQ - **[How to configure the settings in my project](https://github.com/ritwickdey/vscode-live-server/blob/master/docs/faqs.md#how-to-configure-the-settings-in-my-project)**?

https://github.com/ritwickdey/vscode-live-server/blob/master/docs/faqs.md#how-to-configure-the-settings-in-my-project

**Comment by cohn17** [comment]
I did, yes, but that didn't seem to work. I'm not on a specific project right now, I just have a folder in which I am keeping all of my programming files. I created a .vscode folder within that folder and then a settings.json file with the code you specified, but nothing happened. I assume there's one more step that I would know to do if I weren't just starting out.

**Comment by cohn17** [comment]
<img width="1394" alt="screen shot 2018-06-05 at 5 30 57 pm" src="https://user-images.githubusercontent.com/11272608/40970893-1e42aa0c-68e6-11e8-8cd1-b84830aa3134.png">

**Comment by cohn17** [comment]
<img width="1393" alt="screen shot 2018-06-05 at 5 34 53 pm" src="https://user-images.githubusercontent.com/11272608/40971077-9f4a376e-68e6-11e8-858e-71a3fe3a53ee.png">

**Comment by cohn17** [comment]
Thanks for taking a look.

**Comment by ritwickdey** [comment]
Ohh! You didn't open a folder - you just open a single file. Please open folder (file -> open folder) to apply the settings.

**Comment by cohn17** [comment]
I'm sorry, but I don't understand what you mean. Which folder do I open, and with which application?

**Comment by ritwickdey** [comment]
You have to open folder in vscode in order to apply settings. 

Open Vscode -> from menubar select File -> open folder -> choose the folder & ok

**Comment by cohn17** [comment]
Thank you! Now, though, I don't see the "Go Live" icon in the status bar, and Live Server is showing this:

<img width="1440" alt="screen shot 2018-06-05 at 6 02 04 pm" src="https://user-images.githubusercontent.com/11272608/40972298-73612668-68ea-11e8-8b79-b7dec0d73159.png">

This is my code file now:

<img width="903" alt="screen shot 2018-06-05 at 6 02 55 pm" src="https://user-images.githubusercontent.com/11272608/40972321-88fec1ec-68ea-11e8-964a-fa25109c03b6.png">

**Comment by ritwickdey** [comment]
Restart the `vscode` if you don't see `Go Live` initially.

**Comment by ritwickdey** [comment]
Anyway, leave a rating for the extension if you're helped. 😄 

https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details

**Comment by cohn17** [comment]
I closed and reopened the VS Code application. No change.

**Comment by cohn17** [comment]
It says "Server is Started at port : 5500"

**Comment by cohn17** [comment]
Sure - if you look at the images I attached above, you will not see the "Go Live" icon:

<img width="623" alt="screen shot 2018-06-05 at 6 27 00 pm" src="https://user-images.githubusercontent.com/11272608/40973284-e823cec6-68ed-11e8-9088-b4a8f3ef6d59.png">

It was working before, when I first installed it (and it was opening to the default Safari browser).

**Comment by cohn17** [comment]
Let me update this: when I click on ø Port:5500 in the status bar, I do get the icon. However, I do not see my index.html in the Chrome window; I see the URL 127.0.01:5500, like in my message above.

**Comment by ritwickdey** [comment]
Share a screenshot ?

**Comment by cohn17** [comment]
<img width="1440" alt="screen shot 2018-06-05 at 7 09 21 pm" src="https://user-images.githubusercontent.com/11272608/40975048-d5dfe226-68f3-11e8-8f2a-7419bea9098c.png">

**Comment by ritwickdey** [comment]
The `Index.html` is not in project root or sub-root. Open the folder where index.html is located.

**Comment by cohn17** [comment]
Success!

Thank you for taking the time to help me out. If I could ask one last question, why did I first have to open the folder where index.html is located, rather than just opening the file in the code editor like I had been doing?

**Comment by ritwickdey** [comment]
Opening a signal file in any IDE/Code-Editor is a bad idea.

**Comment by ritwickdey** [comment]
Opening a single file in any IDE/Code-Editor is a bad idea.
