### ISSUE TITLE
Simple Request - Bring Browser to Front On A Save

### ISSUE THREAD

**Issue by sobpilot** [ritwickdey/vscode-live-server#147]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

On a save the browser (Chrome) refreshes, but I have limited real estate on my monitor so I have to click on the browser to bring it to the front.

## Expected behavior

When saving I would to switch windows to the browser.

## Environment

```html
Browser:

- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: <!-- Check which version is installed --> 
- Platform:  <!-- Mac, Linux, Windows -->
- Visual Studio Code: <!-- `code --version` -->
```

**Comment by rjoydip** [comment]
I don't think technically it is possible or not. Others hot reloading module `angular`, `browser-sync` etc hasn't this feature. But we are working on the feature of `Side by Side HTML/browser` inside `vs code`.

**Comment by sobpilot** [comment]
Great news, thanks. By the way, I gave Live Server a mention in one of my blogs.
https://medium.com/@steveolensky/create-a-spa-vuejs-application-without-node-webpack-or-any-other-build-process-using-vue-router-b9bf8e36e958

**Comment by rjoydip** [comment]
That's great. Thank you so much.
