### ISSUE TITLE
The Parameter is incorrect

### ISSUE THREAD

**Issue by deanhtid** [ritwickdey/vscode-live-server#152]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

When i try to launch the live server i get a pop up box saying http://127.0.0.1:5500/02.html

## Expected behavior

I expect the browser to launch with some live reloading

## Environment

```html
Browser:

- [x ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 4.1.0
- Platform:  Windows
- Visual Studio Code: 1.24.0
```

**Comment by rjoydip** [comment]
Where you getting the pop-up?
Is it inside vscode?

**Comment by deanhtid** [comment]
Nah it’s seperate from VScode. I would share a screenshot but I don’t have access to my laptop right now

**Comment by rjoydip** [comment]
That's will be better if you share screenshot

**Comment by deanhtid** [comment]
![annotation](https://user-images.githubusercontent.com/10110324/41279507-932ad752-6e24-11e8-963a-80dd49a186f5.png)

**Comment by ritwickdey** [comment]
Okay, basically same as #120 #65 

Set  "liveServer.settings.CustomBrowser":"chrome"

**Comment by deanhtid** [comment]
![annotation](https://user-images.githubusercontent.com/10110324/41289154-b4497ddc-6e40-11e8-9a61-925de601efb9.png)

Now i get this. This is the correct file path

**Comment by ritwickdey** [comment]
Is chrome installed at this location?

**Comment by rjoydip** [comment]
Or you can try with other browser as custom browser

**Comment by deanhtid** [comment]
Yep installed exactly there. Would rather not give up on using Chrome. Thanks

**Comment by deanhtid** [comment]
Tried Firefox as a test and exactly the same error

**Comment by gijoe50000** [comment]
I've been having the same problem now for a week or so on my home machine. No problem on my machine in class. Tried the "chrome" solution above but still the same. Also tried reinstalling VSCode and the extensions.
The Open-In-Browser extension gives the same error, so it doesn't seem to be related to Live Server, and I also get the exact same error in Atoms live server, so I'm not sure if it's a VSCode problem either.

I'm running Windows 10 insider build so maybe it's a problem there?
I'm also running MAMP but uninstalling it didn't help, and I've got MAMP on my class machine and it's fine.

**Comment by davimdantas** [comment]
I'm having the same problem. 
Using VSCode Insider and running windows 10. 
This solution didn't work:
Set "liveServer.settings.CustomBrowser":"chrome"
neither change to another browser.

**Comment by rjoydip** [comment]
I am not sure that whether is this happening by the firewall !

**Comment by gijoe50000** [comment]
Nope. I tried turning off my firewall, and everything security related I
could find. Didn't make any difference. But it could still very well be
something in the network config. It's a pity the error message isn't even a
little more helpful.

**Comment by ritwickdey** [comment]
Just for a confirmation, after getting this error, if you manually open the site (127.0.0.1

**Comment by ritwickdey** [comment]
Just for a confirmation, after getting this error, if you manually open the site (127.0.0.1:5500) ,


Is the server working fine? Or server is also not working!!!

**Comment by gijoe50000** [comment]
Yea, it works fine after you open the html file manually. I'm using random port numbers so it's not always 5500, but yea.

**Comment by gijoe50000** [comment]
Tried a lot of things like copying and pasting the address from the addressbar into settings, and localhost instead of 127.. too. I'm thinking it must be a Windows issue, since the error is generated by Windows (I assume) and I've seen people get the same error with server misconfigs too.. It's very vague. Could b some config change that Microsoft have in the pipeline, since I'm using the insiders build. Don't know if other people with the error are insiders too?

**Comment by davimdantas** [comment]
I don't think it's a windows problem. I have no problem opening the chrome through vscode Task command, works like a charm. I'm using this code: 
`{
            "taskName": "Open in Chrome",     
            "isBuildCommand": true,
            "command": "Chrome",
            "windows": {
                "command": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
            },
            "args": [
                "http://localhost:5500/${relativeFile}"
            ]
 }`

I got this from [@RickStrahl](https://weblog.west-wind.com/posts/2017/Oct/13/Opening-a-Web-Browser-with-an-HTTP-Url-from-Visual-Studio-Code)

**Comment by ritwickdey** [comment]
okay, I think, all of you using Windows Insider Version? We are using `OPN` npm library to open a browser. This saw an issue request on OPN with the same title.  https://github.com/sindresorhus/opn/issues/95

**Comment by gijoe50000** [comment]
Yep, confirmed, thanks. 
Live server opens fine in Edge when it's the default browser. Microsoft at their shenanigans again.. :-)
I wonder if it's just an error or a new upcoming feature?.. Or a way of forcing people to use Edge for a while in the hopes they'll adapt to it?

**Comment by EIVX** [comment]
I also encountered the same problem when using Webstorm, and I think the problem is in the windows10 preview system itself, hoping to get more information

**Comment by edumazzucco** [comment]
Same here :(
Probably is related to the last update of W10 Insider...
I'm using build 17692 btw.

**Comment by petercr** [comment]
Yes I've got the same issue, and am running Windows 10 **Build: `17692.rs_prerelease_flt.180625-1624`** myself and I get the same error message when trying to open _Live Server_ 
Error occurs on both VS Code stable build and Insider's Edition. 

**However it does work just fine if you open it in the browser** 
Thanks @ritwickdey your the man!! 👍 🏅 👏 😎

**Comment by patroza** [comment]
Same here on 17713, only works when Edge is default browser

**Comment by krnlde** [comment]
Build 17723 fixed it for me.

**Comment by andymabb** [comment]
I get exactly the same error trying to run browser-sync after updating to W10, build17713 (Firefox default browser) which prevents all my build NPM & Gulp processes woking automatically.

**Comment by MCanterel** [comment]
@andymabb You can also upgrade Win10 to 17723. That fixed it for me.
