### ISSUE TITLE
script command for npm script

### ISSUE THREAD

**Issue by RocMark** [ritwickdey/vscode-live-server#153]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

just wonder is there any way to use cmd or npm script to start live server
wanna bind live server start with npm script & vscode hotkey
to run specific file without select that file every time

## Environment

```html
Browser:

- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: <!-- Check which version is installed --> 
- Platform:  <!-- Mac, Linux, Windows -->
- Visual Studio Code: <!-- `code --version` -->
```

## Others

thxs for great extension !
I'm not a native English speaker
feel free to let me know where i didn't describe well enough

**Comment by rjoydip** [comment]
U don't think this could be the good use cases. @ritwickdey what you think?

**Comment by ritwickdey** [comment]
What is the use case ? I can't think. Can anyone explain?

**Comment by RocMark** [comment]
Never mind just wonder is there a way to Simultaneously start npm & live server when i change vscode settings or install some plugin that require reloading 
I'm just too lazy  i guess xd
Feel free to close this  thx  for replying !

**Comment by rjoydip** [comment]
@RocMark Actually any `vscode extension` works on `vscode` execution context. It does not work through npm script.
