### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by JakariaPUST** [ritwickdey/vscode-live-server#1530]
- Issue Type: `Bug`
- Extension Name: `LiveServer`
- Extension Version: `5.6.1`
- OS Version: `Linux x64 5.8.0-48-generic`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by JakariaPUST** [comment]
Unresponsive performance issue.
After working with a django project I created a html folder then the live server is unresponsive

**Comment by yandeu** [comment]
Maybe there are too many files in your project? Live Server watches for all file changes in your workspace.

Maybe you want to try [Five Server](https://marketplace.visualstudio.com/items?itemName=yandeu.five-server) with the settings below:
_Define the `/html` folder as root and watch only for file changes inside `/html`._

```js
// fiveserver.config.js
module.exports = {
  root: 'html',
  watch: 'html'
}
```

**Comment by JakariaPUST** [comment]
Thanks dear....
