### ISSUE TITLE
scroll to edit point

### ISSUE THREAD

**Issue by Taariqq** [ritwickdey/vscode-live-server#154]
```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[x ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

Edits below the end of screen are not visible unless you scroll to them

## Expected behavior

Browser should scroll to the point on the webpage that is being edited. Also, when you click a portion on the page the editor should scroll to that point as well.

## Environment

```html
Browser:

- [ ] Chrome (desktop) version XX
- [60.0.2 ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: <!-- Check which version is installed --> 
- Platform:  Linux Mint
- Visual Studio Code:  1.24.1
```

**Comment by rjoydip** [comment]
duplicate #41

**Comment by rjoydip** [comment]
@Taariqq https://github.com/tapio/live-server/issues/241#issuecomment-390182419

**Comment by Taariqq** [comment]
Thanks @rjoydip although the other issue, from the description, sounds like a bug, I am sorry if I wasted your time.

**Comment by ritwickdey** [comment]
Did you try to set `fullReload` settings as `true`?  Checkout the settings page full details.

If you set it as true, your browser will refresh fully on CSS changes & that will preserve scroll height position,

**Comment by rjoydip** [comment]
@Taariqq Thanks for reporting.
