### ISSUE TITLE
When i'm trying to visualise my html code.I'm seeing the Following error.How can i resolve it?

### ISSUE THREAD

**Issue by srisrinu1** [ritwickdey/vscode-live-server#1546]
// = 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf()); } parent.appendChild(elem); } } var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://'; var address = protocol + window.location.host + window.location.pathname + '/ws'; var socket = new WebSocket(address); socket.onmessage = function (msg) { if (msg.data == 'reload') window.location.reload(); else if (msg.data == 'refreshcss') refreshCSS(); }; if (sessionStorage && !sessionStorage.getItem('IsThisFirstTime_Log_From_LiveServer')) { console.log('Live reload enabled.'); sessionStorage.setItem('IsThisFirstTime_Log_From_LiveServer', true); } })(); } else { console.error('Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.'); } // ]]>

**Comment by srisrinu1** [comment]
I found Error in my code.Issue resolved.For this error it is because of  errors in the code try to check

**Comment by yandeu** [comment]
> Issue resolved

Glad to hear. Did you also check the updated [Five Server](https://marketplace.visualstudio.com/items?itemName=yandeu.five-server).
