### ISSUE TITLE
Enable https option to accept cer or pfx files

### ISSUE THREAD

**Issue by qbunia** [ritwickdey/vscode-live-server#155]
```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```
I`m windows user so I would like to see a cer or pfx files to be accepted in https settings.

**Comment by ritwickdey** [comment]
I think your requested feature is already available. You can start live server with https protocol. Have you checked the settings page?

**Comment by qbunia** [comment]
I can do that but accepted files arent cer or pfx. I would like to use cer or pfx files for certificate.

**Comment by rjoydip** [comment]
What's the error? Can you give us some screenshots?

**Comment by rjoydip** [comment]
Closing this issue due to no response.  Feel free to ping if any help needed.
