### ISSUE TITLE
Just a quick Wordpress question

### ISSUE THREAD

**Issue by thedonquixotic** [ritwickdey/vscode-live-server#156]
## I'm submitting a...
```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[x] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Just a quick question!

I'm sorry if this is an ignorant question but I am a designer learning to code and I was curious if I could use Live Server in place of a LAMP or XAMP localhost server setup? I currently using Local by Flywheel to create my localhost server but I was wondering Live Server was also able to do this? I wasn't entirely clear on it's functionality.

**Comment by rjoydip** [comment]
@thedonquixotic Please check @ritwickdey comment.
[isseu:137](https://github.com/ritwickdey/vscode-live-server/issues/137#issuecomment-392240045)

**Comment by rjoydip** [comment]
Closing this issue due to no feedback.
