### ISSUE TITLE
How to remove Live reload enabled from console?

### ISSUE THREAD

**Issue by AAhrit** [ritwickdey/vscode-live-server#16]
Hi men this is a awesome extension but where I do remove Live reload enabled? every time I save my js file that message shows in the console

**Comment by ritwickdey** [comment]
If you don't want to live reload features for specific files, you can apply exclude files by settings -
 `liveServer.settings.ignoreFiles'. 


If you want to disable the live reload feature totally. You can use wildcard in the settings. 


Let me know if it works for you or not.

**Comment by AAhrit** [comment]
I dont want to remove any feature!!!, I just want to remove the line of code that says: console.log("Live reload enabled") I dont want it to appear every time I save my code

**Comment by ritwickdey** [comment]
Yep!  I got that. It is little bit annoying when you dealing javascript. 

Okay... in next update I'll add this feature so that the 'live reload enabled' message comes only one time. :)

**Comment by ritwickdey** [comment]
Hi @AAhrit , This issue has been fixed with v2.0.0 update. Please update it from vscode marketplace 😄.
Let me know if it like it or not.

If you really like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).

**Comment by AAhrit** [comment]
Damn!!! Its great. Thanks for adding me on the changelog  +1:

**Comment by rajat8266** [comment]
Experiencing same error.
As a beginner ,where i need to make changes?

**Comment by akashutosh77** [comment]
Experiencing same error.
As a beginner ,where i need to make changes? @ritwickdey ritwickdey

**Comment by sitek94** [comment]
@akashutosh77, if you have installed live-server globally like this:
```bash
npm i -g live-server
```
Then you can do the following steps to find and edit live-server source files:
```bash
# find where live-server is installed globally
npm ls -g live-server

# cd into live-server directory
cd <whatever_was_returned_from_previous_command>
cd node_modules/live-server

# open it in your editor
code .
```

![Screen Shot 2022-01-16 at 16 52 24](https://user-images.githubusercontent.com/58401630/149667254-40b5af6c-ba30-429a-b4f7-881722cb50d5.png)

Once you have live-server source opened, you can search for "Live reload enabled" string, simply comment out/remove that line and save the file.

![Screen Shot 2022-01-16 at 16 57 30](https://user-images.githubusercontent.com/58401630/149667514-d6525420-953d-4ef8-a8c5-40d836f9d977.png)

Hope, it helps :)

**Comment by cazavi** [comment]
Experiencing same error. and im not a beginner

**Comment by G-ourav** [comment]
if you are facing this issue in function-js  
function greet() {
        console.log('Good morning');
    }

     greet();
  you have call the function in the end

**Comment by sohailX13** [comment]
@ritwickdey i am getting the error in console 'live reload enable'.plzzz can u reply ASAP, coz i have to finish my project real quick but i'm struck here.
