### ISSUE TITLE
"Go Live" is no displayed.

### ISSUE THREAD

**Issue by tori-333** [ritwickdey/vscode-live-server#160]
"Go Live" is no displayed. 
Since it was displayed until a few days ago, was there any change in version upgrade?

The "Open with Live Server" command displays an entry field but has no guidance as to what to enter.

live server version 5.0.0

**Comment by rjoydip** [comment]
@tori-333 No, there is no change in `commands/keybindings/menus`. Can you check your console? Is there any error?

**Comment by tori-333** [comment]
Entering the "http://localhost:5050/" in the "Open with Live Server" command will cause a long error on the development tool's console.
I guess this is only because I do not understand how to use this command.


console.ts:136 [Extension Host] WARNING: Promise with no error callback:5
log.ts:171   ERR Cannot read property 'uri' of undefined: TypeError: Cannot read property 'uri' of undefined
	at setOrChangeWorkspace.then.workspaceName (C:\Users\USERNAME\.vscode\extensions\ritwickdey.liveserver-5.0.0\out\src\workspaceResolver.js:46:86)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:76:971)
...
I will skip it because it is so long.


I do not know the reason why the "Go Live" button is not displayed.
It is displayed automatically while editing HTML files, right?


Sorry, Because I do not understand English, this sentence was translated by Goole.

**Comment by ritwickdey** [comment]
What is the your vscode version?

**Comment by tori-333** [comment]
VSCode version is 1.24.0

**Comment by ritwickdey** [comment]
Please give a screenshot of your Vscode workspace.

**Comment by tori-333** [comment]
I'm not change settings.
https://i.imgur.com/4bxh35I.png

**Comment by ritwickdey** [comment]
Strange! This is part of vscode api, it should not be null.

Anyway, I'need more info.
1. Is this multi-root workspace?
2. Please try a command (ctr+shift+p), 'Live Server: Change live server workspace'. Share a screenshot with us.
3. Have you tried to reinstall vscode?

**Comment by tori-333** [comment]
1. Normal workspace.
   Even when opening a single HTML file, the "Go Live" button did not appear.

2. What is this place to enter?
   https://i.imgur.com/MhfGhcZ.png

3. No. 

I am thinking of giving up.

**Comment by ritwickdey** [comment]
Yaa, I was right. This line is null.

https://github.com/ritwickdey/vscode-live-server/blob/7b955c5d5c5b4229502cde0d27d0841690560987/src/workspaceResolver.ts#L5-L6

But this is the part of vscode api, how it could be null...!! Really Strange issue. 

Can you show me a screenshot of explorer (ctrl+shift+E) window of vscode?

**Comment by rjoydip** [comment]
@ritwickdey I think null is producing from here.
https://github.com/ritwickdey/vscode-live-server/blob/7b955c5d5c5b4229502cde0d27d0841690560987/src/workspaceResolver.ts#L46

**Comment by tori-333** [comment]
"Go Live" button was displayed!

When you display explorer with Ctrl + Sfhit + E and add folder, "Go Live" button is displayed!

It seems to be a problem that no folder was registered in my workspace.

The problem was solved. Thank you.

**Comment by ritwickdey** [comment]
@rjoydip, but why? `Config.setMutiRootWorkspaceName(null);` is just resetting the user settings. & I said @tori-333 to try `Live Server: Change live server workspace` command. This command is triggering this line of code

https://github.com/ritwickdey/vscode-live-server/blob/7b955c5d5c5b4229502cde0d27d0841690560987/src/workspaceResolver.ts#L4-L16

This is null.

**Comment by ritwickdey** [comment]
Hi @tori-333 , Great. just for a asking, what doing mean by "It seems to be a problem that no folder was registered in my workspace.". What you did?

**Comment by rjoydip** [comment]
@ritwickdey Give a checking that whether workshop has any folder then apply map.

**Comment by ritwickdey** [comment]
yaa! it's one of the edge cases. Ok. Live Server will prompt an error msg from next update.

**Comment by tori-333** [comment]
JS-Collage(ワークスペース)
JS-Collage(Work Space)

まだフォルダーをワークスペースに追加していません。
You have not added the folder to the workspace yet.

フォルダーの追加
Add folder

It's OK?

**Comment by Isabellle** [comment]
Sometimes, relaunch vscode could fix the issue. Don't know why but it worked.

**Comment by thintalllade43** [comment]
my vscode not lunching

**Comment by thintalllade43** [comment]
i mean after installing the live server.
its says "Open a folder or workspace... (File -> Open Folder)"

**Comment by apolopena** [comment]
I just got the issue by simply opening a saved workspace file that had no folder added. I had to add the same folder that the workspace file was in was in to get the Live Server button to appear.

**Comment by viicktur** [comment]
here is the display message of my VS code 
Extension host terminated unexpectedly.

**Comment by corrysalim** [comment]
> JS-Collage(ワークスペース)
> JS-Collage(Work Space)
> 
> まだフォルダーをワークスペースに追加していません。
> You have not added the folder to the workspace yet.
> 
> フォルダーの追加
> Add folder
> 
> It's OK?

Thanks a lot 🙏🏻

**Comment by omrajsharma** [comment]
I am very begginer with vs code. Please can anyone ecplain in more elaborated form. this would be a great help.

**Comment by thintalllade43** [comment]
It depends.. The html file and cos file must be in a folder first.
Then you can Go live.

**Comment by thintalllade43** [comment]
Note.
The ritwickdey Vscode Live  Server is an extension. You add to your Vs Code
in other to view your written code in the web browser.

**Comment by phemmyjunior** [comment]
I had my go live button displayed before I upgraded my visual studio code and since then my go live button disappeared, I've uninstalled and re installed the live server more than 10 times and still nothing is working,pls I need help asap

**Comment by thintalllade43** [comment]
Try right clicking on the code. You might find the go live option there..

**Comment by phemmyjunior** [comment]
No it's not there even when I clicked open with live server,nothing happened

**Comment by vikramvi** [comment]
> Sorry. I English very bad.
> 
> The folder did not exist in the workspace.
> 
> https://i.imgur.com/JaCXer2.png

What's difference between workspace and folder in VSCode ?

**Comment by aishmash1010** [comment]
I was facing the same issue, I installed live server extension , which was not present and it worked.

**Comment by Galmic** [comment]
I'm also new here and had the same issue, Here's how i solve this issue.
File >> Open Folder

Then select the folder that your working on. and then you can now see the Go Live button at the bottom.

Hope this helps.

**Comment by ladykyle** [comment]
@aishmash1010  I am having the same issue with live server. Installed live server and am receiving an error message "port:5500"

**Comment by sayan2202** [comment]
when i click on live server ,then this is not working

**Comment by Patoski-patoski** [comment]
I installed Live Server but it's not running, It does not display "Go live " on the taskbar.
I cannot even run Live Server even when I right clicked.

P.S other live Preview worked except live Server
