### ISSUE TITLE
Live Server becomes unresponsive; "Waiting for 127.0.0.1"

### ISSUE THREAD

**Issue by HarryAdney** [ritwickdey/vscode-live-server#166]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[x] Other: Live Server becomes unresponsive.
```

## Current behavior

After a couple of hours use, the server stops serving. The browser taskbar shows "Waiting for 127.0.0.1"

## Expected behavior

The server wouldn't become unresponsive.

## Environment

```html
Browser:

- [x] Firefox Developer Edition version 62.0b2
- [x] probably all browsers

For Tooling issues:

- Live Server: 5.1.1 
- Platform:  Windows 10
- Visual Studio Code: 1.24.1
```

## Others

Presumably this isn't anything to do with extensions or security software since it happens after a couple of hours (I'm estimating; I haven't timed it)

**Comment by ritwickdey** [comment]
Can you please share a screenshot? Have you restarted you pc?

**Comment by HarryAdney** [comment]
Hi,

A screenshot would be of limited value; all it'll show is a blank page.
Closing vscode and reopening doesn't solve it because the server seems to
be "locked".

The only way I've found to correct it is to reboot. It's a bit of a hassle,
obviously.

Best regards,

Martin Dimmock
Owner, Chief Developer
HarryAdney Internet Services

T: 01969662871
E: martin@harryadney.com
W: https://harryadney.com

**Comment by ritwickdey** [comment]
Okay! I think it's your system's issue. That's why it's fixing after rebooting.

**Comment by HarryAdney** [comment]
Ok, cheers.

Best regards,

Martin Dimmock
Owner, Chief Developer
HarryAdney Internet Services

T: 01969662871
E: martin@harryadney.com
W: https://harryadney.com

**Comment by contentfree** [comment]
I disagree it's his system's issue (insofar that it's related to live server). I have a similar issue where, upon saving, _something_ goes wrong with live server and looking at VS Code's Process Explorer shows extensionHost at 100% CPU. Killing extensionHost from the process explorer (and restarting it in the resulting error dialog) "fixes" it for a time. But it's certainly something going on with live server (and probably an interaction with another extension).

**Comment by sufiyanpk7** [comment]
> I disagree it's his system's issue (insofar that it's related to live server). I have a similar issue where, upon saving, _something_ goes wrong with live server and looking at VS Code's Process Explorer shows extensionHost at 100% CPU. Killing extensionHost from the process explorer (and restarting it in the resulting error dialog) "fixes" it for a time. But it's certainly something going on with live server (and probably an interaction with another extension).

how  to fix

**Comment by Chanchal121** [comment]
Rebooting the system doesn't fix the issue. How to fix this?

**Comment by joeycodeMAN** [comment]
For any noobs like myself, this is the behavior if you have loop errors in your code also.

**Comment by bworkman53** [comment]
I was having the same problem.
I found that switching to Google Chrome as the default browser worked for me

**Comment by zubiatahseen1** [comment]
> For any noobs like myself, this is the behavior if you have loop errors in your code also.

Thanks a lot. This fixed my issue.
