### ISSUE TITLE
Mailbox Field Bug

### ISSUE THREAD

**Issue by fisheva** [ritwickdey/vscode-live-server#167]
## I'm submitting a Bug report.

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

Live Server automatically changes the page structure when it encounters a mailbox field.
<img width="1679" alt="qq20180626-224621 2x" src="https://user-images.githubusercontent.com/17448419/41920917-469d3382-7994-11e8-81c8-f3ac09cb390f.png">

## Expected behavior

Rendering the page correctly.
<img width="1679" alt="qq20180626-224859 2x" src="https://user-images.githubusercontent.com/17448419/41921047-8e229e0e-7994-11e8-9534-42c6652ca079.png">

## Environment

```html
Browser:

- [x] Chrome (desktop) version 66.0.3359.181 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 5.1.1 <!-- Check which version is installed --> 
- Platform:  Mac <!-- Mac, Linux, Windows -->
- Visual Studio Code: 1.24.1<!-- `code --version` -->
```

## Others
If you want to reproduce the bug shown above, here is [my blog project link](https://github.com/fisheva/Eva-Blog).

**Comment by ritwickdey** [comment]
I don't think it is live server's issue. This is the issue of any extension that you've installed in chrome.

-----

### Workaround: 
Open the server in Guest or incognito window .

------
Anyway, I've tried on my laptop. So issue so far.
![image](https://user-images.githubusercontent.com/18099464/41925625-c1996aec-798a-11e8-8a30-cf39cbac0985.png)

**Comment by fisheva** [comment]
It works correctly after I closed all my Chrome extensions. Now I'm trying to find out which one does the matter.
Thanks for your reply! Live Server is awesome! I would rate it five stars!
