### ISSUE TITLE
Auto reload no longer working

### ISSUE THREAD

**Issue by Velkas** [ritwickdey/vscode-live-server#171]
Problem: Live Server isn't auto-reloading anymore

Expected Result: Saving any file in an open folder with Live Server running will refresh the browser

Steps taken to remedy:
- Reinstall firefox
- Reinstall extension
- Reinstall VS Code
- Ensured user settings forces live server settings such as full reload and wait time.

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  (no issues found via search)
[ ] Feature request
[ ] Documentation issue or request
[ x] Other: Help request if this ends up not being a bug
```

For Tooling issues:

- Live Server: 5.1.1
- Platform:  Windows
- Visual Studio Code: 1.24.1
- Firefox Version: 61.10 
```

**Comment by rjoydip** [comment]
@Velkas Sorry for the late response. Can you check this thread [link](https://github.com/ritwickdey/vscode-live-server/issues/82)

**Comment by amirghiasi** [comment]
in my case after change my work folder location from "user\my user name\.vscode" to another folder live server reload worked again.

**Comment by jarekj** [comment]
If someone, like me, is looking for a solution. For me worked removing "#" hash from folder name.
