### ISSUE TITLE
Error message while declaring new variable

### ISSUE THREAD

**Issue by VitoPareto** [ritwickdey/vscode-live-server#176]
## I'm submitting a...

![screenshot_1](https://user-images.githubusercontent.com/29175511/43398897-a6ce5c7e-9409-11e8-8563-6182260c8660.png)
![screenshot_2](https://user-images.githubusercontent.com/29175511/43398903-a8cd2dde-9409-11e8-86bd-864a8a6aa96e.png)

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

I can't name variable with the same name ('i' in this example) even if i comment out or delete previous declaration. It looks like this extension somehow saving it.

**Comment by rjoydip** [comment]
@VitoPareto This is a javascript error, not `vscode-live-server`

**Comment by ritwickdey** [comment]
check line number 1, `i` is already declared. 😺

**Comment by VitoPareto** [comment]
@ritwickdey  Number one line had only `//FOR LOOPS` comment, eitherway I couldn't use variable with name 'i' in any file, but when i opened google chrome console without live-server everything was fine.  Closing and restarting extension didn't help either. Finnaly, restaring system solved my problem. Thank you for the time devoted to helping me.
