### ISSUE TITLE
live server refresh remote page in browser randomly without any change of my local file

### ISSUE THREAD

**Issue by vimtt** [ritwickdey/vscode-live-server#177]
Issue Type: <b>Bug</b>

live server refresh remote page in browser randomly without any change of my local file, the operator system is win10

Extension version: 5.1.1
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.56GB (2.22GB free)|
|Process Argv|D:\Program Files (x86)\VSCode-win32-ia32-1.25.1\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rjoydip** [comment]
@vimtt Can you provide some video/screenshot?

**Comment by vimtt** [comment]
![2018-08-12_104909](https://user-images.githubusercontent.com/3397136/43997983-9f75fa86-9e1d-11e8-8f4e-61de4006beb5.jpg)

**Comment by vimtt** [comment]
It's maybe the problem of the win10 system  or the nodejs dll or even the hardware ? How can I diagnose this? It's refresh randomly at the beginning, but than OK.

**Comment by vimtt** [comment]
![2018-08-13_085849](https://user-images.githubusercontent.com/3397136/44009109-d9fc5858-9edb-11e8-9d2e-b0413684ab50.jpg)

I found that the file detected changed is not changed since 2018-4-20.

**Comment by vimtt** [comment]
the chokidar check the access time, not the modified time for determining the change of the file.


![2018-08-13_095319](https://user-images.githubusercontent.com/3397136/44009579-8f67c27e-9edf-11e8-8ba1-2274e2313b10.jpg)

**Comment by rjoydip** [comment]
@vimtt may the issue is in `chokidar` module

**Comment by vimtt** [comment]
@rjoydip I had fixed this problem by disable the file access time update options in regedit of the win10 system.
[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\FileSystem]
"NtfsDisableLastAccessUpdate"=dword:80000003
