### ISSUE TITLE
.settings.ignoreFiles doesn`t work

### ISSUE THREAD

**Issue by qbunia** [ritwickdey/vscode-live-server#188]
I tried many different configurations and seems like its not working at all. I even tried to use .liveserverignore still nothing. Can you fix this?

I need this fix so I could handle my problem that I`m having with liveserver now:
1. I have less files in my project so I setup gulp task to watch changes in less files. Whenever it sees the change it compiles all less into single css file. Liveserver refreshes after saving less file but I still dont see any changes on browser until I refresh it again.
2. I have html templates used in angularjs. Whenever I save any of these templates they are compiled into ts/js file so basically browser refreshes 2 times. First on html template change then on ts/js file change.

**Comment by rjoydip** [comment]
> I have html templates used in angularjs. Whenever I save any of these templates they are compiled into ts/js file so basically browser refreshes 2 times. First on html template change then on ts/js file change.

Have you changed the default liveserverignore  `settings`?

**Comment by qbunia** [comment]
Where is default liveserverignore stored? Because I dont see it in my folders.

**Comment by qbunia** [comment]
Tried setting up:
    "liveServer.settings.ignoreFiles": 
    [
        "**/*.css"
    ]

and it doesnt work. Css files are still not ignroed.

**Comment by qbunia** [comment]
@danieljdemarco Hello?

**Comment by David1991dev** [comment]
Hey qbunia,
You have to create the .vscode folder in your main folder, not the actual one, and you have to restart the port.

**Comment by qbunia** [comment]
Thanks it helped me out

**Comment by drodsou** [comment]
My problem was specifying a single file e.g. `"data.json"`, but it worked changing to a pattern/glob: `"data.json*"`
