### ISSUE TITLE
Can I turn off the live refresh function?

### ISSUE THREAD

**Issue by wgbx** [ritwickdey/vscode-live-server#189]
I looked at the documentation and found that it didn't seem to turn off the real-time refresh feature? Because the project I am using uses Easyui, after the change, the page will be refreshed and it will return to the homepage. I want to turn it off.

**Comment by rjoydip** [comment]
No there is no options for turn off live reloading

**Comment by Far-Se** [comment]
1. Close the server.
2. Add this in settings.json `"liveServer.settings.ignoreFiles":["**"],`
3. Open server.

**Comment by nikoladim123** [comment]
Stupid crap wont let me edit settings.json file. this is the worst product after windows 10
