### ISSUE TITLE
Live Server does not display graphics

### ISSUE THREAD

**Issue by techMod** [ritwickdey/vscode-live-server#19]
When I open the server, and let the settings untouched or set the root of the server it is not displaying images an graphical elements.

**Comment by ritwickdey** [comment]
Sorry. I don't get that. Please explain on more details. What you are getting error?

**Comment by techMod** [comment]
Sorry, my Bad. Whenever I want to display graphics like so:

<img src="file///:/path/to/file.png">

The server just shows the alt text, opening the File directly in chrome displays fine. 

Also when I set the server root, I get an invalid path message. At least thats the case with the portable .zip version.

**Comment by ritwickdey** [comment]
okay. I got that. This a security purpose issue.  Your browser (chrome) doesn't allow to use `file:///` protocol to use local resource. Think about if chrome allow it, any website can read your files with help of `file:///` protocol. 

Use relative path always.


For more details : https://stackoverflow.com/questions/23969953/not-allowed-to-load-local-resource-file-c-jpg-java-ee-tomcat

**Comment by ritwickdey** [comment]
Here is another resource . https://stackoverflow.com/questions/39007243/cannot-open-local-file-chrome-not-allowed-to-load-local-resource



Hopefully you get the point why it is not working.

**Comment by techMod** [comment]
The funny thing is, when I open the file directly in chrome and not through the extension it displays the pictures fine. But I get the point though.

**Comment by ritwickdey** [comment]
Hmm.. Obviously. It makes sense. When you open a HTML file to chrome, this is just a local file. So,a local file can access local resource using `file:///` protocol. But when you're using localhost (loopback server),  chrome is denying access of local resource. 😄

**Comment by techMod** [comment]
Okay finally I hot IT xD
