### ISSUE TITLE
Mount a directory to a route doesn't works

### ISSUE THREAD

**Issue by JuanJoseGonGi** [ritwickdey/vscode-live-server#191]
I have two folders in the root. "/app" and a "/.tmp". In the first one there is an index.html file and a subfolder "/styles" with main.scss. In the second one there is a subfolder "/styles" that contains main.css (The main.scss already processed).

In my settings I have

```
{
  "liveServer.settings.ChromeDebuggingAttachment": true,
  "liveServer.settings.file": "index.html",
  "liveServer.settings.root": "/app",
  "liveServer.settings.mount": [
    ["/styles", "../.tmp/styles"]
  ]
}
```

**Only load the index.html**

**Comment by markbjerke** [comment]
The same problem, mount doesn't seem to work.

**Comment by gijswijs** [comment]
Same problem. Mount doesn't seem to work.

**Comment by gijswijs** [comment]
Checked out the source code.

The mount works, but you have to reference the folder from the workspace root. And you have to use the period, otherwise it starts looking from the drive root.

So

```
"liveServer.settings.mount": [
  ["/styles", "./.tmp/styles"]
]
```

**Comment by ayelsew** [comment]
Just for common knowledge.
I spend a lot of time trying to use wildcards to mount my paths to dir like: `["/*js", "./out"]`. 
Analyzing that code, I saw that the server HTTP package, used by liver-server is the [Connect](https://www.npmjs.com/package/connect), And it doesn't support wildcards as you can see in this issue: [app.use documentation](https://github.com/senchalabs/connect/issues/1060#issuecomment-59935703).

So if you are working with distributed files in any directories on your workspace, and these files for some reason are represented by `/` (root path),

In my case I have:
```
|--- src
|      \ index.html
|--- out
       \ index.js
```    
Considering do this:

```JSON
    "liveServer.settings.mount": [
        ["/", "./src"],
        ["/", "./out"],
    ],
```
It will look up `index.html` at `./src`, `index.js` at `./src` (didn't will be found) and at `./out` (here works).
