### ISSUE TITLE
I Can't Get Live Server to Work On MacBook

### ISSUE THREAD

**Issue by js76155** [ritwickdey/vscode-live-server#196]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```
## Current behavior

I am new to Visual Studio Code and to writing code. VSC is working perfectly. Sadly, after installing and activating the Live Server extension I get an error when trying to start it in a browser. The error message is: Open a folder or workspace... (File -> Open Folder)
All I am doing is working on HTML and CSS. If I open the HTML page in Chrome, I can update it by using cmd tab and cmd r. 

I uninstalled the extension and updated the version of VSC. I then reinstalled the LS extension and get exactly the same result.    

## Expected behavior

The VSC HTML page I'm working on would open in Chrome and instantly update as I make changes.

## Environment

```html
Browser:

- [X ] Chrome (desktop) Version 69.0.3497.81 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 5.1.1
- Platform:  Mac OS High Sierra version: 10.13.6
- Visual Studio Code: Version 1.27.1 (1.27.1)
```

## Others

I tried installing another extension: Live Server Preview 0.1.2 and couldn't get this to work either. I have also searched YouTube and GIT for a solution but had no luck.

**Comment by vstegen** [comment]
The extension won't work if you only have a file open. Use 'File -> Open Folder' in VSCode to open the directory your files are in. Then open the respective HTML file. You can start Live Server now and it should work.

**Comment by js76155** [comment]
You are quite correct. IT WORKS!! Thank you for providing this simple yet effective solution.

**Comment by theProtestant** [comment]
I was having this issue, then followed the above. I got the 'Go Live' button to show up, but now when press it it shows this error: 
"Something is went wrong! Please check into Developer Console or report on GitHub."
<img width="451" alt="Screen Shot 2020-07-07 at 3 29 24 PM" src="https://user-images.githubusercontent.com/64393050/86839202-c145dd80-c066-11ea-915f-36429197f0ce.png">

**Comment by 5ascha** [comment]
Hello people, 
unfortunately my browser does not open automatically. I have already selected "Chrome" in the settings, yet without success. Is there a mac os setting that I need to make? It works via the manual path in the browser.

Thanks in front,
many greetings
Sascha

**Comment by aizehaer** [comment]
Wowwww. It is working ! It took me days to figure out. Thank you. I could not use the command 'File ->Open Folder' directly.(maybe it is not a command). Instead I open the folder first in welcome page and then use the extension.

**Comment by aizehaer** [comment]
Another tip from me. If you get tired from switch back forth from the web page and your code. You can use extension --browser preview. First, open live server. Second, open browser  preview and cope the address. Third, paste the address onto the browser preview side panel. voilà, there you have it, Vs code and webpage side by side. And you can see the live updated.

**Comment by officialsnowwisdom** [comment]
This is what solved mine:

uninstalled the live server and install another type of live server, then make use of your new live server and make sure it is working. Then uninstall it and install the main live server(the live server that was having the issues)

hope it works for you guys :)

**Comment by Jasleenphutela** [comment]
when i rum live server nothing is opened . i am just shown port 5500 nothing else

**Comment by ton21** [comment]
> This is what solved mine:
> 
> uninstalled the live server and install another type of live server, then make use of your new live server and make sure it is working. Then uninstall it and install the main live server(the live server that was having the issues)
> 
> hope it works for you guys :)

Thanks! This solved mine.
