### ISSUE TITLE
CSS Mime type error

### ISSUE THREAD

**Issue by dominik-korsa** [ritwickdey/vscode-live-server#197]
## Current behavior

`Refused to apply style from 'http://127.0.0.1:5500/website/display/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
When loading a CSS file I get an error like above, and the stylesheet doesn't load.

## Expected 

Mime type of the CSS file would be **text/css** instead of **text/html**. It might be a good idea to use the [mime-type](https://www.npmjs.com/package/mime-type) npm package to dynamically assign the style.

## Environment

- Chrome (desktop) version **69.0.3497.81**
- Live Server: **5.1.1**
- Platform:  **Windows 10 Home 64bit**
- Visual Studio Code: **1.26**

**Comment by dominik-korsa** [comment]
# Update
The type was **text/html** because that was a 404 error. My bad 🥇

**Comment by rajeev14ranjan** [comment]
For unsupported stylesheet MIME type error. Please check the network tab. This usually happens when there is a typo in file/path name. The browser gets 404 error in response which cannot be applied like css.

**Comment by krupenja** [comment]
Another thing to keep in mind: after you fix the path, you might need to do a hard reload in your browser (`ctrl/cmd+shift+R` in Chrome) to bypass cache.

**Comment by Mumbere7** [comment]
Most of the time people get CSS MIME error could be because of the wrong path of css file in your code

**Comment by dileepxdn** [comment]
I renamed style.css with styles.css 
Problem solved for me.

**Comment by bertil291utn** [comment]
Thank @krupenja  your [comment](https://github.com/ritwickdey/vscode-live-server/issues/197#issuecomment-542680865) saved me

**Comment by harishs3** [comment]
i changed from style.css to styles.css and did a hard reload and tried downloading the npm mime-type package and nothing is still working. the same is happening when I put app.js in the source code. any help?

**Comment by maulidailham** [comment]
no no no, i got this with RIGHT path, why is it closed? because OP too dumb?

**Comment by skdza** [comment]
I'm getting the same error with the correct path and everything. What is wrong??
