### ISSUE TITLE
Startup page

### ISSUE THREAD

**Issue by zorgoz** [ritwickdey/vscode-live-server#2]
Even if I have a html page opened in the acive editor form an other folder, "Go Live" will serve the file with the same name from workspace root.

_appModel.ts (114):_ `let rootPath = WorkSpacePath ? WorkSpacePath : documentPath;`
Will `WorkSpacePath` ever be null?

**Comment by ritwickdey** [comment]
First, _Thanks a lot for the feedback._

`WorkSpacePath`  will be `Undefined` if user open a single file - no workspace.

anyway, I don't got your point. Please clear me. 
Live Server will open a server form Workspace root. if workspace is not available then it will start server from current active document's root. 

you mentioned "**an other folder**". Is _the folder_ is not sub folder of the workspace?

I got another issue in _appModel.ts (114):_ `if (fileExtension != "html") fileName = null;`. That should be `fileExtension != ".html"`

**Comment by zorgoz** [comment]
Hello!
Ok, I understand. But this is still a hard restriction: why should the _workspace root_ be the _web root_ 
 as well? Mine is a subfolder of the workspace.
It is confusing anyway: the _file name_ is from the active editor, but the folder served is totaly different. What if there is no file with the same name in the workspace root? You will get a directory listing... quite useless.
I think that you should let the user decide if he/she wants to serve the currently opened file or a specific file from the workspace - I am sure, the later will be the most used scenario. 
I suggest you add a setting (like the port), where the user can specify any html file relative to the workspace root. If it is missing then it should fall back to serving the currently edited file (indifferent if there is a workspace or not).

**Comment by ritwickdey** [comment]
Okay. I got your point. I definitely try to add the settings :)

**Comment by ritwickdey** [comment]
Hi, I added the settings. :) Yet I am not published the version. Tomorrow I'll push the version to markplace. okay?

**Comment by zorgoz** [comment]
Hello,
Ok! Thanks.

(mobilról küldve)

2017. júl. 3. 13:27 ezt írta ("Ritwick Dey" <notifications@github.com>):

**Comment by ritwickdey** [comment]
Hi, I published a new version with the features. let me know if you like it or not. :)

For now, I am closing this to issue list.
Feel free to suggest me or report bug :)
