### ISSUE TITLE
How to force opening a static page over https?

### ISSUE THREAD

**Issue by Xaqron** [ritwickdey/vscode-live-server#20]
Hello and thanks for your nice extension.
I needed to open a HTML file with some WebRTC functionality but that needs serving the page over HTTPS or functionality is refused by browser.
How to do that?

**Comment by ritwickdey** [comment]
As of now, you can't use HTTPS but soon, this will be added....... 😄...

**Comment by ritwickdey** [comment]
Feature is a added from v3.0.0. Please give a try.


If you like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).
