### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by Saidusmon** [ritwickdey/vscode-live-server#203]
When I am running my HTML file on vs code through "open with live server option" vs code is showing an error saying Open a folder or Workspace

<img width="1042" alt="screen shot 2018-09-24 at 14 16 27" src="https://user-images.githubusercontent.com/43481828/45951659-abd40080-c004-11e8-86b6-c1d0557a32cc.png">

**Comment by rjoydip** [comment]
You need a project working directory
