### ISSUE TITLE
certificate error if proxyUri uses https

### ISSUE THREAD

**Issue by bkroll** [ritwickdey/vscode-live-server#207]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

My proxy settings are this:
```
    "liveServer.settings.proxy": {
      "enable": true,
      "baseUri": "/magicpath/",
     "proxyUri": "https://sub.domain.tld/magicpath/"
    },
```

In an HTML file, I have:

```
<iframe src="/magicpath/test.txt"></iframe>
```

The Iframe contains the following error message:
```
Error: Hostname/IP doesn't match certificate's altnames: "IP: 127.0.0.1 is not in the cert's list: "
at Object.checkServerIdentity (tls.js:222:17)
at TLSSocket.<anonymous> (_tls_wrap.js:1109:29)
at emitNone (events.js:106:13)
at TLSSocket.emit (events.js:208:7)
at TLSSocket._finishInit (_tls_wrap.js:637:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) 

```
## Expected behavior

When displaying the iframe in live server preview, it should display the test file's contents.

## Environment

```html
Browser:

- [X] Chrome (desktop) version 69.0.3497.10 and 71.0.3554.2
- [X] Firefox version 62.0.2 (64-Bit)
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 5.1.1
- Platform:  Windows 10
- Visual Studio Code: 1.27.2
```

## Others

I have tried setting `http.proxyStrictSSL": false`, but that did not affect the problem.

**Comment by bkroll** [comment]
We created a local workaround for that problem in our use case, so closing this issue.

**Comment by iamjrock** [comment]
@bkroll, I am having this issue as well.  Would be able to tell me roughly what your local workaround is?

**Comment by bkroll** [comment]
Sorry for the late answer. This workaround meant changes to our development environment which are specific to the software we use and work on. It even meant moving away from using vscode-live-server for certain areas of our work.
