### ISSUE TITLE
Image Tags with Local Images

### ISSUE THREAD

**Issue by MarkWhite1961** [ritwickdey/vscode-live-server#2083]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ x] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

I have folder with various HTML and CSS pages.

The folder also has images which are in sub-folders:

[Root]
--index.html
--style.css
--[folder]
----image.jpg

In my code I have 

<img src="folder/image.jpg" alt="Dog" />

The image is not showing.

## Expected behavior

Is it possible to display the image?

## Environment

```html
Browser:

- [ x] Chrome (desktop) version 93.0.4577.82
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 14,941,894
- Platform:  Windows 10 64bit
- Visual Studio Code: 1.60.1
```

**Comment by MarkWhite1961** [comment]
I fixed it by adding a leading . on the paths.
The project was part of a heirarchy.

**Comment by Illegal-Services** [comment]
this worked for me:

instead of this link:
http://127.0.0.1:5500/
uses that:
http://localhost:5500/
