### ISSUE TITLE
"liveServer.settings.CustomBrowser": "chrome" not working

### ISSUE THREAD

**Issue by glassd** [ritwickdey/vscode-live-server#209]
## Current behavior

Still opens my default browser regardless of setting

## Expected behavior

Open the browser specified in the setting

## Environment

VSCode - Insiders Mac

This happens even after a restart of the program. It just appears to ignore the setting completely.

**Comment by glassd** [comment]
Please disregard. This issue was being caused by Chrome and not the plugin. Good idea to fallback to default browser on failure to launch.

**Comment by Magistern** [comment]
I have the same issue. Would you like to share what caused Chrome to prevent from opening?
