### ISSUE TITLE
Error on port 5500

### ISSUE THREAD

**Issue by aspannas** [ritwickdey/vscode-live-server#217]
When I try to go live I get the error "Error on port 5500" and I've tried to change the port but I get the same message again but with the new port. Am I doing something wrong?

And I've tried unistalling the extension and VS Code, but the error remains.

**Comment by AngryDW84** [comment]
I solved this problem.
First, open the setting.json file.
Next to Default User Settings
In User Setting, override your setting. 
I override the following by adding the following and using port 5501 was the solution.
"libServer.Settings.port": 5501[
![smartselectimage_2018-12-04-17-09-32](https://user-images.githubusercontent.com/38788799/49427848-c0442e80-f7e7-11e8-8edc-eb73a0532273.png)
](url)

**Comment by aberrantartist** [comment]
This is probably a simple question to answer, but I am just starting to get into development and I don't know how to get into that settings.json file.  Where is it located and how do I access it? I've been looking for it and checked multiple articles, but I can't find it.
