### ISSUE TITLE
Always show "Live Reload is not possible as body or head tag or defined tag is missing in HTML"

### ISSUE THREAD

**Issue by zhengshuai1001** [ritwickdey/vscode-live-server#23]
When I save the file, it always shows "Live Reload is not possible as body or head tag or defined tag is missing in HTML"

**Comment by ritwickdey** [comment]
Add body or head tag in your HTML. It will not prompt again. 


By the way, I'm getting requests to add a option show that we can disable the warning ⚠. Please wait a few hours. Today I'll release another update. :)

**Comment by zhengshuai1001** [comment]
@ritwickdey Thank you very much.

By the way, My HTML has the body and head Tags. :grin:

**Comment by ritwickdey** [comment]
This issue has been fixed with v2.1.1 update. Please update it from vscode marketplace 😄.

If you like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).
