### ISSUE TITLE
Live server caused m1 to go to 70+ % usage

### ISSUE THREAD

**Issue by M1K1B** [ritwickdey/vscode-live-server#2319]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[* ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

While building web app, I wanted to test HTML page and ran live server (On m1 supported vs code). In less than 5 minutes of running, MacBook started throttling(~50% of CPU usage increase) and overheating.

## Expected behavior

The desired behavior would include CPU getting utilized ~10% more and a slight heat increase.

## Environment

```html
Browser:

- [*] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: v5.6.1
- Platform:  MacOS Monterey 12.1
- Visual Studio Code: 1.63.2 (arm64)
```

**Comment by ritwickdey** [comment]
I'm using M1 now. 

Can you help me to reproduce the scenario?

**Comment by M1K1B** [comment]
Of course, I lunched vs code beside spotify and brave browser, created simple HTML page with boilerplate code, CSS page and linked them in HTML. Then, I started liveserver on that HTML, everything was working fine, the only issue is that after around 5 minutes of use, I noticed extreme overheating and CPU was running on ~75%

**Comment by ritwickdey** [comment]
What's the size of the HTML file including CSS & JS ? I'll try to reproduce in my local.

**Comment by ritwickdey** [comment]
Or if you can share a sample with me, then I'll be far better.

**Comment by M1K1B** [comment]
There is 2 files, on is empty style.css, and other is index.html.
Code in HTML:
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="style.css">
</head>
<body>
    
</body>
</html>`

that's it

**Comment by M1K1B** [comment]
There are two files, empty style.css, and HTML with this code:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="style.css">
</head>
<body>
    
</body>
</html>

**Comment by ritwickdey** [comment]
I tried. Not able to reproduce. :(

**Comment by M1K1B** [comment]
No worries, thank you for trying!
