### ISSUE TITLE
it is not showing 

### ISSUE THREAD

**Issue by TANMAY214** [ritwickdey/vscode-live-server#2326]
Issue Type: <b>Bug</b>

go live option is not showing

Extension version: 5.7.1
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (12.66GB free)|
|Process Argv|--crash-reporter-id 922d57d6-ff87-4d75-821d-4500b7812f01|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422343
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30424895
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710:30416614

```

</details>

**Comment by ritwickdey** [comment]
Do you have `HTML/CSS/SVG` files in your folder?

Activation events are changed due to performance reasons. 
https://github.com/ritwickdey/vscode-live-server/commit/620738b3cf3bfbd6d3f2ba255290db1f3a1c4bfd

BTW, You can right-click to an HTML file and choose `open with live server`

**Comment by anthon38** [comment]
As far as I'm concerned the button shows up only if I open an html or css file. If the session starts on a js file for example, the button is absent.

**Comment by ritwickdey** [comment]
yup @anthon38, you're right.  there is a small bug. 
https://github.com/ritwickdey/vscode-live-server/blob/620738b3cf3bfbd6d3f2ba255290db1f3a1c4bfd/package.json#L35

It should be `onLanguage:javascript`

Fixing right now. Thanks @anthon38

**Comment by ritwickdey** [comment]
Published to vscode marketplace. Pls upgrade to the latest version and let me know. 
For now, I'm closing the issue.
