### ISSUE TITLE
Electron use high CPU.

### ISSUE THREAD

**Issue by zhuozhiyongde** [ritwickdey/vscode-live-server#2327]
## Once Live Server starts, a process called Electron takes up a lot of CPU.

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

I made sure that the problem was caused by Live Server (once Liver Server was turned on, you could see a steep increase in the activity monitor) and that it was not related to code like HTML or CSS (on my other Windows device with the same files without any problems). This problem can recur (after rebooting my Mac or replacing the HTML file). However, this problem has only recently appeared, and obviously it did not occur before, and I did not update the system or anything like that.

## Expected behavior

I don't think Live Server should use so much CPU.

## Environment

```html
Browser:

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ x] Safari (desktop) version 14.1.2 (16611.3.10.1.6)
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server:  VS Code Extensions
- Platform:  macOS Big Sur 11.6.2 (20G303), on MacBook Pro (13-inch, 2017, intel CPU)
- Visual Studio Code: 
Version: 1.63.2 (Universal)
Submit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

## Others
Here is a screenshot of activity monitor:
<img src="https://s4.ax1x.com/2022/01/20/7yGolj.png" alt="7yGolj.png" border="0" />

**Comment by ritwickdey** [comment]
Hi @zhuozhiyongde, Can you disable all other extensions and try one again? and Is auto-save on?

**Comment by zhuozhiyongde** [comment]
> Hi @zhuozhiyongde, Can you disable all other extensions and try one again? and Is auto-save on?

Sorry, I just saw your reply.
I do have autosave turned on and have some plugins like formatting code, HTML related, but after I unset/disable all the extensions that may cause problems, the problem still persists.
Here is the result after executing the `lsof -i:5050` command.
```
→ lsof -i:5500
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
com.apple 5523 zhuozhiyongde 30u IPv4 0x3de2f2732e470221 0t0 TCP localhost:51605->localhost:fcp-addr-srvr1 (ESTABLISHED)
com.apple 5523 zhuozhiyongde 39u IPv4 0x3de2f2733ec943a9 0t0 TCP localhost:51607->localhost:fcp-addr-srvr1 (ESTABLISHED)
Electron 5780 zhuozhiyongde 33u IPv4 0x3de2f2733ec94dd1 0t0 TCP :fcp-addr-srvr1 (LISTEN)
Electron 5780 zhuozhiyongde 40u IPv4 0x3de2f273404e3ac1 0t0 TCP localhost:fcp-addr-srvr1->localhost:51607 (ESTABLISHED)
Electron 5780 zhuozhiyongde 51u IPv4 0x3de2f2733ec63f11 0t0 TCP localhost:fcp-addr-srvr1->localhost:51605 (ESTABLISHED)
```
Meanwhile, when live server is not on, executing this command does not return any result.
I really can't understand this sudden exception, and I carefully recalled that the only suspicious action before the exception occurred was that I had set up an IP Pool program, but I confirmed that it had exited.
I hope you can take the time to help me, thank you!

**Comment by zhuozhiyongde** [comment]
Here is the result after executing the `ps -ef | grep Electron` command:
```
→ ps -ef | grep Electron
  501  5386     1   0  7:10AM ??         4:05.35 /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  501  5394     1   0  7:10AM ??         0:00.03 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Helpers/chrome_crashpad_handler --no-rate-limit --monitor-self-annotation=ptype=crashpad-handler --database=/Users/zhuozhiyongde/Library/Application Support/Code/Crashpad --metrics-dir=/Users/zhuozhiyongde/Library/Application Support/Code --url=appcenter://code?aid=de75e3cc-e22f-4f42-a03f-1409c21d8af8&uid=59102394-fa95-4a3a-a092-cf0c78477ab1&iid=59102394-fa95-4a3a-a092-cf0c78477ab1&sid=59102394-fa95-4a3a-a092-cf0c78477ab1 --annotation=_companyName=Microsoft --annotation=_productName=VSCode --annotation=_version=1.63.2 --annotation=prod=Electron --annotation=ver=13.5.2 --handshake-fd=27
  501  6791  5386   0  9:03AM ??         3:00.06 /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node --inspect-port=0 /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork --type=extensionHost --skipWorkspaceStorageLock
  501  6801  6791   0  9:03AM ??         0:00.51 /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=6791
  501  6802  6791   0  9:03AM ??         0:00.26 /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=6791
```

**Comment by zhuozhiyongde** [comment]
Oh, I think I've found the reason why Live Server uses such a high CPU.
I copied all the font-awesome resources to my workspace, which may cause frequent and unnecessary use of CPU to check each file for changes (actually, it has more than 20,000 files in the directory).
