### ISSUE TITLE
Sometimes after saving changes the liveserver displays a blank page

### ISSUE THREAD

**Issue by ShadowCrafter011** [ritwickdey/vscode-live-server#2332]
When I start the liveserver in vscode everything seems to be working fine. But sometimes after saving my file the server just displays a blank page. The issue can be fixed by reloading the page, but that is really annoying and I'm using live server just to not have to do that. I'm not sure what causes this to happen, seems to be random. Any help is appreciated
EDIT: after it displays the blank page it just stops reloading after saved changes

**Comment by ritwickdey** [comment]
Fixed?
