### ISSUE TITLE
Go Live button does not appear if an HTML file hasn't been opened in the editor

### ISSUE THREAD

**Issue by MattBrooks95** [ritwickdey/vscode-live-server#2334]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[x ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior
The button to start the server only appears in the bottom-right of VSCode after the user has opened a HTML file in the editor. For example, if you are working on a SPA, the button not appearing while the user is editing a Javascript or Typescript file is annoying.

I noticed and confirmed in the FAQ that you can open the server with the alt+l -> alt+o chord, but some of the members on my team prefer the UI button.

After opening an HTML file once, the Go Live button appears in the bottom as it should.

## Expected behavior
If there are live server settings in the Vscode settings file, the button should be displayed regardless of what file is currently being edited.

It used to be this way.

## Environment

```html
Browser:

- [ x] Chrome (desktop) version XX

For Tooling issues:

- Live Server: v5.7.4 
- Platform:  Windows
- Visual Studio Code: 1.63.2
```

**Comment by ritwickdey** [comment]
Yes, there was some performance issue. That's why the activation event is recently changed. https://github.com/ritwickdey/vscode-live-server/commit/1b8f82cea4b1fe61a601657220cbd31c2dbfc2aa 

I can add "language:typescript" as one of the activation events.

**Comment by MattBrooks95** [comment]
I see. Adding typescript as an activation event would be appreciated, but would it be possible to make this configurable in some way?

Is there anything that we can do to make this button appear all the time, without waiting for an update?

I actually do not use VsCode myself, I am speaking on behalf of some of my teammates.

**Comment by ritwickdey** [comment]
Sure. I'll add this.

**Comment by MattBrooks95** [comment]
Awesome! Thank you.

**Comment by ritwickdey** [comment]
It's fixed in last version
