### ISSUE TITLE
VSC Live server Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by gfdossa** [ritwickdey/vscode-live-server#2339]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ x] Other: <!-- Please describe: -->
```

## Current behavior

I'm new to using Visual Studio code. I downloaded live server but whenever I "go live" I get the error "
Error: connect ECONNREFUSED 127.0.0.1:80
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)"

The file is opening http://127.0.0.1:5500/index.html

## Environment

```html
Browser:

- [ x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server:  1.63.2 
- Platform:  <!-- Mac, Linux, Windows -->
- Visual Studio Code: <!-- `code --version` -->
```

**Comment by ritwickdey** [comment]
Hi, please check the settings. I think you've added `80` port.  You can't open 80 port without `sudo` permission. Please change that.

**Comment by gfdossa** [comment]
> Hi, please check the settings. I think you've added `80` port. You can't open 80 port without `sudo` permission. Please change that.

Thank you for your reply! I added " "liveServer.settings.port": 0," to the settings.json and changed the proxyURI to http://127.0.0.1 but it's still opening to 127.0.0.1:80 and giving me the same error message

**Comment by ritwickdey** [comment]
Are you using proxy? if not remove that.

**Comment by gfdossa** [comment]
> Are you using proxy? if not remove that. Also, check your workspace setting. Not User setting.

Turning off proxy worked (not sure how that got enabled in the first place). Thank you!
