### ISSUE TITLE
Live Server disappeared and can't get it to show

### ISSUE THREAD

**Issue by deanstreetlab** [ritwickdey/vscode-live-server#2341]
## I cannot get Live Server to function at all and not sure what's wrong

```html
[x] Other:  
```

## My Issue

I used Live Server before for a long time, but when I now use it after a few months, it doesn't show in anywhere, no status bar icon, not in right click. I tried uninstall and install a few times.  After installed, is it supposed to show up in `Microsoft VS Code/resources/app/extensions` (it isn't)? Can't open http://localhost:5500/

## Environment

```html
Browser:

- [x] Chrome (desktop) version 97

For Tooling issues:

- Live Server: 5.7.4
- Platform:  Windows 10 Home x64
- Visual Studio Code: 1.63.2
```

## Others

Below are some screenshots

- <a href="https://i.postimg.cc/1zT7RS5J/Untitled.png" target="_blank">showing installed and enabled</a>
- [html file opened but no Go Live icon](https://i.postimg.cc/50s0QsT7/1.png)
- [right click on file doesn't show Live Server](https://i.postimg.cc/KvB1JDMz/2.png)
- [settings/config](https://i.postimg.cc/252C8210/23.png)
- [resources/app/extensions](https://i.postimg.cc/P5HvxVPk/Untitled.png)

**Comment by deanstreetlab** [comment]
Hi, I tried installing an older version (5.6) and it is working. It seems to a problem with v5.7

**Comment by MattBrooks95** [comment]
This may be related to issue #2334  ??? Does the button appear when you open an HTML file?

**Comment by ritwickdey** [comment]
@MattBrooks95  Hi, nope it's not related to #2334 

@deanstreetlab Hi, something is wrong. Btw thanks for the debugging info. It supposes to show here `%USERPROFILE%\.vscode\extensions`.  Can you please install v5.7 and check if it's there or not. And also, which project you're working on? It seems it's a GitHub repo. Can able to share that so that I can try it in my local?
