### ISSUE TITLE
webSocket

### ISSUE THREAD

**Issue by raneves1** [ritwickdey/vscode-live-server#2344]
Issue Type: <b>Bug</b>

socket = new WebSocket(address);
aparece mesnagem : "webSocket  failed"

Extension version: 5.7.4
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8300 Eight-Core Processor            (8 x 3315)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.97GB (1.18GB free)|
|Process Argv|--crash-reporter-id 2dac630b-a745-4422-af0b-8c0fcc9c7e76|
|Screen Reader|no|
|VM|36%|
</details>

**Comment by ritwickdey** [comment]
what's the issue?
