### ISSUE TITLE
Code won't launch

### ISSUE THREAD

**Issue by Powermage6565** [ritwickdey/vscode-live-server#2345]
Issue Type: <b>Bug</b>

I have a code in place with, Html, Css, and javaScript and when I launch it, I only see the html code in play?

Extension version: 5.7.4
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.36GB (0.96GB free)|
|Process Argv|--crash-reporter-id 25c97356-c58d-4e46-95d0-4b72fc58c852|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflight:30433670
vsc1dsc:30433058
pythonvs932:30410667
wslgetstarted:30433507
vs360:30404995
vsrem710cf:30416617

```

</details>

**Comment by ritwickdey** [comment]
Can you please explain?

**Comment by ritwickdey** [comment]
Can you share the files or share some screenshot?

**Comment by Powermage6565** [comment]
![image](https://user-images.githubusercontent.com/99194303/153627829-1f456fc1-a48f-4e18-a7e8-c974c891e0a2.png)
![image](https://user-images.githubusercontent.com/99194303/153627886-6e85d7cd-45a8-4402-b21f-23cdce4f8059.png)
![image](https://user-images.githubusercontent.com/99194303/153627931-dae5bddc-f137-44b3-aa65-e6741ab407f1.png)
![image](https://user-images.githubusercontent.com/99194303/153627977-e28e1ad9-43dc-428d-99fd-a2a03bb22b7e.png)
![image](https://user-images.githubusercontent.com/99194303/153628024-9ebfaf74-d49d-4b10-aeb1-405b8abafc7d.png)
![image](https://user-images.githubusercontent.com/99194303/153628079-36b6b05f-06e9-4c24-96fc-99fc0a616c62.png)
![image](https://user-images.githubusercontent.com/99194303/153628131-c759fe72-b987-468c-8c06-1147365b39ab.png)

**Comment by ritwickdey** [comment]
It should work. Can you check the console? if there is any error? Or can you zip the folder and send it here?

**Comment by Powermage6565** [comment]
Sorry it's a tad
[Calculator.zip](https://github.com/ritwickdey/vscode-live-server/files/8054799/Calculator.zip)
 late, Console detects no problems with the code, so no known errors, I'll send over the folder. The attached screen shot is what shows when I launch it.  
![image](https://user-images.githubusercontent.com/99194303/153734594-8ed02c13-784f-4cd3-bf75-ce3e0014f3ab.png)

**Comment by Powermage6565** [comment]
Any updates?

**Comment by ritwickdey** [comment]
Hi, I checked. It's your code issue. Not live Server. 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/18099464/154278230-95034911-c8ad-4467-92aa-fcad0f399e47.png">

**Comment by ritwickdey** [comment]
Few more details:

Spelling mistake.
<img width="665" alt="image" src="https://user-images.githubusercontent.com/18099464/154278357-a66dc0d1-2e47-40ea-a2ae-f9fa32cec861.png">

**Comment by ritwickdey** [comment]
Not only this. there are a lot of issues. 

Happy coding.

**Comment by Powermage6565** [comment]
Ahh I see, thanks for the help, lmao I'll fix it up, I didn't see these small mistakes, so I assumed it was the extension
