### ISSUE TITLE
Live server won't open browser for html files

### ISSUE THREAD

**Issue by Raelinda** [ritwickdey/vscode-live-server#2349]
Regression 

## Current behavior

If I click 'go live' from an html file:  live server launches but the browser doesn't open. 

If I click 'go live' from a css file: live server launches and will display the index.html file linked to it, but no other html files. Which is a drag if my project has more than one page.

I'm on a MacBook/intel core. Big Sur 11.4

Already tried:
-setting firefox as my default browser for my MacBook.
-setting firefox as my vscode browser live server settings.
-setting firefox as my vscode browser in settings.JSON:    "liveServer.settings.CustomBrowser": "firefox",
-confirming that https/enable is set to 'false' in live server settings.
-pasting the following into firefox's url bar: http://127.0.0.1:5500/index.html
-clicking 'go live' from the project folder in sidebar before selecting an html file within it.
-manually right-clicking on html file in sidebar.
-reinstalling live server.
-reinstalling vs code.
-trying all of above replacing firefox with chrome, and getting same results.
Conclusion: The issue is with live server, not with the browser.

Browser: Firefox version 97

For Tooling issues:
- Live Server: 5.7.4
- Platform:  Mac
- Visual Studio Code: Version: 1.64.2 (Universal)

**Comment by ritwickdey** [comment]
Are you share `No Brower` is unchecked?

<img width="670" alt="image" src="https://user-images.githubusercontent.com/18099464/153767389-c84e7851-6ec3-4bc9-9235-c839e21ecf4f.png">

**Comment by ritwickdey** [comment]
```
{
    "liveServer.settings.AdvanceCustomBrowserCmdLine": "/Applications/Firefox.app/Contents/MacOS/firefox",
    "liveServer.settings.NoBrowser": false,
    "liveServer.settings.CustomBrowser": null
}
```

Can you try this setting?

**Comment by Raelinda** [comment]
It appears so:



I don’t know if this is related, but I can only launch live server and browser from a css file.
If select my project folder from the vscode sidebar and click ‘go live’ at the bottom of the page, live server does appear to launch (‘go live’ switches to ‘Port: 5500’). But the browser doesn’t launch. In order to launch the browser I have to select a css file, quit live server, and relaunch it.

**Comment by Raelinda** [comment]
does this code snippet get pasted into settings.json?

**Comment by ritwickdey** [comment]
yes... create `.vscode/settings.json` file inside your workspace.

**Comment by ritwickdey** [comment]
Can you make a short video on whatever you're saying CSS file ?

**Comment by Raelinda** [comment]
I’ll give that a shot.  Thanks.
:)

**Comment by Raelinda** [comment]
I don’t know how to do that.

I just tried editing the settings.json and ending up messing up all my other user settings.
I’m just going to figure out a workaround.  
Thanks for trying.

**Comment by ritwickdey** [comment]
Just create a settings file inside `.vscode` folder. (image added)
<img width="301" alt="image" src="https://user-images.githubusercontent.com/18099464/153893330-abc5ae21-8e3f-4f3e-b081-8b24c4ea37df.png">

**Comment by Raelinda** [comment]
I see what you mean now.  
Thank you!

**Comment by cwhitelam** [comment]
I am having the same issue; I try and click "open with live server" but am not redirected to chrome browser to view html file
![JSON settings](https://user-images.githubusercontent.com/79796271/153960491-911f0247-bba2-4a64-93ab-62515f8749cc.png)

**Comment by ritwickdey** [comment]
Please check this issue https://github.com/ritwickdey/vscode-live-server/issues/65 @cwhitelam
