### ISSUE TITLE
Live server only loading html and not the css 

### ISSUE THREAD

**Issue by CodeMachineDesu** [ritwickdey/vscode-live-server#2351]
# I am submitting a 
Issue wherein my live server is not loading the css file and only launchig the html. This issue is not faced when I manually open the file in the browser so I know that the path is correct. I should inform that this issue is not faced when the css file is in the same folder with the html file but only when the files are in different folders within the same directory.

Things that I have tried:
1)Everything suggested in https://github.com/ritwickdey/vscode-live-server/issues/142
2)Updating VS Code
2)Uninstalling and reinstalling live server to see if it fixes the issue

Platform: Windows 10 version 20H2
Browser : Chrome 98
Live server version : 5.7.4
Vscode version: 1.64.2 (User setup)

**Comment by CodeMachineDesu** [comment]
> ` different folders` means? Can you write the full path of HTML and CSS ?

Hey, sorry for the late reply.

For example, I have a parent folder called "website" within which are two other folders, "HTML"and "CSS", each having the respective html and css files. When I am linking my html with the css file in "CSS", live server is not loading the css and instead loading the html only. But I know for sure that the path with which I am linking the css, ../CSS/file.css, is correct as the file is loading when I open the html directly in the browser.

This problem is not faced, when both the css and html files are in the same folder,i.e, when I move the "file.css" from the "CSS" folder and put it in the "HTML" folder, which contains my html file and change the link path to just "file.css",asthey are in the same folder, live server loads my html correctly as it would be shown in browser with the css present.

**Comment by ritwickdey** [comment]
I think you're trying access out of the workspace file. Can you check if you get a 404 error in the browser console?

**Comment by ritwickdey** [comment]
and pls share a screenshot of FileExploer of vscode

**Comment by CodeMachineDesu** [comment]
> I think you're trying access out of the workspace file. Can you check if you get a 404 error in the browser console?

attaching the screenshots her
![Screenshot 2022-02-14 211123](https://user-images.githubusercontent.com/86048024/153896433-784c9a8d-8157-4c69-a9bc-9f0f0ce7c73a.png)
e

**Comment by CodeMachineDesu** [comment]
![Screenshot 2022-02-14 211213](https://user-images.githubusercontent.com/86048024/153896528-761c4de0-e4f3-4d8d-83e3-928b2e09fb24.png)

**Comment by CodeMachineDesu** [comment]
I am just a beginner so i really don't know what all of this means, that's why i gave both ss

**Comment by CodeMachineDesu** [comment]
Hey, quick update. I think i figured out what you meant by "workspace". When i opened the "webdev" folder and then opened the html file by launching liver server, the css is working! Thanks a lot @ritwickdey  for your time in helping a beginner like me to figure out the problem which was on my end

**Comment by ritwickdey** [comment]
Yes. I was right.  You have to keep your CSS file inside the vscode workspace. 
Every file should need to be inside your workspace folder (`ARGHA(WEBDEV)`).

------
PS: If you are wondering why it's working when you directly open the HTML file into the browser, then the answer is when you open the file directly to the browser, it uses the `file://` protocol.  But LiveServer uses HTTP protocol. Both are not same.  One server can't serve files from outside of the root folder (Due to security issues).
