### ISSUE TITLE
Live server fails to load html template

### ISSUE THREAD

**Issue by gairik9** [ritwickdey/vscode-live-server#2358]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by ritwickdey** [comment]
What's this?

**Comment by gairik9** [comment]
Few days back when i was trying to load my page using live server it kept
failing to do so.
It was showing 'GET ERROR'.

**Comment by ritwickdey** [comment]
Is this still happening? Can you show me a screenshot?

**Comment by gairik9** [comment]
No it's working now. But it keeps happening sometimes. I'll send a
screenshot when it happens again.
