### ISSUE TITLE
Please help its very urgent

### ISSUE THREAD

**Issue by rajdeep9565** [ritwickdey/vscode-live-server#2360]
Can somebody suggest me what i need to do. 
Please its very urgent.
![127 0 0 1 - Google Chrome 2_23_2022 8_51_29 PM](https://user-images.githubusercontent.com/87421854/155349699-0389520b-b436-4a3b-8f89-0a3c99250d47.png)

**Comment by Abhisingh755** [comment]
I think your Live Server is not working in your system
