### ISSUE TITLE
Session host name is set to Null

### ISSUE THREAD

**Issue by vrindavan** [ritwickdey/vscode-live-server#2367]
Issue Type: <b>Bug</b>

Start session
My name is just always NULL
I have signed in using Microsoft Account

Extension version: 5.7.4
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.32GB free)|
|Process Argv|--crash-reporter-id 7db457c9-5c3d-4c8f-a393-03df083706c1|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ritwickdey** [comment]
Not related to LiveServer
