### ISSUE TITLE
.liveserverrc config file for per-project settings

### ISSUE THREAD

**Issue by obihill** [ritwickdey/vscode-live-server#2370]
This is a ***feature request***. 

Thanks for this extension. It's very useful.

I know it's currently possible to update the settings via VSCode settings. However, on a per-project level, it would help if settings could be made using a config file à la ESLint, Babel, etc.

I would suggest something like `.liveserverrc`.

Thanks.

**Comment by ritwickdey** [comment]
you can create `<PROJECT>/.vscode/settings.json`
