### ISSUE TITLE
Warning: "Live Reload is not possible without body or head tag."

### ISSUE THREAD

**Issue by Mx-Wolf** [ritwickdey/vscode-live-server#2381]
## I'm submitting a bug

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  check related issues #2047, #1309, #1308
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

extension successully injects code to html page and works as intended. Yet the message "Live Reload is not possible without body or head tag" pops up every time i save some other unrelated .tsx файл.

## Expected behavior

no need to produce this warning as the extension works just fine

![image](https://user-images.githubusercontent.com/26059432/158377369-196de9ab-4426-4744-89d8-947409598161.png)

## Environment

```html
Browser:

- [x] Chrome (desktop) version 99
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: Live Server v5.7.5
- Platform:  Windows 
- Visual Studio Code: 1.65.2
```

**Comment by ritwickdey** [comment]
Make sure your html has proper format. I mean,
```
<html>
<head></head>
<body></body>
</html>
```
