### ISSUE TITLE
live server print out -->

### ISSUE THREAD

**Issue by sanghyun98** [ritwickdey/vscode-live-server#2383]
[ x] Bug report  

## Current behavior

<!DOCTYPE html>
<html>
<head><title>0000</title></head>
<body>
<h3>000000</h3>
<hr>
00000000
</body>
</html>

## Expected behavior

it print out
 -->
front of this page

## Environment

```html
Browser:

Version 99.0.4844.74 (Official Build) (64-bit)

For Tooling issues:

- Live Server: 5.7.5
- Platform:  Windows 
- Visual Studio Code: 1.65.2
```

**Comment by ritwickdey** [comment]
Not related to Live Server. 

Let me know if you belive it's a bug from Live Server
