### ISSUE TITLE
Debounce setting

### ISSUE THREAD

**Issue by Kyborg01** [ritwickdey/vscode-live-server#2386]
Hi, I have running Tailwind CSS watcher `npx tailwindcss -i src/css/style.css -o public/css/style.css --watch`

It is automatically .css built every time an html document is saved.
```
Rebuilding...
Done in 31ms.

Rebuilding...
Done in 23ms.
```

The problem is that the Tailwind CSS rebuild is slower than the Live server reload, so i don't see the changes.

Is it possible to add settings debounce (ms) settings to Live Server?

**Comment by ritwickdey** [comment]
There is already a setting. `liveServer.settings.wait`

https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md
