### ISSUE TITLE
Your VS Code extension is affected by a security issue and have been blocked

### ISSUE THREAD

**Issue by auchenberg** [ritwickdey/vscode-live-server#241]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) [x] Fix the extension, submit an update to the marketplace
2) [x] Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

/k

**Comment by ritwickdey** [comment]
Hey @auchenberg, I've already updated the extension  with the fix https://github.com/ritwickdey/vscode-live-server/releases/tag/v5.3.0

Should I make another version ?

**Comment by ritwickdey** [comment]
This has been fixed! Let me know if I missed something!
