### ISSUE TITLE
Necesito ayuda. Live Server No me funciona, no refresca mis páginas

### ISSUE THREAD

**Issue by DerickReyes** [ritwickdey/vscode-live-server#2422]
Necesito ayuda, Live Server me dejo de funcionar y no se que hacer, cuando guardo el documento no me refresca las páginas, 
**¿Quién me puede ayudar con este problema?**

Cuando guardo me sale una alerta de: Live Reload is not possible winthout body or head tag.

**Comment by ritwickdey** [comment]
Duplicate of #2419
