### ISSUE TITLE
Sophos detected a Troj/Bckdoor-AL in your code

### ISSUE THREAD

**Issue by cswright88** [ritwickdey/vscode-live-server#245]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

Sophos detected a trojan back door and deleted some code from your live server
The error was detected in vs code here:
/.vscode/extensions/ritwickdey.liveserver-5.2.0/node_modules/flatmap-stream/index.min.js

Because it was deleted I'm not sure why it was there but just wanted to let you know.
## Expected behavior

The desired behavior is not having a backdoor.  
## Environment

```html
Browser:

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: <!-- Check which version is installed --> 
version 5.2.0
- Platform:  <!-- Mac, Linux, Windows -->
mac
- Visual Studio Code: <!-- `code --version` -->
 Version 1.29.1
```

**Comment by ritwickdey** [comment]
Please upgrade the extension to v5.3.1
