### ISSUE TITLE
Look like the latest version of this extension has coinminer in it

### ISSUE THREAD

**Issue by vinchauhan** [ritwickdey/vscode-live-server#246]
My antivirus flagged the index.min.js and another js file as Coinminer... THis needs to be removed from market place. Looks like the creator got Greedy...!

~\.vscode\extensions\ritwickdey.liveserver-5.2.0\node_modules\flatmap-stream\index.min.js

## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Environment

```html
Browser:

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: <!-- Check which version is installed --> 
- Platform:  <!-- Mac, Linux, Windows -->
- Visual Studio Code: <!-- `code --version` -->
```

**Comment by ritwickdey** [comment]
Lastest Version is 5.3.1.

Anyway, I got ZERO dollar from an open source project. (yes, ZERO dollar & I gave my few months on this project). 

Please try to learn how to respect .

**Comment by vinchauhan** [comment]
> Lastest Version is 5.3.1.
> 
> Anyway, I got ZERO dollar from an open source project. (yes, ZERO dollar & I gave my few months on this project).
> 
> Please try to learn how to respect .

Sorry @ritwickdey  if you felt disrespected. I don't have to disrespect you in anyway of the great work you have done. I was just pointing out on what I found and I am sure the latest version is free of any such thing.

Sorry again if you felt my humor disrespectful in any way.
