### ISSUE TITLE
Live Preview not working in the editor

### ISSUE THREAD

**Issue by deepindersinghbti** [ritwickdey/vscode-live-server#2463]
I added the following setting to my `settings.json` file:

`"liveServer.settings.useBrowserPreview": true`

 Then I tried to start the server, but it shows the following error:

**Server is started at 5500 but failed to open in Browser Preview. Got Browser Preview Extension Installed?**  

I tried to install the [Browser Preview](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview) extension but it has been deprecated and has no install button. Please help me! I badly need browser preview in my editor.

**Comment by adrian-constantinescu** [comment]
Browser Preview has indeed been deprecated in favour of [Live Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server).
Live Preview looks like it is not currently supported by Live Server, however, for HTML files (at least) Live Preview can display them itself.

**Comment by deepindersinghbti** [comment]
@adrian-constantinescu  
It has almost been a year since I created this issue. After creating this issue, I found the Live Preview extension and am currently using that extension, and I have never faced any problem. I forgot to close this issue. Thank you for your attempt to help me with this issue.
