### ISSUE TITLE
"Open a folder or workspace... (File -> Open Folder)" when "> Live Server: Open with Live Server" without a folder being open

### ISSUE THREAD

**Issue by riahc3** [ritwickdey/vscode-live-server#248]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[X ] Feature request
[ X] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

With a HTML page open, I hit Ctrl+Shift+P and type Live Server: Open with Live Server but I get a error saying Open a folder or workspace... (File -> Open Folder)

## Expected behavior

Should open a standalone HTML file.

## Environment

```html
Browser: 

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [X ] IE version 11
- [ ] Edge version XX

For Tooling issues:

- Live Server: Latest 
- Platform: Windows
- Visual Studio Code: 1.29.1
```

**Comment by FDelrosario** [comment]
Hi I was just wondering if you were able to solve this issue? I am experiences the same error.

**Comment by maks1981** [comment]
Guys hello, i have the same problem but i could not solve it.
When i press Open with live server below message appears "Open a folder or workspace... (File -> Open Folder)", I opened any html file there many times but nothing about live server works ,guys how can i solve this?please any help
Kind Regards

**Comment by irfan339** [comment]
hi 

Want to known how to open more than one html file using live server in visual studio code 
And when i try open more than one file with live server it is opening that files on same port, but when try to close live server for one file it is closing for all files opened on that port
So please tell me how to use live server for multiple files in visual studio code

**Comment by Pihu01** [comment]
I'm facing the same issue can anybody help me please!
"Open a folder or workspace... (File -> Open Folder)"

**Comment by Pihu01** [comment]
Wow! I got the solution, 
whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
thank you

**Comment by 1000martians** [comment]
Didn't work for me :(

**Comment by CAH1983** [comment]
it worked, thank you!

**Comment by prabhu8511** [comment]
@Pihu01 it worked

**Comment by rohitdhas** [comment]
it really works...............

**Comment by Pihu01** [comment]
Will you please attach screenshot or write your issue which you are facing?
It will help me to understand related problem

**Comment by TheManWithFlaws** [comment]
Thanks, but It worked with the help of your previous answwr.

**Comment by Prottoy2938** [comment]
> 
> 
> Didn't work for me :(

Try doing "ctrl O" and then open the file. This will solve it. You might have seen "Not Opened In Folder" notification

**Comment by Geek2452** [comment]
It worked!

**Comment by JohanJimenex** [comment]
> Didn't work for me :(
remenber the extention on chrome ON

**Comment by eyobai** [comment]
go to file>open folder> then open the folder where .html file is saved dont open the file just open the folder

**Comment by Yashr29-max** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

sry but i cant understand please can you helped me to solved this prob.......

**Comment by Yashr29-max** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

thankyou pihu its working ..........
thanks alot....

**Comment by Tanmoy-Banerjee** [comment]
> ## I'm submitting a...
> ```
> [ ] Regression (a behavior that used to work and stopped working in a new release)
> [X ] Bug report  
> [X ] Feature request
> [ X] Documentation issue or request
> [ ] Other: 
> ```
> 
> ## Current behavior
> With a HTML page open, I hit Ctrl+Shift+P and type Live Server: Open with Live Server but I get a error saying Open a folder or workspace... (File -> Open Folder)
> 
> ## Expected behavior
> Should open a standalone HTML file.
> 
> ## Environment
> ```
> Browser: 
> 
> - [ ] Chrome (desktop) version XX
> - [ ] Firefox version XX
> - [ ] Safari (desktop) version XX
> - [X ] IE version 11
> - [ ] Edge version XX
> 
> For Tooling issues:
> 
> - Live Server: Latest 
> - Platform: Windows
> - Visual Studio Code: 1.29.1
> ```
> 
> ## Others
Open your folder in Vscode explorer

**Comment by 1999allen** [comment]
the same question occured,can anybody help me figure it out ? 3q

**Comment by skevetine** [comment]
![15849871230747339885818080902238](https://user-images.githubusercontent.com/62213033/77348749-30235300-6d64-11ea-9345-9428f322dd45.jpg)


Vscode>File>Open file>"choose the folder where you saved .html file.

then "alt+alt+o to start live" server
i can make a short video if you cant understand me.

**Comment by skevetine** [comment]
Vscode>File>Open folder >"choose the folder where you saved .html file.

then click on "alt+alt+o" to start live server.
i can make a short video if you cant understand me.

**Comment by 1999allen** [comment]
yep,i understand,i had try to find out folder,but it doesn't work finally.But I am so appreciated if you could send me the video.

**Comment by lakhan-solanki** [comment]
thanks it worked!!

**Comment by Jacer7** [comment]
> I'm facing the same issue can anybody help me please!
> "Open a folder or workspace... (File -> Open Folder)"

where are the solutions??

**Comment by arvinmi** [comment]
Hi, I am facing the same issue. I tried opening in the folder location, and the folder in VS code explorer, it didn't work. Can anyone help me out? Thanks in advance.

**Comment by 1999allen** [comment]
What a pity btw,i don't know how to solve out the problem either.i am so soory for that,i am considering to download another editor such as Hbuilder replacing of vscode and let it go as for liverserver




Best Regards,
Allen


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"arvinmi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 下午2:20
收件人:&nbsp;"ritwickdey/vscode-live-server"<vscode-live-server@noreply.github.com&gt;;
抄送:&nbsp;"Allen"<53370387@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ritwickdey/vscode-live-server] "Open a folder or workspace... (File -&gt; Open Folder)" when "&gt; Live Server: Open with Live Server" without a folder being open (#248)





 
Hi, I am facing the same issue. I tried opening in the folder location, and the folder in VS code explorer, it didn't work. Can anyone help me out? Thanks in advance.

**Comment by HackerPractice** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

I cant believe that worked :D

**Comment by 1999allen** [comment]
i had try,but the error existed all the time.Do you have other solutions to aviod it?


Thank you so much~


Best Regards,
Allen




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "HackerPractice"<notifications@github.com&gt;; 
发送时间: 2020年5月31日(星期天) 晚上8:57
收件人: "ritwickdey/vscode-live-server"<vscode-live-server@noreply.github.com&gt;; 
抄送: "Allen"<53370387@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ritwickdey/vscode-live-server] &quot;Open a folder or workspace... (File -&gt; Open Folder)&quot; when &quot;&gt; Live Server: Open with Live Server&quot; without a folder being open (#248)





  
Wow! I got the solution,
 whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
 thank you
  
I cant believe that worked :D

**Comment by aman-git13** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

thank you maam
it really works

**Comment by shahnaeem** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

thank you, it worked for me

**Comment by 1999allen** [comment]
thanks for your reminding,i am trying to do so but it doesn't work at present,could you show me the pictures what you operate on?


thank you so much for your support.


Best Regards,
Allen




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shahnaeem"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 凌晨5:28
收件人: "ritwickdey/vscode-live-server"<vscode-live-server@noreply.github.com&gt;; 
抄送: "Allen"<53370387@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ritwickdey/vscode-live-server] &quot;Open a folder or workspace... (File -&gt; Open Folder)&quot; when &quot;&gt; Live Server: Open with Live Server&quot; without a folder being open (#248)





  
Wow! I got the solution,
 whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
 thank you
  
thank you, it worked for me

**Comment by Sahinujjaman-Rahaman** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

Its not working

**Comment by Sahinujjaman-Rahaman** [comment]
Its working :-) 
At first you should **open folder** not only open file...

**Comment by Galadriel4** [comment]
Try to open the FOLDER that contains the document you are trying to see with live server. I did that and the problem was solved.

PD: Even if you have the document opened, you might not have the folder opened, and that could be caussing the problem. At least, that was what happend in my case.

Greetings!

**Comment by Luuciano96** [comment]
Server is started at 5500 but failed to open in Browser Preview. Thats the error that shows when I try this method

> Try to open the FOLDER that contains the document you are trying to see with live server. I did that and the problem was solved.
> 
> PD: Even if you have the document opened, you might not have the folder opened, and that could be caussing the problem. At least, that was what happend in my case.
> 
> Greetings!

A new error just popped out when I tried this method. "Server is started at 5500 but failed to open in Browser Preview."

Could you help me?

**Comment by KuluUthappa** [comment]
Hi,

When you try opening the live server and it throws an error saying "Open a folder or workspace... (File -> Open Folder)" then,
On vscode to the top left corner --> Go to file-- > open folder and select the folder in which the code is saved. 
This should resolve the issue.

**Comment by FelixJose28** [comment]
> go to file>open folder> then open the folder where .html file is saved dont open the file just open the folder
Yes, that is the solution

**Comment by Gopipatwa** [comment]
Thankyou it's working

**Comment by loglost** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

it worked! Thank you!

**Comment by nagaajay4** [comment]
> > Wow! I got the solution,
> > whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> > thank you
> 
> Its not working

>It's working thanks learner

**Comment by loglost** [comment]
well we should thanks to 'Pihu01'  up there

**Comment by NiranjanShirke** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

It worked for me ...thanks for posting

**Comment by nibicon** [comment]
right click on  UNTITLED (WORKSPACE)  and select ADD FOLDER TO WORKSPACE
select the folder you wan to add and continue working. 
![Annotation 2020-11-21 095644](https://user-images.githubusercontent.com/72159607/99872147-fd29ab80-2bdf-11eb-98bf-e7e1c57cf528.jpg)
![Annotation 2020-11-21 095634](https://user-images.githubusercontent.com/72159607/99872149-00249c00-2be0-11eb-8108-542ef45fdc21.jpg)

**Comment by nibicon** [comment]
you can also click on file AND select ADD FOLDER TO WORKSPACE. the select the complete folder of your code. 
![Uploading {06AE5C49-1343-474D-AA51-6521DCFA1472}.png.jpg…]()

**Comment by Mohit-Rautela** [comment]
Guyz.... its not working because you might have selected "open file" option to put your file in VS Code, instead try to select "open folder" option in VS Code and it will surely gonna work. 👍 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

**Comment by pechavarria62** [comment]
For Apple users, 
hi guys what worked for me it was, when i went to open the folder the system just took me right to the folder, i clicked out of there like were the folder is, then i went to the folder then the file, if the bottom line turns blue in vscode that means it worked.  let me know please.

**Comment by kscripter** [comment]
> you can also click on FILE and select ADD FOLDER TO WORKSPACE. then select the complete folder of your code.

Exactly make sure all the folders you have your files in are saved in a "WORKSPACE FOLDER". Put all your files in the Workspace Folder, then open the files from your workspace folder by using VSCODE to open it.

**Comment by Lokesh01** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

thanx that really helped

**Comment by unisrasheed** [comment]
I got a solution
open vs code
then click on files then click  on  open folder,  select  the folder where  your html file is.
then click on right click open with  server.
it will work

**Comment by lucasezequiel05** [comment]
> Wow! I got the solution,
> whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click.
> thank you

Thank you! I did it!

**Comment by premkr2512** [comment]
go to File , Then to Open Folder and then go to Select . And now you can select your file .

**Comment by dens90** [comment]
thank you Pihu01 
 it works

**Comment by TamarDvorkin** [comment]
> eyobai

Thank you- it works!

**Comment by DevLGustavo** [comment]
> vá para arquivo>abrir pasta> depois abra a pasta onde o arquivo .html está salvo não abra o arquivo apenas abra a pasta

Conseguir resolver com sua ajuda. grato!!!!!!!!!!!

**Comment by SeaSideSon** [comment]
solution:
on VSC go to upper left: file>open folder
select the folder which contains the .html files 
after that, the folder opens in VSC and you will be able to run the live server on each html file.

**Comment by AlexSgherri** [comment]
Just deselect Open Editors to hide it and it will work

**Comment by JslinSir** [comment]
> Wow! I got the solution, whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click. thank you
6666

**Comment by JslinSir** [comment]
> Wow! I got the solution, whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click. thank you

6666

**Comment by SaarthakMaini** [comment]
Thank you @Pihu01

**Comment by EEvan11** [comment]
"Open a folder or workspace... (File -> Open Folder)" when "> Live Server: Open with Live Server" without a folder being open" This issue happens to me too when I just create file in VS and just run it, so I just create some folder and put the file their and it works.

**Comment by LukaGK** [comment]
It worked, thank you!

**Comment by Mudassir551** [comment]
> Wow! I got the solution, whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click. thank you

Thanks!

**Comment by jalalbmnf** [comment]
Hello everyone , i had a same issue. But i open html file in browser and open html file in vscode and it works , opening another folder or workspace is not a good way cause , machine spends power for unnecessary things when you unnecessary folder or workspace

**Comment by Hollin-A** [comment]
> Wow! I got the solution, whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click. thank you

Thank you. It worked

**Comment by dhritiman122** [comment]
> Wow! I got the solution, whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click. thank you

Thank you so much for your help

**Comment by NeelContractor** [comment]
Probably you guys were use git and changed your working dir in it. first open your folder in which the file is save then try to do . this might help you guys.

**Comment by SIRBOLU** [comment]
> Wow! I got the solution, whenever you try to open file without opening folder in visual studio code, then the issue occurs, to avoid this first open the folder(where code file already exist) in visual studio code, and then you can open live server by right click. thank you

Thanks so much

**Comment by MauricioQuiroga** [comment]
> Guys hello, i have the same problem but i could not solve it. When i press Open with live server below message appears "Open a folder or workspace... (File -> Open Folder)", I opened any html file there many times but nothing about live server works ,guys how can i solve this?please any help Kind Regards



> Guys hello, i have the same problem but i could not solve it. When i press Open with live server below message appears "Open a folder or workspace... (File -> Open Folder)", I opened any html file there many times but nothing about live server works ,guys how can i solve this?please any help Kind Regards

Solved it, turns out it's you are using just one file of a folder instead of the folder in its entirety, I don't know if I;m expressing myself correctly pero if this didn't help let me know

**Comment by euniceno** [comment]
> 

OMG really thanks you save my computer life. I'm almost freak out and thanks~

**Comment by nimahamidi12** [comment]
Solution video

https://elnima.ir/2023/07/23/open-live-server-in-visual-studio-code/

**Comment by AliRezaH2001** [comment]
> ,

thanks alot

**Comment by IThuanghao** [comment]
> 进入文件>打开文件夹>然后打开保存文件的文件夹.html 不要打开文件，只打开文件夹

nice to meet you!
