### ISSUE TITLE
Can you set up live reload for websites that are already hosted on a remote server?

### ISSUE THREAD

**Issue by architchandra** [ritwickdey/vscode-live-server#25]
Let's say I am using a server for development that is hosted with Bluehost etc. The domain pointing to it is 'abc.xyz'. Can I set up the live server such that my browser reloads every time I save the file in VSCode (I am using ftp-simple to edit files directly on the server)?

Thanks in advance.

**Comment by ritwickdey** [comment]
Hi, First, thanks for the feedback.  It is not possible. 

Live Server inject few lines of JS code when it serves any HTML page for live reload feature.

Best Way : 
Make a local Package -> start git tracking. -> modify code -> commit -> Push to FTP Server.

**Comment by architchandra** [comment]
Thanks Ritwick. Yes, I guess that is what I'll have to do.
