### ISSUE TITLE
Extension host terminated unexpectedly in vs code insiders 1.31.0

### ISSUE THREAD

**Issue by minoseah629** [ritwickdey/vscode-live-server#250]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

After launching vscode-insider and a moment later, I get Extension host terminated unexpectedly.

I disabled all extensions with no issue. 
I reenabled all extensions and located developer tool and saw below error:

Developer Tool shows this error: 

dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/xxx/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

## Expected behavior

VS Code operates normally

## Environment

```html
Browser:

no applicable browser

For Tooling issues:

- Live Server: 5.3.1
- Platform:  10.14.3 Beta (18D21c)
- Visual Studio Code: Version 1.31.0-insider (1.31.0-insider)
```

## Others

https://github.com/Microsoft/vscode/issues/64981

**Comment by hassanbinsafdar** [comment]
Same Here :(

**Comment by ritwickdey** [comment]
Hey, sorry for late. Seems like it's a serious issue. Can anyone please share console of vscode (Help => Toggle Develoer Tools) ?

**Comment by ritwickdey** [comment]
Sorry, I got the log from @minoseah629

**Comment by ritwickdey** [comment]
The issue is comes from `fsevents`. Seems like all of you're using Mac. 

There are some breaking changes as `vscode-insider` is now using electron.js v3.x and Node.js 10.x

The Issue is related to https://github.com/electron/electron/issues/14841 & https://github.com/strongloop/fsevents/issues/229

I've upgraded one package. Can anyone please clone the project & install the package from here 

Please let me know if you need any help to manual install and status of extension after install ?

**Comment by kouhei** [comment]
I don't know how to install extensions from here.
Please let me know it.

**Comment by ritwickdey** [comment]
Hi @kouhei thanks for your interest. Sorry for a late reply (due to my exams).

Can you join with me in Hangout Text Chat or Skype Text Chat (or anyone ? )

Hangout: ritwickdey97@gmail.com
Skype: ritwickdey


[It'll be annoying if I do chat here, because everyone will receive emails for every comment.]

**Comment by abdohossam5** [comment]
any chance of fixing this soon. it's making the insiders edition unusable.

**Comment by jdpurnell** [comment]
manually updating to v5.4.0-alpha fixed this for me...

**Comment by bengry** [comment]
@ritwickdey I tried to manually install the `vsix` in the releases, as well as manually compiling from the source code of the alpha2 tag, in both I get the follow error when trying to use the extension, the extension host doesn't seem to be crashing though:
![image](https://user-images.githubusercontent.com/260431/50353145-fc99bd80-054f-11e9-8df4-6e4a16727416.png)

**Comment by kristofferR** [comment]
It's still not fixed, I tried installing LiveServer-5.4.0-alpha4-osx.vsix and Extension Host is still crashing:

dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/kristoffer/.vscode-insiders/extensions/ritwickdey.liveserver-5.4.0-alpha4/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/kristoffer/.vscode-insiders/extensions/ritwickdey.liveserver-5.4.0-alpha4/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

**Comment by Ceus** [comment]
Still failing on 1.31.0-insider (1.31.0-insider).

![extension host](https://user-images.githubusercontent.com/3145889/50838861-ad5fd500-1324-11e9-9b05-cdff2be937cb.png)

`Extension Host
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3273 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/jfelps/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/jfelps/.vscode-insiders/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace`

**Comment by crystalfp** [comment]
Idem in 1.30.2 But I used it (together with Live SCSS compiler) before this upgrade.
Hope it helps.

**Comment by morlandi-jss** [comment]
Same problem here, 1.30.2 with very few plugins (Typescript hero, TypeScript ast outline, material icon theme and psioniq file header). I attach the log 
[-1548415132702.log](https://github.com/ritwickdey/vscode-live-server/files/2795812/-1548415132702.log)

**Comment by markonyango** [comment]
`Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Datum: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Betriebssystem: Windows_NT x64 10.0.17134`

Same here. I fire up VS Code and the extension host crashes immediately.

**Comment by adesugbaa** [comment]
Please try 5.4.0.alpha6 pre-release build.

**Comment by kristofferR** [comment]
> Please try 5.4.0 release build.

Still doesn't work. 
![capto_capture 2019-02-04_03-59-22_am](https://user-images.githubusercontent.com/481270/52188145-5836b680-2831-11e9-81a0-6cf2593798ac.png)

**Comment by adesugbaa** [comment]
> > Please try 5.4.0 release build.
> 
> Still doesn't work.
> ![capto_capture 2019-02-04_03-59-22_am](https://user-images.githubusercontent.com/481270/52188145-5836b680-2831-11e9-81a0-6cf2593798ac.png)

Please provide information on OS, VS Code Build etc

**Comment by rebeccapeltz** [comment]
I'm seeing the extension host crash too.

**Comment by mrjjwright** [comment]
Crashing for me as well with VSCode 1.31 release

**Comment by mrjjwright** [comment]
Nevermind, working when I manually installled 1.5.4 from VSIX file.

**Comment by Hckdbrd** [comment]
Live server uninstalling let me get rid of that strange issue. Try to uninstall it! Good Luck!

**Comment by llauderesv** [comment]
Hi I'm also experiencing this issue.

Hope will fix it as soon as possible.

VS Code Version 1.31.0

![screen shot 2019-02-07 at 9 15 41 am](https://user-images.githubusercontent.com/20419473/52384572-043e0300-2ab9-11e9-8949-6a94fe9d47df.jpg)

**Comment by minoseah629** [comment]
It worked for v 1.32.0-insider

**Comment by adesugbaa** [comment]
Please download 5.4.0 from this repo (under Releases), and try installing that manually.

```
View -> Command Pallete... -> Extensions Install from VSIX...
```

Select the extension you downloaded, and restart VS Code when it completes.

Please provide feedback - 5.4.0 will be published once we confirm it is working for all.

**Comment by kristofferR** [comment]
The latest 5.4.0 version now works fine, on macOS and VS Code 1.32.0 👍

**Comment by ritwickdey** [comment]
Please install v5.4.0 from marketplace. Let us know if it doesn't work. (and also don't forget to update vscode-insider 😄)

**Comment by leoggonzalez** [comment]
I tried installing the v5.4.0 from the marketplace but the issue persisted. I had to rollback to vscode 1.30 :(

**Comment by ritwickdey** [comment]
Hi @leoggonzalez, Have you tried the lastest version? It should work. 

Anyway, is this same issue? you can create a new issue request in GitHub if the issue is different.

**Comment by crystalfp** [comment]
I use the latest version on the latest Code version. If I deinstall live scss compile and live server the extension server does not crash anymore. So, what do you need to understand the problem? Thanks! Mario


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Ritwick Dey <notifications@github.com> Data: 12/02/19  14:25  (GMT+01:00) A: ritwickdey/vscode-live-server <vscode-live-server@noreply.github.com> Cc: Mario Valle <mvalle@cscs.ch>, Comment <comment@noreply.github.com> Oggetto: Re: [ritwickdey/vscode-live-server] Extension host terminated unexpectedly in vs code insiders 1.31.0 (#250) 
Hi @leoggonzalez, Have you tried the lastest version? It should work.
Anyway, is this same issue? you can create a new issue request in GitHub if the issue is different.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ritwickdey/vscode-live-server","title":"ritwickdey/vscode-live-server","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ritwickdey/vscode-live-server"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ritwickdey in #250: Hi @leoggonzalez, Have you tried the lastest version? It should work. \r\n\r\nAnyway, is this same issue? you can create a new issue request in GitHub if the issue is different."}],"action":{"name":"View Issue","url":"https://github.com/ritwickdey/vscode-live-server/issues/250#issuecomment-462757815"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ritwickdey/vscode-live-server/issues/250#issuecomment-462757815",
"url": "https://github.com/ritwickdey/vscode-live-server/issues/250#issuecomment-462757815",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by philipaarseth** [comment]
This Is still a problem, using the insiders version is by no means a fix. It doesn't even use the same settings.

**Comment by Ceus** [comment]
This is resolved for me.

Version 1.32.0-insider (1.32.0-insider)
Live Server v5.5.1

**Comment by crystalfp** [comment]
OK, waiting for new Code and Live server versions. In the mean time I simply run sass --wait outside Code.

**Comment by hevisko** [comment]
Same issue on Version 1.32.3 (1.32.3)

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/hvisage/.vscode/extensions/living42.vscode-simple-sync-0.0.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/hvisage/.vscode/extensions/living42.vscode-simple-sync-0.0.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
```

**Comment by mpx2m** [comment]
1.33.0
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/lingyinxie/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/lingyinxie/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

**Comment by GuoZhiQiang** [comment]
I disable all the Extensions , then enable them one by one and find that `Settings Sync` extension caused the error :`Extension host terminated unexpectedly.`. Finally I disable `Settings Sync` solve the problem. But I really want to use `Settings Sync`. Feeling bad.

My VSCode version : 1.33.0.

**Comment by aziez** [comment]
> I disable all the Extensions , then enable them one by one and find that `Settings Sync` extension caused the error :`Extension host terminated unexpectedly.`. Finally I disable `Settings Sync` solve the problem. But I really want to use `Settings Sync`. Feeling bad.
> 
> My VSCode version : 1.33.0.

all fixs with disable setting sync

**Comment by ricardorojass** [comment]
> I disable all the Extensions , then enable them one by one and find that `Settings Sync` extension caused the error :`Extension host terminated unexpectedly.`. Finally I disable `Settings Sync` solve the problem. But I really want to use `Settings Sync`. Feeling bad.
> 
> My VSCode version : 1.33.0.

Thanks, works for me

**Comment by TepyThai** [comment]
If updating Live-Server doesn't work for you, try "disable" "Setting sync" extension.

**Comment by paoloalmeida** [comment]
WOW! Thank you so much! It works for me :)

**Comment by daisyleenr** [comment]
> I disable all the Extensions , then enable them one by one and find that `Settings Sync` extension caused the error :`Extension host terminated unexpectedly.`. Finally I disable `Settings Sync` solve the problem. But I really want to use `Settings Sync`. Feeling bad.
> 
> My VSCode version : 1.33.0.

Thanks, works for me :)

**Comment by TunvirRahman** [comment]
deleting all extension of VSCode help me to solve the issue.
`cd ~/.vscode/extensions` and then delete all and now reinstall your required extensions again

**Comment by danlafreniere** [comment]
Disabling settings sync also worked for me. Thank you!

**Comment by datajunkee** [comment]
I tried disabling, didn't work. I then tried deleting all extensions and restarted...naturally it worked. Then installing just Live Server causes the Extension host failure with the following message:

![Screen Shot 2019-04-17 at 5 01 30 AM](https://user-images.githubusercontent.com/1210328/56275002-e3ec7f00-60cd-11e9-89b4-5a753ef4be7c.png)

**Comment by TunvirRahman** [comment]
Caused by `Settings Sync` extension. I was using `React Native Full Pack` extension and this extension is using `Settings Sync` extension as dependency. So I have switched to another Extension named` React Native Tools` and now Solved the issue.

**Comment by jonathaniqueda** [comment]
When I disable `Live Server` extension, resolved for me.

**Comment by BashirAljounaidy** [comment]
> deleting all extension of VSCode help me to solve the issue.
> `cd ~/.vscode/extensions` and then delete all and now reinstall your required extensions again


Thank youuu . Done

**Comment by MaksymilianWojcik** [comment]
The simplest solution is to disable all extensions and enable them all again :) Also did the same with Live Server - reenabling solved the issue, I can still use it

**Comment by ritwickdey** [comment]
New version is published. Please try to install from store. It should work. If not, please let me know

**Comment by KaceAlexiCasey** [comment]
Guys, the problem is in your code if that problem appears. For example I used a path of a deleted folder somwhere in my .scss files and this issue started the crash of the Sass Live Compiler. 

Just check your code for any strange errors.

**Comment by CuongStf** [comment]
just only disable or uninstall extension live-sass, it's work for me
Hope help.

**Comment by devarajuavula** [comment]
I tried all the above step and procedures but there is no solution.  
finally, I Cross checked all my installed extensions plugins and I found same and similar extensions twice or trice the problem will be occurs. So, I uninstall the related or similar extension plugins the problem is resolved. Thank you
