### ISSUE TITLE
Font Size different in live server as compared to opening html file from Windows Explorer.

### ISSUE THREAD

**Issue by hasaansworld** [ritwickdey/vscode-live-server#251]
## I'm submitting a...

Bug report 

## Current behavior
I have an html file linked with css stylesheet that uses em unit for font size. The font-size I used looks fine in liveserver but when I open the html file from Windows Explorer the font-size is noticeably smaller.

## Expected behavior
liveserver and html file should both look the same.

## Environment
Browser:

`Chrome (desktop)`

For Tooling issues:

- Live Server: `5.3.1`
- Platform:  `Windows`
- Visual Studio Code: `1.3.0`

**Comment by rjoydip** [comment]
The live server doesn't use any CSS.

**Comment by vipul0425** [comment]
@hasaansworld I am facing the same issue did you got any solution to it?

**Comment by MkdirRaiden** [comment]
I 'm facing the same problem as well cuz...

**Comment by esi8bitman** [comment]
Me too ... what should I do? ... change the brower? or change the server?

**Comment by codebypratham** [comment]
there is size reduced problem
![Screenshot (1)](https://github.com/ritwickdey/vscode-live-server/assets/167754418/b63672d2-3f49-457a-b2ed-78ff79ccb2ce)
