### ISSUE TITLE
Linear Gradient not functioning properly on live server.

### ISSUE THREAD

**Issue by BettyJohnson02** [ritwickdey/vscode-live-server#2561]
We have written the needed data into your clipboard
Type: <b>Bug</b>

I'm relatively new to coding and I'm trying to create something fun with a linear gradient but as I put in the code with CSS it turns into multiple repeats.

body{
    background: linear-gradient(to bottom, #33ccff 0%, #006600 100%);
}

Extension version: 5.7.5
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.60GB (3.15GB free)|
|Process Argv|--crash-reporter-id e9e61b3b-d729-43a5-bc7b-4d1be22339ff|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

rd because it was too large to send. Please paste.

**Comment by BettyJohnson02** [comment]
Here's the photo of it

HOW IT LOOKS:
<img width="788" alt="Screenshot 2022-08-27 201217" src="https://user-images.githubusercontent.com/82971307/187052205-04c6dee3-6cb1-4768-bac2-ed68129b6f05.png">
:

VS HOW IT IS SUPPOSED TO LOOK
<img width="409" alt="Screenshot 2022-08-27 201328" src="https://user-images.githubusercontent.com/82971307/187052232-93b32dec-891f-4c03-ac38-49cb2caa7e50.png">
:

**Comment by ritwickdey** [comment]
```
body {
        min-height: 100vh;
        background: linear-gradient(to bottom, #33ccff 0%, #006600 100%);
      }
```
