### ISSUE TITLE
Something is went wrong! Please check into Developer Console or report on GitHub.

### ISSUE THREAD

**Issue by yemresusam** [ritwickdey/vscode-live-server#2571]
Type: <b>Bug</b>

Something is went wrong! Please check into Developer Console or report on GitHub. 
i am encountering this error pls helpme

Extension version: 5.7.9
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.33GB free)|
|Process Argv|--crash-reporter-id 5d07d44d-14e5-4798-ae01-4229d6f614fa --crash-reporter-id 5d07d44d-14e5-4798-ae01-4229d6f614fa|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by ritwickdey** [comment]
Can you please share logs from Developer Console?

**Comment by yemresusam** [comment]
I solved the problem and uploaded it to my own youtube channel, https://www.youtube.com/watch?v=4vDoMtIGhtk&ab_channel=YAZILIMDOSTUNUZ but this is my problem link https://resimyukle.io/r/iFqJ56DQLS
thanks for help

**Comment by ritwickdey** [comment]
Hey, I just want to know why the latest version is not working for you.  Please install the lastest version and share logs from Developer Console (Help -> toogle developer tool -> console)

**Comment by yemresusam** [comment]
ı shared the issue  https://resimyukle.io/r/iFqJ56DQLS

**Comment by ritwickdey** [comment]
Sorry, it's not the code from LiveServer, maybe some internal code from vscode. You'll find logs from Developer Console option.  ` (Help -> toogle developer tool -> console)`

**Comment by yemresusam** [comment]
now i installed v5.7.9 and it worked i think you have solved the problem =)

**Comment by yemresusam** [comment]
https://resimyukle.io/r/xnUoMhyB6n

**Comment by ritwickdey** [comment]
hmm. Pls share same logs if you face the same issue again.

**Comment by yemresusam** [comment]
okey thanks
