### ISSUE TITLE
Question: Live server sudo mode for port 80

### ISSUE THREAD

**Issue by abc-1211** [ritwickdey/vscode-live-server#2589]
## I'm submitting a...
Question

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ X] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior
I tried to set to port 80 in settings.json, however, it will auto changed to port 81. Port 80 is empty and available, i would say the culprit live server doesn't have the permission (sudo) to use Port 80. How can I enable Sudo mode and use port80?
I am trying to connect to other software and they are sending HTTP request only.

## Environment
Computer: MacBook Pro (M1, 2020)
OS: IOS 11.1
Live Server Version: v5.7.9 (version number after reinstalled) (no info for version number before reinstalled)
VSCode Version: 1.56.2 (Universal)
```html
Browser:

- [ x] Chrome (desktop) version 89.0.4389.114
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by ritwickdey** [comment]
Make sure nothing is running on port 80. 
https://superuser.com/questions/597398/no-idea-what-is-listening-on-port-80-in-os-x

**Comment by abc-1211** [comment]
> Make sure nothing is running on port 80. 
> 
> https://superuser.com/questions/597398/no-idea-what-is-listening-on-port-80-in-os-x

As stated in the question, PORT 80 IS CONFIRMED EMPTY AND NO SERVICE IS OCCUPIED.

**Comment by TriMoon** [comment]
> @ritwickdey  Make sure nothing is running on port 80.

As the OP already stated above, it's an available port...

The problem is that Linux demands root priviledges to open listen ports below 1024...
So maybe a dialog that requests proper authorization from the user to perform that action as root is possible?
- `pkexec` maybe?
- Or usage of `sudo` within a terminal, or automated with an entry in the sudoers file that permits it without password which is dangerous...
