### ISSUE TITLE
Live Reload is not possible without body or head tag

### ISSUE THREAD

**Issue by tehsy97** [ritwickdey/vscode-live-server#262]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

The web browser shows something when I just run the extension and connect to a port No. but when I make changes to my html files the error message ("Live Reload is not possible without body or head tag") pops up and the web browser shows nothing (blank). I have to close the server and reconnect it every time for web browser to show the new web contents. When I added an extra  ```<html> ``` or ``` </html> ``` the Live Server works fine for some reason.

I installed Live Server 8 months ago and it worked fine until recently when I tried to use it again after 4 months of inactivity and updated to the new version of it. I tried to open my old html documents that used to work fine with Live Server and don't work fine with it now. I thought I might have changed my codes and copied some codes from https://www.w3schools.com/html/default.asp but the Live Server behaved the same way.

The codes I copied from the link and with issue
 ```html
 <!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>

</body>
</html> 
```

The codes that work fine with extra ```<html> ``` or ``` </html> ```
 ```html
<!DOCTYPE html>
<html>
<html>     <!-- extra -->
<head>
<title>Page Title</title>
</head>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>

</body>
</html> 
```
 ```html
<!DOCTYPE html>
<html>
</html>              <!-- extra -->
<head>
<title>Page Title</title>
</head>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>

</body>
</html> 
```
## Expected behavior
It should reload and work without the extra <html> or </html>, like last time, without problem.

## Environment

```html
Browser:

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ x ] Edge version 42.17134.1.0

For Tooling issues:

- Live Server: 5.3.0 
- Platform:  Windows 
- Visual Studio Code: 1.30.2 
```

**Comment by ritwickdey** [comment]
Just click to turn off when it prompts

**Comment by pgluz** [comment]
> Just click to turn off when it prompts

This is not the solution. The problem is not the annoying notification, but the fact that auto-reload doesn't work.
In my case is even worse - instead of the mentioned notification, Live Server shows a blank page, doesn't matter what I type as a code.

**Comment by HarryAdney** [comment]
Yep, got this problem now. Not bothered by the notice, it's the reloading that's the problem. Is there a fix yet?

**Comment by meCoding** [comment]
I got the same problem. In my case, the problem was a wrong file encoding in index.html. When I changed the encoding to ASCII or UTF-8, the Live Reload started working again.

**Comment by barnettx** [comment]
I've been having this issue as well for my index.html

My solution was to delete the original file, then create a new file and copy over the code. 

I created a separate test.html and live-reload was working again. Thought it was an encoding error so I copied my working test.html code into index.html. Still no luck. Deleted and then created a new index.html -- things are back to normal now.

**Comment by alexpti4ka** [comment]
I used to have it when I had a link to an .svg file that was not saved. Saving all files in the project could probably work.

**Comment by proton2021** [comment]
After reading other posts decided to make a small change in th index.html page from : <meta charset="UTF-8"> 
to <meta charset="utf-8"> and it started to work again.

**Comment by Ghostpiedpiper** [comment]
Actually,you just need add the code like this:<head><meta charset="UTF-8"></head>.I think this is a bug for compiler or some other thing else.Anyway ,i soloved it

**Comment by Ghostpiedpiper** [comment]
Actually,you just need add the code like this:
<head>
        <meta charset="UTF-8">
</head>
I think this is a bug for compiler or some other thing else.Anyway ,i solved it

**Comment by Ghostpiedpiper** [comment]
Actually,you just need add the code like this:
<meta charset="UTF-8">  in your head part
I think this is a bug for compiler or some other thing else.Anyway ,i solved it

**Comment by davidd-prog** [comment]
The problem can also arise when working on a project saved on an external hard drive, this is the case for me. The extension may fail to detect changes from the external hard drive.
