### ISSUE TITLE
Will Not Load Files on Launch

### ISSUE THREAD

**Issue by GTME1** [ritwickdey/vscode-live-server#2628]
## I'm submitting a...

```html
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior
Stuck on load, will not load any files 

when launching live server
## Expected behavior
files loaded and page shown 

files loaded and page shown with live reload
## Environment

```html
Browser:

- [ x] Chrome (desktop) version XX
- [ x] Firefox version XX
- [ x] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: <!-- Check which version is installed --> 
- Platform:  <!-- Mac, Linux, Windows -->
- Visual Studio Code: <!-- `code --version` -->
```

**Comment by gavynevans** [comment]
@christian-bromann @adesugbaa @rjoydip-zz @mxschmitt @fdb @christian-bromann  @pluwen hi! Can one of the owners of this repo please delete the issues I've opened? They look terrible on my profile and I'd really appreciate it

**Comment by adesugbaa** [comment]
I just checked issue 2628. There is no option to delete the issue - maybe the owner of the repo can do that.

**Comment by adesugbaa** [comment]
I do not have permission to delete issues.

**Comment by gavynevans** [comment]
Shoot @adesugbaa, that's a bummer. Thank you for taking the time to respond tho. Any contact with Ritwick by chance? I'll literally pay y'all if that's what it'll take!
