### ISSUE TITLE
The Extension isn't working and GoLive Button doesn't appear

### ISSUE THREAD

**Issue by omar-danasoury** [ritwickdey/vscode-live-server#264]
Issue Type: <b>Bug</b>

I have installed the extension but it didn't work. I tried to reinstall it but it didn't work

Extension version: 5.3.1
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 6.3.9600

**Comment by KimchhunPoeng** [comment]
Thank you rjoydip

**Comment by viditvarshney** [comment]
@rjoydip  Please close the issue if its done many are opened  since they are solved
