### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by sariyamon** [ritwickdey/vscode-live-server#265]
Issue Type: <b>Bug</b>

sometimes live server not responding or very slow.

Extension version: 5.3.1
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299

**Comment by rjoydip** [comment]
Need more details.

**Comment by sariyamon** [comment]
Hi bro,
The issue has been resolved by reinstalling VS Code along with the
extension.So far its working fine.will let you know if anything happens.
Thank you very much.
