### ISSUE TITLE
v5.4.0 not published to the marketplace

### ISSUE THREAD

**Issue by dalDevelo** [ritwickdey/vscode-live-server#269]
## I'm submitting a...

```html
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[x] Other: <!-- Unpublished update -->
```

## Current behavior

v5.4.0 is in 'release' status, but is not available for download via the [VisualStudio Marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)

## Expected behavior

Able to download and install / update to v5.4.0 from within VSCode or download directly from the [VisualStudio Marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)

**Comment by ritwickdey** [comment]
There were few internal discussion, that's why the 5.4.0 gets delay. Anyway it's already published 😄
