### ISSUE TITLE
Possibility of add custom host

### ISSUE THREAD

**Issue by lavir** [ritwickdey/vscode-live-server#27]
Would be nice to have a possibility of add custom host. E.g you can access to the Mac from other by using a hostname which ends with '.local' e.g. 'http://my-mac.local:5500'. Right now you also can do this, but you cannot set the custom hostname in settings 'liveServer.settings.host' as default.

**Comment by ritwickdey** [comment]
Okay! Try  to `liveServer.settings.host : my-mac.local` .............  I know, it will indicate error, but ignore the error and give a try. Let me know it works or not.  :smile:

**Comment by lavir** [comment]
yes, it works well :)

**Comment by ritwickdey** [comment]
@lavir  Thanks for the confirmation. I'll remove the restriction on that settings in next update so that we can able to add custom host 👍

**Comment by ritwickdey** [comment]
This issue is resolved with v2.2.0.  Please update the extension. Thanks for the reporting.

If you like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).
