### ISSUE TITLE
Extension Host Terminated Unexpectedly v1.31

### ISSUE THREAD

**Issue by ahmadawais** [ritwickdey/vscode-live-server#273]
Issue Type: Bug

The latest release of v1.31 stops working due to this extension.

For details check out this issue since I have the same exact problem. 
https://github.com/Microsoft/vscode/issues/67999

```html
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
```

## Current behavior

No extensions work.

## Expected behavior

Extensions should work.

## Environment

```html
Browser:

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 5.3.1
- Platform: Mac
- Visual Studio Code: v1.31
```

**Comment by p-glynn** [comment]
have noticed this as well, feelsbadman

**Comment by KUBEK65** [comment]
Same issue.
MacOS.

**Comment by reynoldsDesign** [comment]
Same issue. 
Also MacOS

**Comment by adesugbaa** [comment]
Please try the 5.4.0 in the Releases tab. Please ensure that you are on the latest nightly build (for insiders).

We are awaiting feedback before publishing it to the Visual Studio Marketplace.

**Comment by BJSebastian** [comment]
Installing via the 5.4.0 .vsix file fixed the problem for me on my Mac.

**Comment by reynoldsDesign** [comment]
> Please try the 5.4.0 in the Releases tab. Please ensure that you are on the latest nightly build (for insiders).
> 
> We are awaiting feedback before publishing it to the Visual Studio Marketplace.

Back in business. Thank you!

**Comment by bgq007** [comment]
I know people are going to shake their heads at me, but how do I get and install the latest version to fix the issue if the latest version isn't in the Marketplace? Im new to this stuff. I really don't understand how I'd go about doing this.

**Comment by adesugbaa** [comment]
Please download 5.4.0 from this repo (under Releases), and try installing that manually.

```
View -> Command Pallete... -> Extensions Install from VSIX...
```

Select the extension you downloaded, and restart VS Code when it completes.

Please provide feedback - 5.4.0 will be published once we confirm it is working for all.

**Comment by bgq007** [comment]
@adesugbaa Thanks! That worked for me. All is back to normal (v5.4.0)

**Comment by helloflow** [comment]
Yes it works for me too! Thanks

**Comment by harpalassi** [comment]
worked for me, thank you

**Comment by ritwickdey** [comment]
I've published LiveServer@5.4.0 to marketplace. Please install it from marketplace

**Comment by Tupax** [comment]
> Please try the 5.4.0 in the Releases tab. Please ensure that you are on the latest nightly build (for insiders).
> 
> We are awaiting feedback before publishing it to the Visual Studio Marketplace.

Working!!
Tks!!

**Comment by crystalfp** [comment]
Seems it works depending on the extensions starting order. Sometimes it work flawlessly, sometimes crashes the extension server on startup, but after relaunching VS Code few times, it start working again. Note I use it as the Live Sass Compiler extension requires it. Thanks for looking!
