### ISSUE TITLE
live server not working

### ISSUE THREAD

**Issue by prabhatsuman7250** [ritwickdey/vscode-live-server#2772]
Type: <b>Performance Issue</b>

when i open with live server after code finish then live server not working .
 I am try many times but not resolve this problem .
popup show - windows cannot find true . make sure typed the name correctly , and then try again
please help!!!!!! 

Extension version: 5.7.9
VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (9.90GB free)|
|Process Argv|--crash-reporter-id 03a91b6a-a1e0-4228-a2f8-0e8c264d55bf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   116	 18268	code main
    0	    76	  4280	   utility-process
    0	    27	  4564	   crashpad-handler
    0	    83	  7508	fileWatcher [1]
    0	   189	 13984	window [1] (practice.html - Web dx - Visual Studio Code)
    0	   121	 14204	extensionHost [1]
    0	   127	  4428	     electron-nodejs ("C:\Users\prabh\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\prabh\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=14204)
    0	    84	  9540	     electron-nodejs ("C:\Users\prabh\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\prabh\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=14204)
    0	    88	 16980	window [2] (Issue Reporter)
    0	   214	 18960	   gpu-process
    0	    90	 20544	shared-process
    0	    81	 19248	     ptyHost
    0	    44	 22260	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (practice.html - Web dx - Visual Studio Code)
|    Folder (Web dx): 7 files
|      File types: html(4) css(1) jpg(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30731968
fixshowwlkth:30730052
hidesbindicator:30730055

```

</details>

**Comment by bulutibo** [comment]
Me yapacigimi bilmiyorum cozemiyorum cozmeme allah rizasi icin yardim edin
