### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DenisYurkov** [ritwickdey/vscode-live-server#278]
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.4.0`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/denis-yurkov/ritwickdey.LiveServer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by adesugbaa** [comment]
Please attach the **ritwickdey.LiveServer-unresponsive.cpuprofile.txt** file.

**Comment by ritwickdey** [comment]
I think, it's because of https://github.com/ritwickdey/vscode-live-server/issues/255

**Comment by ritwickdey** [comment]
Please upgrade the extension to lastest version. If it doesn't work, please let me know

**Comment by ritwickdey** [comment]
If you can share reproducible steps that would be even better.

**Comment by DenisYurkov** [comment]
Thanks helped!

**Comment by sinisabecic** [comment]
No, I am gettin it only on GitHub. I dont know why. Make a new folder 'mvc_sajt' in 'htdocs' and state all files from downloaded file(folder)  'mvc-master' on it. Advice for u: Use the Xampp.

**Comment by mrahdreegez** [comment]
Hello Ritwick,
Updated VSCode to latest version and everything seems to be working fine, thanks!

**Comment by vikaspoonia** [comment]
It was fixed after updating to new VScode version and extension for me.

**Comment by arjundapp** [comment]
Hello, 
I am also having this issue. can anyone help me to resolve?
I'm using VScode 1.33.0 and Live server 5.5.1 with MacOS

**Comment by belachkar** [comment]
Hi,
The same issue with vs code
version 1.39.0
OS: win 10 x64
[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://drive.google.com/open?id=1gRJEwb7zevcLejVwHNYbPtDsie_0DbVz)

**Comment by claudioseccia** [comment]
Same issue, MacOs, latest VsCode (1.41.1) and Live Server 5.6.1 :(

**Comment by dan-farley** [comment]
In my situation it seems to be related to having the composer "vendor" folder included in my workspace.  Maybe it is having to watch all of those tens of thousands of files for file refreshes?  Anyway I was able to select only my main web app folder and reduced my CPU usage from ~300% to 5%.  Is there some way to exclude folders from the reload rules?

**Comment by darkRaspberry** [comment]
https://github.com/ritwickdey/vscode-live-server/issues/741
Also

**Comment by DEVANGYDV** [comment]
Issue Type: Performance
Extension Name: LiveServer
Extension Version: 5.6.1
OS Version: window_NT x64 10.0.19041 
VSCode version: 1.48.2
[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/5144866/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)

**Comment by An-max-i** [comment]
таже проблема с расширением
/home/denis-yurkov/ritwickdey.LiveServer-unresponsive.cpuprofile.txt

**Comment by dinotomassini** [comment]
Hi,
Same error ( 
    LiveServer v5.6.1 
    ritwickdey.LiveServer-unresponsive.cpuprofile.txt 
)
but on arch linux and using vscode v1.53.2.
Downgrade the extension to 5.6.0 and works for me

**Comment by OmarVD-code** [comment]
Hi,
Same error (
LiveServer v5.6.1
ritwickdey.LiveServer-unresponsive.cpuprofile.txt
)
but on arch linux and using vscode v1.53.2.
Downgrade the extension to 5.6.0 and works for me

**Comment by SatvikG7** [comment]
When is this problem gonna be fixed

**Comment by F-Olive** [comment]
Hi
Same error 
Live Server V5.6.1
"ritwickdey.LiveServer-unresponsive.cpuprofile.txt"
MacOS using VSCode v1.56.2

**Comment by JoggerShyr** [comment]
[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/6651683/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)

Hi, here is my device information:
Processor	Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz   2.40 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor

Edition	Windows 10 Pro
Version	21H1
Installed on	‎6/‎20/‎2020
OS build	19043.1023
Serial number	PC1JJ87P
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Comment by KorigamiK** [comment]
[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/7211614/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)

This is my device:
Host: Inspiron 11 - 3147
OS: MX x86_64
GPU: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Displ
CPU: Intel Pentium N3530 (4) @ 2.582GHz
Memory: 2849MiB / 3832MiB

**Comment by lucasffpinho** [comment]
Hello Ritwickdey,
I've been experiencing issues related to the one in this post.
After launching the local server, CPU and Memory usage starts to rise until it crashes.
https://github.com/ritwickdey/vscode-live-server/issues/2577

**Comment by Mohitprajapati2299** [comment]
this is my fist day plase help me

**Comment by RussQuan** [comment]
same here on Macbook Air M4
