### ISSUE TITLE
LiveServer running really slow on website root and won't close down

### ISSUE THREAD

**Issue by gfmoore** [ritwickdey/vscode-live-server#28]
I have a QNAP NAS which I use as a webserver.
I have a number of projects under the main root folder
VSCode and live server runs fine if I open a project under the root folder.

However when I used the root folder as the vscode folder and on the root folder I created an index.html file , when I launched this it took ages to load, doesn't respond to changes (or if it is it is taking forever) and I couldn't stop the live server. I closed down Chrome and still couldn't close the server down.

An error bar popped up: Running the contributed command:'extension.liveServer.goOffline' failed.

Very helpful, not.

Now the NAS is open to the internet, but I can't understand why it is fine on sub folders, but not on the rootfolder. 

I have rebooted my laptop and tried again, I have cleared the cache in chrom (I use an extension to do this as well). 

Any thoughts or suggestions as to what I could look at. 

It's not a deal breaker as I can run the page the old fashioned way. Oh I am using index,html (there is also an index.php there - but it's a QNAP thing?) uhmmm?

**Comment by ritwickdey** [comment]
Sorry, I don't get the point. Live Server is a extension that creates a local server `localhost`. What is the link of your `QNAP NAS` with `Live Server` ?

Btw, which operating system you're using? 

[This your root folder contains lot of file (may be 5K-10K), it may response slowly due to huge files. (All the change detection is made by [chokidar](https://github.com/paulmillr/chokidar) library). There is a way to exclude files, checkout the [settings section](https://github.com/ritwickdey/vscode-live-server#settings) ]

**Comment by gfmoore** [comment]
Yes I know what you mean. It shouldn't make any difference, but something weird is going on.

I use win10.

Ahh i wonder if that's the problem. Thought the root directory contains only a few files itself, it contains a number of sub folders used for other web sites that contain quite a bit. 

Oooh: In fact I have just noted a recursively existing phpMyadmin folder. That is phpmyadmin folder contains phpmyadmin ad nauseum. I'm deleting the subfolder. How the heck that happened???

I'll let you know if that solved the problem, but at least its a direction of attack, thanks.

regards, 

Gordon

gm@gordonmoore.co.uk
g.f.moore@keele.ac.uk


On 30/09/2017 13:54:57, Ritwick Dey <notifications@github.com> wrote:
Sorry, I don't get the point. Live Server is a extension that creates a local server localhost. What is the link of your QNAP NAS with Live Server ?
Btw, which operating system you're using?
[This your root folder contains lot of file (may be 5K-10K), it may response slowly due to huge files. (All the change detection is made by chokidar [https://github.com/paulmillr/chokidar] library). There is a way to exclude files, checkout the settings section [https://github.com/ritwickdey/vscode-live-server#settings] ]

**Comment by gfmoore** [comment]
Okay, so I eventually got rid of the recursive phpMyAdmin - had to use the NAS to uninstall and then restart which took longer than I expected and was fairly frightening ;),  but all okay now.

So my root and folders use up nearly 90Mg and server still runs v slow. I've had a look at the settings, but can't quite figure out how I exclude say a folder/directory. So I have a folder in my root called MathFiguredOut, how do I exclude this?

(btw the link of QNAP with liveserver is just that the QNAP NAS has a "Web" folder and this is what the apache server in the NAS looks at as the root folder. I'm just working directly with the files there from VSCode - don't worry I would do this in a professional environment, but since it's my werver what the heck, saves all that uploading and copying malarky :)

(till I get it wrong of course!)

G

**Comment by ritwickdey** [comment]
Sorry. What is the `90Mg`? Another things, pick any sub folders (not contains much file) & open with VSCODE. & try to start 'live server' and made some change & check whether it's working fast or not.

[I am also using Windows 10, No issue so far]

**Comment by gfmoore** [comment]
Sorry I meant MB (edited the post).

yes, it's fine on subfolders, just not root. Even on the largest and most numerous in terms of files folder.

Weird isn't it.

I suppose another thought is that the root folder is essentially a Linux directory, though it's all pretty transparent to win 10. If  it was a problem then why aren't the subfolders affected?

Anyway it's not a major issue as I've moved on...

Thanks for your responses, at least I fixed an issue I didn't even know I had :)

**Comment by ritwickdey** [comment]
> the root folder is essentially a Linux directory

I meant work-space folder. (I called it as Root) 

>  at least I fixed an issue I didn't even know I had :

Is it fixed?

**Comment by gfmoore** [comment]
Not the substantive issue, I meant the issue of having multiple levels of phpmyadmin is fixed.

⁣Regards, Gordon
gm@gordonmoore.co.uk​

**Comment by ritwickdey** [comment]
`phpmyadmin`?

but live server is for static files, not for 'php' or 'asp.net' or 'node.js'

**Comment by gfmoore** [comment]
Mate, what are you going on about? My root folder contains phpmyadmin as it's a real love server and contains all sorts of stuff. It's got nothing to do with anything. I don't use live server for phpmyadmin etc.

Let me try and make it clear.

I have a production server. It has a root folder (in apache it would be called .htdocs on the NAS it is called web) it contains a number of websites each in its own directory/folder. The root also has a website, because that's how it started. 

If I use vscode and select one of the folders and work with my files: html, js, css and use live server everything is hunky dory and very good, much better than brackets live server as I can use the dev tools as well, so kudos.

However, if I select the root folder and work with my html and css files, itis incredibly slow to start up the web page using live server and any changes I make are equally slow to refresh.

It doesn't make any sense to me.  Why would liver server work fine on subfolders, but not on the main folder.

I suspect there is something happening in the QNAP NAS box, which hosts the web server that is interfering with the live server, but what it is or why is beyond me.

I just hoped that as the developer of live server you might have some insight into what is going on, but if not, no worries. As I said I've moved on now.

Thanks for your help.:)

G

regards, 

Gordon

gm@gordonmoore.co.uk
g.f.moore@keele.ac.uk


On 02/10/2017 09:10:15, Ritwick Dey <notifications@github.com> wrote:
phpmyadmin?
but live server is for static files, not for 'php' or 'asp.net' or 'node.js'

**Comment by ritwickdey** [comment]
oh! Sorry for the late, I got your issue properly. 

Whenever you start server from root folder, it just live reload get slow but from the sub folder it is fine. right?


One think you telll me.........  Is the all files are important to track its changes (because the performance is decreasing due to huge file) ? 

Just a workaround : (Let me know it works for not)
1. Open the vscode from root folder.
2. Set up VScode settings  following..
```json
 //add all unsupported file having in your project
liveServer.settings.ignoreFiles:  [
    "**/*.php"  
],
//change live server root if
liveServer.settings.root: "/subfolder/mainFolder"
```

**Comment by gfmoore** [comment]
//add all unsupported file having in your project
    "liveServer.settings.ignoreFiles":  [
        "**/*.php"  
    ],
    //change live server root if
    "liveServer.settings.root": "/subfolder/mainFolder",

-I added in the quote marks :)

not sure what I'm supposed to put for the /subfolder/mainFolder ?

**Comment by ritwickdey** [comment]
I meant,

Suppose your root folder is `C:\Project\` but all of your  static file is in `C:\Project\project1\staticRoot\`. you have also `C:\Project\peoject2\**`  and so on..... but all aren't containing   static file.

now if you open vscode from root (`C:\Project\`). It's best to track all file starting from  `C:\Project\project1\staticRoot\`. 
If you've this situation, you can shift the root of the live server. 
`"liveServer.settings.root": "/project1/staticRoot/"`,

got it?

**Comment by gfmoore** [comment]
Sorry, I must be having a senior moment. :(

My root is \\xxxnas\Web
below that I have \\xxxnas\Web\project1,  \\xxxnas\Web\project2,  \\xxxnas\Web\project3 etc

I only want to work with the static files in  \\xxxnas\Web

Sorry, I haven't responded sooner, but I have had to do other work :)

**Comment by ritwickdey** [comment]
you meant, all of the static files are in `\xxxnas\Web`... not `\xxxnas\Web\Anywhere-else\**`

In this case, 
try to exclude all folders from  `\xxxnas\Web`
```json
{
     "liveServer.settings.ignoreFiles":  [
                "project1/***",
               "/somewhere-else/**",
               "project2/***,
                "**/*.php"
     ],
}
```

Please try that. let me know it works or not

**Comment by ritwickdey** [comment]
Actually this issue is from [chokidar](https://github.com/paulmillr/chokidar) 😞

**Comment by ritwickdey** [comment]
`chokidar` is taking responsibility to raise event on change detection

**Comment by gfmoore** [comment]
:)

Excluding the subfolders and their php files seems to have done the trick. I can now work on the root folder and your server is working fine.

What is it about the php files then??

**Comment by ritwickdey** [comment]
Wow! That's great. Live Server is for static files not for php. PHP will not run through Live Server.

By this `"liveServer.settings.ignoreFiles"` settings you're telling to Live Server - "I don't have any static files on other directory, so you don't have to track does file." 😃
