### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by alexis1986** [ritwickdey/vscode-live-server#282]
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.3.1`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.0`
[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/2847796/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)

**Comment by ritwickdey** [comment]
Can you please share a screenshot of your workspace in comment of #278  ?

// Duplicate of #278

**Comment by ritwickdey** [comment]
Please upgrade the extension to lastest version (I've updated it recently). 

If it doesn't work, please let me know in comment of #278

**Comment by ritwickdey** [comment]
If you can share reproducible steps that would be even better. (Comment in #278 )
