### ISSUE TITLE
Extension host terminated unexpectedly. v5.5.0

### ISSUE THREAD

**Issue by jonbp** [ritwickdey/vscode-live-server#285]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

Live Server 5.5.0 throws an "Extension host terminated unexpectedly." fatal error that stops the functionality of other extensions.

Rolling back to 5.4.0 resolves the issue.

**Error Screenshot**

![screenshot 2019-02-12 at 11 07 16](https://user-images.githubusercontent.com/3267483/52631309-641c1b80-2eb6-11e9-8c2f-49a2a80b624f.png)

**Console Screenshot**

![screenshot 2019-02-12 at 11 01 11](https://user-images.githubusercontent.com/3267483/52631322-7007dd80-2eb6-11e9-98b2-ade3c0c7d1dd.png)

## Environment

```html
For Tooling issues:

- Live Server: 5.5.0
- Platform:  macOS 10.14.1
- Visual Studio Code: 1.31.0
```

**Comment by musti-91** [comment]
I have same I could not even uninstall it.☹️

**Comment by spacecakes** [comment]
I have this error too. Goes away when disabling the extension.

**Comment by ritwickdey** [comment]
Hi @musti-91, go to /users/<USERNAME>/.vscode/extensions/ and delete live server folder to uninstall it.


Anyway, I'm very sorry that you're guys facing same issue. I don't have macbook to figure out this issue. 


@adesugbaa  Can you please figure out the issue? May be if you can do rebuild the extension and publish it to Github.

**Comment by ritwickdey** [comment]
For TEMPORARY Fixing : Install Previous version `v5.4.0`

![image](https://user-images.githubusercontent.com/18099464/52633286-e6720300-2ee9-11e9-8d04-d032a1e1c765.png)

**Comment by ritwickdey** [comment]
Hi, can any want to try the following? (First install v5.5.0 from vscode markplace,)

1. Please donwload the [fse.zip](https://github.com/ritwickdey/vscode-live-server/files/2855662/fse.zip)
2. Extract the `fse.node`
3. Now go to `: /Users/YOUR_USERNAME/.vscode/extensions/ritwickdey.liveserver-5.5.0/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/`
4. Now replace the `fse.node`


Please let me know! I'll appreciate if anyone try the following steps

**Comment by spacecakes** [comment]
> Please let me know! I'll appreciate if anyone try the following steps

Yep, this does seem to be working on macOS and Visual Studio Code latest!

**Comment by AnthonyRubioDev** [comment]
Hello @ritwickdey ! Seems to work here. Here is what i got ! 
<img width="454" alt="capture d ecran 2019-02-12 a 13 01 54" src="https://user-images.githubusercontent.com/45395092/52634095-96357980-2ec6-11e9-8818-64f3a879e8ba.png">

**Comment by ritwickdey** [comment]
Sweet! Thank you guys. I'm publishing a new version to marketplace. I still don't what is the BEST to fix the issue. But util then I'll manually replace the `fse.node`

**Comment by ritwickdey** [comment]
I've published a new version to store. Can you guys please install the new version (v5.5.1) and update me if it works or not. 

Thank you

**Comment by AnthonyRubioDev** [comment]
Seems to work here ! Thanks for the fast support @ritwickdey ! You guy rock !

**Comment by spacecakes** [comment]
Yes, for me as well. Thanks a lot!

**Comment by jonbp** [comment]
Work's great for me too. Thanks for the swift fix!

Seems to work for everyone so I'll close the issue.

**Comment by ritwickdey** [comment]
Ahhh!   Thank you so much guys for the supports.

**Comment by dashingvampire** [comment]
sir..its not working at all for me right now. yesterday i updated it to i guess 5.4. and i updated vscode too.
and then the live reload stopped working. i have vscode on autosave. and now i have to refresh the live server chrome window manually.....i searched in your issues for long hours yesterday.
uninstalled live server..uninstalled vscode.
installed all again. 
restarted system.
and now i installed older 5.3.0 live server version.

still have to refresh manually.
please help me....i really need it.

**Comment by dashingvampire** [comment]
updated it back to 5.5.1. still same issue.

**Comment by ritwickdey** [comment]
Hi @dashingvampire, Please open a new issue request. I'll happy to help you

**Comment by Xenophon81** [comment]
Thank you so much for fixing this. Was going crazy with the installing / uninstalling of plugins. Even Live-Sass Compiler broke because of this.

**Comment by Jvalal** [comment]
still broken on my end.

![image](https://user-images.githubusercontent.com/3803053/52833569-2f64bb80-3092-11e9-86ce-b0d4319f5f6c.png)

**Comment by Jvalal** [comment]
I can't even uninstall it or disable it!!! C'mon....! 

![image](https://user-images.githubusercontent.com/3803053/52834386-810f4500-3096-11e9-9d47-93ab6978d271.png)

**Comment by ritwickdey** [comment]
Try this one to uninstall it 

https://github.com/ritwickdey/vscode-live-server/issues/285#issuecomment-462728705


Please upgrade it to latest version, and let me know if doesn't work

**Comment by ridesirat** [comment]
Hello @ritwickdey and everybody.
The same start happening to me today. But last night was ok (Lisbon time).
I think the problem has some connection with Live Sass. I disabled it and Live Server is ok. When I tried both I couldn't.

**Comment by FelesNoctis** [comment]
Should be resolved as of Image Preview 0.17.4. Mine's running just fine again!

https://github.com/kisstkondoros/gutter-preview/issues/40

**Comment by dusitsiri** [comment]
if you installed some theme, you can try. I'm try to reinstall extensions and  doesn't install all themes(everything about theme). It's work for me.

**Comment by apocolyptic** [comment]
Im getting this same error as of an update i did today.. previous versions are not quick fixing the issue and i can not uninstall it.. im gonna be real pissed if i have to uninstall and reinstall vsCode..

**Comment by Yuvraj535** [comment]
Im getting the same error i have done that fsnode file replace file but still the error pops up

**Comment by Rajdeep100** [comment]
Take a look at your antivirus, add that detected file to your antivirus's exclusion list

**Comment by branaus** [comment]
I had the same error. Downgraded to v5.5 and it is now working again

**Comment by didymus707** [comment]
Hi, on the recurring issue of **External host terminated unexpectedly** and this is the updated version(5.6.1). Here is a picture of what I am talking about
![Screenshot from 2020-06-06 00-59-42](https://user-images.githubusercontent.com/38667458/83930888-beb74600-a791-11ea-9abc-ab7311eee0bd.png)

**Comment by alapo92** [comment]
To me this is connected to Live Sass Compiler. The Extension terminates after using an @import statement

**Comment by didymus707** [comment]
@alapo92 I have not used live sass in a while

**Comment by ToledoNicola** [comment]
yes also to me and i can't uninstall ** Cannot uninstall extension 'Live Server'. Extension 'Live Sass Compiler' depends on this.** @ritwickdey

**Comment by aayamdahal** [comment]
> To me this is connected to Live Sass Compiler. The Extension terminates after using an @import statement

same for mee is there a fix?

**Comment by clintonhays** [comment]
> > To me this is connected to Live Sass Compiler. The Extension terminates after using an @import statement
> 
> same for mee is there a fix?

I'm getting the same issue exactly. Tried so many fixes...no luck.

**Comment by clintonhays** [comment]
Seems to be linked to Color Highlight extension per https://github.com/ritwickdey/vscode-live-sass-compiler/issues/193

I uninstalled Color Highlight and haven't had any issues.
