### ISSUE TITLE
Live Server loads and does not start...

### ISSUE THREAD

**Issue by zxczxc52** [ritwickdey/vscode-live-server#2850]
Hello everyone, I have one problem with Live Server in VS Code. Can you help me?
I run Live Server, but it keeps loading and loading. And it won't start at all. What do we have to do? I've already uninstalled it and reinstalled it, but I still haven't found a solution. 

![liveserver](https://github.com/ritwickdey/vscode-live-server/assets/83227616/8b03855d-983b-413d-acff-dbafe86b219c)

**Comment by Adityaraj002** [comment]
I'm get same problem and also it is not opening browser automatically

**Comment by zxczxc52** [comment]
I solved my problem, it was due to the fact that I started an infinite loop. And because of this, my server broke))

**Comment by zxczxc52** [comment]
I solved my problem, it was due to the fact that I started an infinite loop. And because of this, my server broke))
