### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Taariqq** [ritwickdey/vscode-live-server#289]
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.4.0`
- OS Version: `Linux x64 4.4.0-53-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/t/ritwickdey.LiveServer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ritwickdey** [comment]
please upgrade the extension and let me know.

Same as #278

**Comment by ritwickdey** [comment]
If you can share reproducible steps that would be even better. (Comment in #278 )
