### ISSUE TITLE
Runs nicely but wont to refresh changes in live(

### ISSUE THREAD

**Issue by dkfl1995** [ritwickdey/vscode-live-server#29]
I trying start server and instance runs good) also for smartphone but i cant to use all of features provided because it DONT WANT to refresh instantly and in-live my changes into project... and also i see the (maybe, im not sure of "FORBIDDEN" icon like circle with diagonal line) in status line on bottom of workspace.
What can i do to fix this?

Pretty thanks you! However, u made nice addon and cured my brain-pain.

P.S. Wrote offhand. Have without no doubts ugly english skills. But if not, u can assure me with this youself.

**Comment by dkfl1995** [comment]
Hey) sorry but i ought to say about my posible way to solve this issue.. Autosave was off
and if i turned it on, all gone work fine i see. So from now you can put out my beggings) and just hear thanks from meee)

**Comment by ritwickdey** [comment]
Is the issue resolved?

> DONT WANT to refresh instantly and in-live my changes into project

I don't get that? Whenever you saved tracked file, live server will refresh the browser page -> This is the feature. Sorry I am not clear.

**Comment by abhiinos111abhi** [comment]
change in autosave delay will help you
`"files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1`
