### ISSUE TITLE
Live Server Doesn't Work for .htaccess file 

### ISSUE THREAD

**Issue by viditvarshney** [ritwickdey/vscode-live-server#294]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other:
```

## Current behavior

While creating the project , i have to remove the extension from the address bar and 404 error page linking , so i made a  `.htaccess` file . For checking that everything is correctly set up i took a look of that using VS CODE LIVE SERVER  , but it didn't working  . I pushed it to the server and when the site goes LIVE then it worked , but the vscode live server doesn't show the results ..

## Expected behavior

- It should work on the vs code server . 

## Environment

```html
Browser:

- [x] Chrome (desktop) version 72.0.3626.109 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server:   5.5.1    
- Platform:    Windows 
- Visual Studio Code:    1.31.1    
```

**Comment by viditvarshney** [comment]
Can you please look at this issue @ritwickdey  and @rjoydip

**Comment by ritwickdey** [comment]
Hey. What do you want to achieve? 

(I'm not familiar with htaccess file. As far knowledge it's a config file for Apache server)

**Comment by viditvarshney** [comment]
Yes you are right but  , as i mention my issue .
okk , is there is a way to check .htaccess file in vscode . i only know one way to push that in your server

**Comment by ritwickdey** [comment]
Nope. It's a node server. It will not recognise  htaccess file.

What features/behaviour are you look for?

**Comment by viditvarshney** [comment]
like i want to remove the file extensions and link of a error page for my website , when i checked this on vs code live server , it doesn't work and so i pushed it to the website and it worked

**Comment by ritwickdey** [comment]
It can be made ambiguity. 

Eg. 
if there has 2 file.

1. `hello.html`
2. `hello/index.html`


now if user visit `<url>/hello`, what page should it render ?

**Comment by viditvarshney** [comment]
yes , so is there any other way to do that thing ?
  and how to check htaccess file locally , is it possible ?

**Comment by viditvarshney** [comment]
when user visit  `<url>/hello` , the page which is render is depend on the programmer that , which url he he links with the htaccess file 
Yeah ! , actually `users are only able to see the file name but on the backend the the redirection occurs on the url with extension

**Comment by ritwickdey** [comment]
I'm not sure, it'll work or not => Give a try for `liveServer.settings.mount`

**Comment by viditvarshney** [comment]
okk i will check 
give me your social presence

**Comment by poojasource2019** [comment]
hi vidit, i am facing the same problem that i am not able to remove the extension from URL. I am using Live server and have created .htaccess file correctly. It is still not working. If u can plz help with how it worked for u.

**Comment by Trying-2-Code** [comment]
I believe this is still an issue. For organization purposes I have my html files in one folder, and with firebase am able to get rid of the .html. It would be a very useful feature to have.
