### ISSUE TITLE
Cannot GET/

### ISSUE THREAD

**Issue by jmmrdev** [ritwickdey/vscode-live-server#3]
Hi, I seem to be having problems previewing my files located in subfolders. I always get this message:
![image](https://user-images.githubusercontent.com/29688279/27811917-917ee5a0-609d-11e7-92f0-363e827e435c.png)

However, I don't have any problems opening html files which is located directly inside the main folder.

**Comment by ritwickdey** [comment]
Can you show me the folder & File structure when you get the error?

**Comment by ritwickdey** [comment]
I got the bug & have fixed it.
Today I'll push the update to VS marketplace. :)

anyway, a lot of thanks  :)

**Comment by ritwickdey** [comment]
Hi, I published a new version with this fix update. Let me know if it works for you or not.

**Comment by jmmrdev** [comment]
Hello, sorry for not replying sooner was kinda busy :) . It works now . Thanks for the fast update and very very great extension :D

**Comment by ritwickdey** [comment]
Thank you very much for the feedback. Please feel free to suggest me or report bug :)

**Comment by GitMervin** [comment]
![cannot get](https://user-images.githubusercontent.com/40827087/42274009-c66555de-7fbd-11e8-8ac6-a90b97b57aa7.PNG)

**Comment by GitMervin** [comment]
![cannot get](https://user-images.githubusercontent.com/40827087/42274105-10bc7978-7fbe-11e8-9f1c-9996018a16db.PNG)
Hi, I'm having a problem when It comes to php but in html it actually works Thanks :)
