### ISSUE TITLE
Launch with Firefox Developer Edition? [Bug in AdvanceCustomBrowserCmdLine]

### ISSUE THREAD

**Issue by hdd1013** [ritwickdey/vscode-live-server#31]
Hi.
Is it possible to launch the Live Server browser with Firefox Developer Edition?
Maybe it would be nice if the extension could parse the settings string and just launch the exe if an exe location is specified instead of a browser name.

**Comment by ritwickdey** [comment]
Yep! you can do it through `liveServer.settings.AdvanceCustomBrowserCmdLine` settings.

You have to do it :
**`"liveServer.settings.AdvanceCustomBrowserCmdLine": "C:\\Program Files\\Firefox Developer Edition\\firefox.exe"`**

**Comment by ritwickdey** [comment]
Opps! found a bug on this settings. 

Workaround: 
`"liveServer.settings.AdvanceCustomBrowserCmdLine": "C:\\\"Program Files\"\\\"Firefox Developer Edition\"\\firefox.exe"`


Soon it will be fixed.

**Comment by abhiinos111abhi** [comment]
Is it possible to to launch with **chrome without extension** in liveServer

**Comment by ritwickdey** [comment]
Hi @abhiinos111abhi , I don't get that

**Comment by hdd1013** [comment]
Thanks for the response! So basically you can do anything you can do on CMD, as long as you use properly escaped strings, right?

**Comment by ritwickdey** [comment]
Yep! With this settings... butI As I said before there is a tiny bug... may be today I'll ship the fix update to store...  .

**Comment by abhiinos111abhi** [comment]
brackets editor live server starts with chrome with no extension.
the reason behind this is loading browser with extension will add more scripts and debugging affects that
so

**Comment by ritwickdey** [comment]
If you're talking about just static files, you don't need any further extension . But if you re taking about dynamic pages like php or node.js , you have to use another extension  "live server web extension"..

**Comment by ritwickdey** [comment]
This issue has been resolved with v3.1.0.  Please update the extension and thanks for the reporting.

If you like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).

**Comment by dakshgautam1** [comment]
For opening live-server with Firefox developer edition on Mac. Copy paste this to user settings. 

"liveServer.settings.CustomBrowser": "/Applications/Firefox Developer Edition.app"

**Comment by misterhtmlcss** [comment]
@dakshgautam1 so you may be trying what I actually wanted and I just found out it works. I wanted to use `"liveServer.settings.CustomBrowser": ` as well not `liveServer.settings.AdvanceCustomBrowserCmdLine`, but they weren't talking about HOWEVER you gave me an idea when you wrote what you did. 
So I tried this:
`"liveServer.settings.CustomBrowser": "Firefox Developer Edition"`
And despite VSC protesting, when I click on my `go live` button it launches developer edition.  Not sure if you still had this issue or how many others are like us, but this works for me for now.

@ritwickdey no idea if you want to add this as a method for doing this on Mac or not, but perhaps it's worth leaving it here at the least so others can find it, but it's not 'officially supported' that way as well. Win win 👍

**Comment by SomeEarth86** [comment]
> @dakshgautam1 so you may be trying what I actually wanted and I just found out it works. I wanted to use `"liveServer.settings.CustomBrowser": ` as well not `liveServer.settings.AdvanceCustomBrowserCmdLine`, but they weren't talking about HOWEVER you gave me an idea when you wrote what you did.
> So I tried this:
> `"liveServer.settings.CustomBrowser": "Firefox Developer Edition"`
> And despite VSC protesting, when I click on my `go live` button it launches developer edition. Not sure if you still had this issue or how many others are like us, but this works for me for now.
> 
> @ritwickdey no idea if you want to add this as a method for doing this on Mac or not, but perhaps it's worth leaving it here at the least so others can find it, but it's not 'officially supported' that way as well. Win win 👍

this worked on my mac instantly, earlier i was trying to locate the firefox dev edition, and was pasting the link in "liveServer.settings.CustomBrowser": .

Thanks a ton!

**Comment by RhuVaeruxia** [comment]
@dakshgautam1 Thanks You! 
"liveServer.settings.CustomBrowser": "/Applications/Firefox Developer Edition.app"

**Comment by Bastigonzales** [comment]
For those who are using window this method worked for me. 

> Make sure to follow the exact file name of your EXE, mine starts with a capital letter because i renamed my exe.

### "liveServer.settings.CustomBrowser": "\\Program Files\\Firefox Developer Edition\\Firefox.exe"
