### ISSUE TITLE
How to change Port from 127.0.0.1:5500 to localhost

### ISSUE THREAD

**Issue by immohammadjaved** [ritwickdey/vscode-live-server#32]
Where is the settings to change port from 127.0.0.1:5500 to localhost

**Comment by ritwickdey** [comment]
Sorry. I don't get that. 

If you want change port, you can use the settings `liveServer.settings.port:3000`.

all the settings are listed here => https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

**Comment by immohammadjaved** [comment]
Thanks @ritwickdey,

**Comment by naim473596** [comment]
hlw baiya

**Comment by shreekantkumar620412** [comment]
![Uploading 2023-05-12 20_14_41.096+0530.jpg…]()

**Comment by shreekantkumar620412** [comment]
Shreekantkumar.com

**Comment by kabrahamyan** [comment]
barev bolorin

**Comment by abuyousufratul** [comment]
hi

**Comment by Dimaanoangelu** [comment]
https://drive.google.com/drive/folders/1y_O00USadIqwtW6S6lOQEQUGIQYhUm0d?usp=drive_link

**Comment by PrakashJangid17** [comment]
Nice

**Comment by Filimon2025** [comment]
http://127.0.0.1:5500/index.html

**Comment by raj94023** [comment]
Yes

**Comment by WebDevelopment761** [comment]
yes
