### ISSUE TITLE
How do I change default directory of Live Server?

### ISSUE THREAD

**Issue by ashishgupta1350** [ritwickdey/vscode-live-server#33]
When I run the live server, it basically points to the default directory instead of letting me choose on which file to run the live server. I need a way such that i can get to choose which file to run on the live server(ie it may be saved anywhere on my computer and I should be able to run it!).

**Comment by ritwickdey** [comment]
There is a settings `liveServer.settings.root` to change root from work-space root directory to anywhere else (but it should be inside of work-space).

https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

**Comment by SylannBin** [comment]
I figure it's the best place to mention the following issue:

@ritwickdey The option you are mentioning only works in the main vscode settings, but not in the project settings which is kind of odd since you are going to have a different root for each project ... I guess.

**Comment by rjoydip** [comment]
@SylannBin You can configure settings for each project separately by create .vscode (folder) > settings.json and overwrite settings for that project

**Comment by rjoydip** [comment]
@ashishgupta1350 @SylannBin I am closing this issue if still have this issue then reopen it.

**Comment by cohn17** [comment]
Hi, sorry to ask, but I do not understand how to change the settings. I see a list of settings under "Contributions" but cannot actually make any changes there. Please advise! Thank you.

**Comment by nitech** [comment]
@cohn17 I had some issues too. What I did was: 

1. Create a folder under the root of the site, called `.vscode`
2. Add a file there, called `settings.json`
3. Edit the file and add the following: 

```json
{
    "liveServer.settings.root": "/dist"
}
```
(`dist` being the root folder I want the liveserver to know about)

Then I actually had to edit the global settings.json: 

1. CTRL+SHIFT+P and type "Preferences".
2. Search for "liveserver" and click "Edit in settings.json"

![image](https://user-images.githubusercontent.com/1279436/55608716-4f098d80-577f-11e9-8dc5-6aaff35ba7b2.png)

3. I then added the same code inside my global settings.json: 

![image](https://user-images.githubusercontent.com/1279436/55608761-6cd6f280-577f-11e9-8424-f50406c189b9.png)

4. Then launched liveserver, killed it, removed the setting in the global settings.json and then relaunched the server. 

From now on, liveserver seems to follow whatever is written in the /.vscode/settings.json - file. Perhaps a bug in vscode?

**Comment by ect0-1** [comment]
how do you do this on mac I cannot make a .vscode folder with a "." as the first character.

**Comment by alexalannunes** [comment]
> @cohn17 I had some issues too. What I did was:
> 
> 1. Create a folder under the root of the site, called `.vscode`
> 2. Add a file there, called `settings.json`
> 3. Edit the file and add the following:
> 
> ```json
> {
>     "liveServer.settings.root": "/dist"
> }
> ```
> 
> (`dist` being the root folder I want the liveserver to know about)
> 
> Then I actually had to edit the global settings.json:
> 
> 1. CTRL+SHIFT+P and type "Preferences".
> 2. Search for "liveserver" and click "Edit in settings.json"
> 
> ![image](https://user-images.githubusercontent.com/1279436/55608716-4f098d80-577f-11e9-8dc5-6aaff35ba7b2.png)
> 
> 1. I then added the same code inside my global settings.json:
> 
> ![image](https://user-images.githubusercontent.com/1279436/55608761-6cd6f280-577f-11e9-8424-f50406c189b9.png)
> 
> 1. Then launched liveserver, killed it, removed the setting in the global settings.json and then relaunched the server.
> 
> From now on, liveserver seems to follow whatever is written in the /.vscode/settings.json - file. Perhaps a bug in vscode?

Thankss!

**Comment by imdyakov** [comment]
Hi,

I am new to VS Code so sorry for dummy question.

What if for learning purposes I have a few different folders with the same structure inside with different lessons (versions of the sites) and I need to switch from one to another inside the same Workspace? Let's say I opened one index.html inside one of the folders inside root of my Workspace and launched it with the Live Server. Then I need to go to another folder inside my Workspace root and to open another index.html inside that separate folder. I open it up in the Live Server but there is still the previous site version opened again.

Is there a way to set it up in the way that it would open up the files from the currently selected folder inside my Workspace (from the folder where currently active file is located in and its subfolders)?

**Comment by bgregi** [comment]
> Hi,
> 
> I am new to VS Code so sorry for dummy question.
> 
> What if for learning purposes I have a few different folders with the same structure inside with different lessons (versions of the sites) and I need to switch from one to another inside the same Workspace? Let's say I opened one index.html inside one of the folders inside root of my Workspace and launched it with the Live Server. Then I need to go to another folder inside my Workspace root and to open another index.html inside that separate folder. I open it up in the Live Server but there is still the previous site version opened again.
> 
> Is there a way to set it up in the way that it would open up the files from the currently selected folder inside my Workspace (from the folder where currently active file is located in and its subfolders)?

I know I'm late, but I just figured this out. Go to the index.html file you want to launch and right-click on it, then choose "Open with Live Server". Remember to close the server first if it's already running from a different html file.

**Comment by vareshwar** [comment]
i am also facing this problem, i am also new to line server and github. pls help me. have a look at screenshot please.

"Server is Started at port : 5500"
"Invaild Path in liveServer.settings.root settings. live Server will serve from workspace root"

my code in file is:
{
    "liveServer.settings.port": 5500,
    "liveServer.settings.root": "/dist",
    "liveServer.settings.AdvanceCustomBrowserCmdLine": "chrome --incognito --remote-debugging-port=9222",
    "liveServer.settings.NoBrowser" : false,
    "liveServer.settings.ignoreFiles" : [
            ".vscode/**",
            "**/*.scss",
            "**/*.sass"
    ],
    "liveServer.settings.useLocalIp": true,
    "liveServer.settings.CustomBrowser": "chrome"
    

}
![Screenshot 2021-11-18 152313](https://user-images.githubusercontent.com/11679314/142392515-f7f9d52a-d313-48ee-b01b-6065da352dbb.png)

**Comment by ArtRevera** [comment]
You can change it using Ctrl+Shift+P & type "Live Server: Change Live Server workspace", toggle down/make your select

**Comment by coleoo** [comment]
> > Hi,
> > I am new to VS Code so sorry for dummy question.
> > What if for learning purposes I have a few different folders with the same structure inside with different lessons (versions of the sites) and I need to switch from one to another inside the same Workspace? Let's say I opened one index.html inside one of the folders inside root of my Workspace and launched it with the Live Server. Then I need to go to another folder inside my Workspace root and to open another index.html inside that separate folder. I open it up in the Live Server but there is still the previous site version opened again.
> > Is there a way to set it up in the way that it would open up the files from the currently selected folder inside my Workspace (from the folder where currently active file is located in and its subfolders)?
> 
> I know I'm late, but I just figured this out. Go to the index.html file you want to launch and right-click on it, then choose "Open with Live Server". Remember to close the server first if it's already running from a different html file.

Thank you! Seriously easiest work around here. You just made this headache go away
