### ISSUE TITLE
Seeing CPU Spike for code helper once clicking go live

### ISSUE THREAD

**Issue by AnthonyMichaelc** [ritwickdey/vscode-live-server#34]
Code helper cpu % goes from a calm idle to 140-160%

- Running latest vscode on Mac OS High Sierra.

- Seeing this on both a laravel and node js project.

- turn off the extension and cpu drops immediately

- vscode without using live server does not use much resources

**Comment by ritwickdey** [comment]
This issue seems like https://github.com/ritwickdey/vscode-live-server/issues/26

A TEST (I don't have MAC, so I need your feedback) : 

Create a simple HTML project
And start the live server and check cpu usages .

**Comment by ritwickdey** [comment]
If you want to help in regarding this issue @bestvow.

**Comment by bestvow** [comment]
ok I will solve this problem

**Comment by bestvow** [comment]
Please tell me your live server version.
![image](https://user-images.githubusercontent.com/24888709/31995051-77ed26bc-b9b5-11e7-8f83-b2f71058a077.png)

**Comment by AnthonyMichaelc** [comment]
I tested the plain html file and the cpu usage stayed normal low usage. It seems to have been only on projects utilizing laravel and node js for me. 

As for my version of live server extension I currently have 3.0.0 as that is the latest one I see in the extensions market tab.

I attempted a laravel and node project and while the usage decreased, it went from 140-160 to 16-130. If there was an update pushed out, I may not have access to it cause there was no updates when I opened code.

**Comment by ritwickdey** [comment]
Ok! Try a settings 

```js
"liveServer.settings.NoBrowser" : true,
"liveServer.settings.ignoreFiles": [
          "*",
          "**"
 ] 
```
[NOTE : IT WILL DISABLE LIVE RELOAD.]

Now what about the CPU usage?

if it works, now for Node.JS project, try this
```
"liveServer.settings.ignoreFiles": [
          "**/node_modules/**"
 ] 
```
Is this works for Node.js ? (Though I excluded this folder from https://github.com/ritwickdey/vscode-live-server/commit/b9cdc1331470e1c2d4334bbf924dbd32190e3753 ), just give a try and let me know.

**Comment by ritwickdey** [comment]
...And,  where all the dependencies for laravel project are stored (by composer package manager) ? [I DON'T KNOW]

```
"liveServer.settings.ignoreFiles": [
          "**/<THE FOLDER NAME>/**"
 ] 
```

Give a try this also.

**Comment by bestvow** [comment]
Manual ignore the file that you don't need to live reload , such as `node_modules` folder.
About to your PHP project , you can analyze the project dependencies file and ignore it.
Most possible lead to overload your cpu may the laravel frame file.
(Sorry for my terrible english syntax)

**Comment by AnthonyMichaelc** [comment]
I have tried implementing your settings and still it is staying around 140 to 150. Tried ignoring just about every folder/file as well.

**Comment by rjoydip** [comment]
@bestvow Please try with newly released version. I have check code helper in a node.js project. It's working fine here. I am closing this issue if you faced the same issue with the latest version reopen it. Thank you

**Comment by drabastomek** [comment]
Still an issue on mac on 6/1/21
