### ISSUE TITLE
live server issue

### ISSUE THREAD

**Issue by anshul0430** [ritwickdey/vscode-live-server#36]
How can I open liverServer.settings.port 
Whenever i go live on a particular HTML file it goes to some directory that i don't know.
![l](https://user-images.githubusercontent.com/30527706/32208395-4b143942-be28-11e7-9cf6-0866cca06c32.jpg)

**Comment by ritwickdey** [comment]
Sorry, I don't get that... Can you explain further more?

**Comment by ritwickdey** [comment]
New Address #37
