### ISSUE TITLE
live server issue

### ISSUE THREAD

**Issue by anshul0430** [ritwickdey/vscode-live-server#37]
![screenshot 2017-10-31 10 57 09](https://user-images.githubusercontent.com/30527706/32208807-faccb9ac-be2a-11e7-85f6-c1f649fa30fe.png)
![screenshot 2017-10-31 10 57 17](https://user-images.githubusercontent.com/30527706/32208816-0056758e-be2b-11e7-82de-8f095850f0ed.png)
![screenshot 2017-10-31 10 57 23](https://user-images.githubusercontent.com/30527706/32208819-05b8c93c-be2b-11e7-91db-a9aa25921c2d.png)
![screenshot 2017-10-31 10 57 30](https://user-images.githubusercontent.com/30527706/32208822-08e4fe32-be2b-11e7-98a1-9b3ed61043bb.png)
First i open my html file.
click on live
opens 5500
but my html file is not there .Whenever i click on live it goes to same location . I dont know what to do.

**Comment by ritwickdey** [comment]
Can you give me a screenshot of your Work space files?

**Comment by ritwickdey** [comment]
* I am not sure, is the `.html` in your workspace or not? 

* Are you new in vscode?

**Comment by anshul0430** [comment]
yes i am new in vscode.
I dont know what is workspace.

**Comment by anshul0430** [comment]
![screenshot 2017-10-31 11 09 34](https://user-images.githubusercontent.com/30527706/32209112-8d675078-be2c-11e7-958f-37180e2f0a2d.png)

**Comment by ritwickdey** [comment]
don't drag and drop the the `index.html` to your Vscode.

From vscode, File -> Open Folder -> select the folder where you've the `index.html`.

or,

From the file explorer, open CMD and type `code .`  (in the same location of the `index.html`)

**Comment by anshul0430** [comment]
thanks brother. 
i love this

**Comment by ritwickdey** [comment]
Is the issue solved?

**Comment by anshul0430** [comment]
yes

**Comment by ritwickdey** [comment]
If you like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).

**Comment by hillarion99** [comment]
m
