### ISSUE TITLE
Basic Routing

### ISSUE THREAD

**Issue by BinaryBen** [ritwickdey/vscode-live-server#39]
Replicating ritwickdey/live-server-web-extension#5 as I originally created it in the wrong repo:

> If I were to use this to develop a SPA, I would need to be able to ensure all routes are redirected to index.html (unless the file otherwise exists, i.e. for stylesheets and js files). Then I can use something like page.js (or whatever framework is the flavour of the month) to handle routing.

**Comment by rjoydip** [comment]
These issue can be solved with new release. Please install latest version of live-server. Fell free to reopen it if get same issue. Thanks
