### ISSUE TITLE
Can't open Chromium in -app mode using LiveServer.settings.AdvanceCustomBrowserCmdLine

### ISSUE THREAD

**Issue by David-Else** [ritwickdey/vscode-live-server#393]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[x ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

(I also have `"liveServer.settings.ChromeDebuggingAttachment": true`,)

try adding `-app` to `"liveServer.settings.AdvanceCustomBrowserCmdLine": "/usr/bin/chromium-browser --remote-debugging-port=9222"` and browser fails to open with no error
## Expected behavior
it opens in app mode as it does on the command line with `/usr/bin/chromium-browser -app=https://www.google.com `

## Environment

```html
Browser:

- [x] Chromium (desktop) version 71

For Tooling issues:

- Live Server: 5.5.1
- Platform:  Linux
- Visual Studio Code: 1.32.3
```

## Others
The syntax demands `-app=URL` , how can this be done using AdvanceCustomBrowserCmdLine?

I just want to get rid of the URL bar from Chromium for screencasting by using app mode, but I can't get it to open using live server. The following feature was dropped and I can't find a better solution:

https://www.howtogeek.com/93995/how-to-auto-hide-the-address-bar-in-google-chrome-and-chromium/

**Comment by David-Else** [comment]
Closing due to being ignored for 8 months.

**Comment by Kovinda** [comment]
@David-Else 
I'd really like to have this as a feature of live server as well

**Comment by Kovinda** [comment]
You could use it like this :

AdvanceCustomBrowserCmdLine": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe --remote-debugging-port=9222 --disable-extensions --app=http://127.0.0.1:5500/"

Although you'll have to navigate to the file
