### ISSUE TITLE
live server ' freezes' after update vscode 1.18

### ISSUE THREAD

**Issue by Dalstam** [ritwickdey/vscode-live-server#40]
HI,

Love the live server. The best preview option for vscode. Only after the latest update of vscode, the server freezes. It happens after 2 or three times I save a file. I also can't stop the server and need to close vs code and choose an other port. Because the original one is occupied.

I am working with windows 10.

Do you know about this issue?

thnx Daniel

**Comment by ritwickdey** [comment]
_[Live server is not supported multi-workspace]_

I am using Windows 10, it is working for me.

> the server freezes
anyway, what do you mean by `freezes` ?  What is actually happening ?


> I also can't stop the server and need to close vs code and choose an other port
Can you send me the snapshot of console of Developer Tool (Help -> toggle Developer Tool) when it is happening ?

**Comment by ritwickdey** [comment]
Sorry for the late. It has been 6 days. So, in this duration have you face the same issue?

**Comment by cycle4passion** [comment]
Yes still having the issue

**Comment by d8vjork** [comment]
I've the same issue of @cycle4passion

**Comment by rjoydip** [comment]
@Dalstam Can you please try with update version?

**Comment by rjoydip** [comment]
I am closing this issue reopen it if this issue arises again. Thank you for reporting.
