### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mrahdreegez** [ritwickdey/vscode-live-server#406]
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.5.1`
- OS Version: `Linux x64 5.0.5-200.fc29.x86_64`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/pc-2/ritwickdey.LiveServer-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mrahdreegez** [comment]
[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/3050840/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)

**Comment by ritwickdey** [comment]
When you're getting this issue? after load of vscode or after clicking to Go Live ?

Is this happen every-time ? or random ?

Please reply here https://github.com/ritwickdey/vscode-live-server/issues/278

Duplicate of https://github.com/ritwickdey/vscode-live-server/issues/278
