### ISSUE TITLE
Browser page up(move to the top) after update.

### ISSUE THREAD

**Issue by claudiney** [ritwickdey/vscode-live-server#41]
Hi there.
 
Every time i save the css file, the browser update and page up to the top, losing focus of editing area. E.g. i'm working on the footer, save the css file and the browser move to the top.
I'm using no settings.json configuration file.
Probably there is something wrong in my side, but i don't know where it is. 

Thanks.

My setup: Windows 10, VS Code 1.18

**Comment by ritwickdey** [comment]
Have you installed Live Server Web Extension?

**Comment by ritwickdey** [comment]
If yes, turn it off!

**Comment by claudiney** [comment]
HI.
No, i didn't, I'm working on pure html and css.

**Comment by claudiney** [comment]
When i change the html, the page don't move, just the css change cause page up.

I tried to uninstall VS Code(erase config files too) and Live Server, but the problem continues.

**Comment by ritwickdey** [comment]
It may be a bug! Have you tried anyother project? Or you have said 'after update', if you install previous version of vscode, is this working?

**Comment by ritwickdey** [comment]
If it is not any sensitive content, can you send me the project (or a fake project where you're facing the same issue)?

**Comment by ritwickdey** [comment]
One tips for now (if it's a bug):

- Install Live Sever Web Extension (for chrome/firefox).
- set the settings : liveServer.settings.useWevExt : true & start the server & copy the address.
-  Open Live Sever Web Extension setup (popup menu)
- Click to live reload & paste the address into 'actual server address' & 'live server address' (same value).

**Comment by claudiney** [comment]
Yes, i tried many different projects and the problem persist.
I'm not going to send the project, because the files are just for testing(regular html and css)

Gulp + browsersync are running ok here. Let me do some tests

**Comment by ritwickdey** [comment]
Hi @claudiney, Today I faced the same issue what you've mentioned here. 

This issue is comes from Library as handling CSS update is different from other files(HTML/JS). If you noticed, when you've changed the CSS, browser never reload the whole page  it just re-render the CSS. 

There should be a settings to fix this kind of issue (Enforce browser is reload whole page instead of re-rendering CSS).

* Workaround:
   - Use Live Server with [Live Server Web Extension](https://github.com/ritwickdey/live-server-web-extension).

> [Seriously, it is not big deal, but I am sorry, I can't update the extension right now - I am really busy for my exam]

**Comment by claudiney** [comment]
Good luck @ritwickdey.

**Comment by ritwickdey** [comment]
This features is already added in v3.1.0.  (Sorry, I forget to close it)

**Comment by cwgabel** [comment]
I had this issue and found that by disabling the chrome extension [Dark Mode](https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj), the problem went away.

I added my test domain http://127.0.0.1:8080 to the Dark Mode extension's exclude list which did ignore this domain for dark mode switching,  but this error on live-server continued to occur.
