### ISSUE TITLE
live-server array issue?

### ISSUE THREAD

**Issue by srj-github** [ritwickdey/vscode-live-server#419]
## I'm submitting a  Bug report 

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

When I run the below code through live server I get the 'tasks.push is not a function' and 'tasks.forEach is not a function' errors.

> The tasks variable is not seen as a javascript object as it should be.

Not sure if this is a problem with live server, but I assume so, because if I open the file directly in the browser, it's working as expected.

```javascript
document.querySelector('form').addEventListener('submit', function(e) {
  const task = document.getElementById('task').value;

  let tasks;

  if (localStorage.getItem('tasks') === null) {
    tasks = [];
  } else {
    tasks = JSON.parse(localStorage.getItem('tasks'));
  }

  tasks.push(task);

  localStorage.setItem('tasks', JSON.stringify(tasks));

  alert('Task saved');

  e.preventDefault();
});

const tasks = JSON.parse(localStorage.getItem('tasks'));

tasks.forEach(function(task) {
  console.log(task);
});

```

## Expected behavior

To see variable tasks as a javascript object

## Environment

```html
Browser:

- [ x] Chrome (desktop) version (latest)
- [ x] Firefox version (latest)
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 5.5.1
- Platform:  Windows 10
- Visual Studio Code: 1.33.1
```

**Comment by srj-github** [comment]
The variable '**tasks**' is set as an '**object**' when running from my 'real' webserver or by opening the file directly in the browser.
When running in virtual-server is's set as '**string**'.

Perhaps something is wrong with **JSON.parse** ?

**Comment by srj-github** [comment]
It's working fine if I pass localhost:5500.

**Not working** with 127.0.0.1:5500

**Comment by ritwickdey** [comment]
`localStorage.getItem('tasks')` is not an array in your `localhost`
