### ISSUE TITLE
Multi-root Workspace support

### ISSUE THREAD

**Issue by mpower02** [ritwickdey/vscode-live-server#43]
When running multi-root workspaces with 2 or more folders, launching Live Server would only display files from the 1st folder.  How can we access the other folder directory to view a file?

**Comment by ritwickdey** [comment]
As of now, Multi root is not supported.

[May be I've to work more for enabling multi root feature - BUT I AM TOTALLY BUSY DUE TO MY EXAM]

**Comment by dsjolie** [comment]
Quick workaround: Go to workspace settings and quickly reorder the folders using Alt-[Up/Down] to move the lines. This way you can quickly select another of your worspace folders to be the active one for Live Server.

PS I'm a newbie in Visual Studio Code so feel free to suggest an even quicker way to do this. I.e., a macro to move the current folder to be the first folder?

**Comment by doogood** [comment]
I realized what the problem was. Changed the order and now everything works :) Thanks!

**Comment by ritwickdey** [comment]
This feature is added in LiveServer 5.0.0. Please update the extension. Sorry for late

**Comment by PeterChen1997** [comment]
It's still doesn't work in multi root project bro ... my version is 5.1.1

**Comment by kirankumardash1** [comment]
I am using 5.5.0 and it still not working

**Comment by nelsonr** [comment]
The README says "Multi-root workspace supported." but it doesn't seem to work yet.

**Comment by BulegaHassan** [comment]
Mr @ritwickdey am using 5.7.4 but does not work.

**Comment by softbby666** [comment]
July 11 2022 and still does not suport multi-root workspaces :( the only temporary solution is to reorder the folders to open the actual file you are working with.

**Comment by nikoscham** [comment]
Any news regarding the multi-root workspaces support? Thanks!
