### ISSUE TITLE
Extension host terminated unexpectedly. v5.6.0

### ISSUE THREAD

**Issue by tiansin** [ritwickdey/vscode-live-server#431]
@ritwickdey 
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/mypc/.vscode/extensions/ritwickdey.liveserver-5.6.0/node_modules/vscode-fsevents/build/Release/fse.node
  Expected in: flat namespace

**Comment by skourismanolis** [comment]
Happens to me as well, installed previous version (5.5.1) and it worked fine. I'm on Mac OS 10.13.6

**Comment by ritwickdey** [comment]
Thanks you for the report. Please give me few min.

**Comment by ganapativs** [comment]
Same here.

**Comment by ritwickdey** [comment]
Hi, Is this working ? https://github.com/ritwickdey/vscode-live-server/releases/download/v5.6.0/LiveServer-v5.6.0-osx.modifed.vsix

Please download the file and try to install manually

**Comment by skourismanolis** [comment]
same issue, "extension host quit unexpectedly"
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/USERNAME/.vscode/extensions/ritwickdey.liveserver-5.6.0/node_modules/vscode-fsevents/build/Release/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/USERNAME/.vscode/extensions/ritwickdey.liveserver-5.6.0/node_modules/vscode-fsevents/build/Release/fse.node
  Expected in: flat namespace
```

**Comment by ganapativs** [comment]
> Hi, Is this working ? https://github.com/ritwickdey/vscode-live-server/releases/download/v5.6.0/LiveServer-v5.6.0-osx.modifed.vsix
> 
> Please download the file and try to install manually

Still same error.

**Comment by ritwickdey** [comment]
Okk.. Thank you.. For now revert backing the build

**Comment by ddiu8081** [comment]
same error here.

**Comment by ritwickdey** [comment]
Hi. please one more try

1. https://github.com/ritwickdey/vscode-live-server/releases/download/v5.6.1/LiveServer-v5.6.1-osx.modified.vsix

2. https://github.com/ritwickdey/vscode-live-server/releases/download/v5.6.1/LiveServer-v5.6.1-osx.vsix

One of them should work

**Comment by ritwickdey** [comment]
I don't have macbook or mac. I'm sorry. That is why I'm unable to catch the error before deployment. I just made few assumption and trying to fix it.

**Comment by MattyBurton** [comment]
how do I manually install?

**Comment by ritwickdey** [comment]
Install from `vsix`
![image](https://user-images.githubusercontent.com/18099464/56281202-a7e70780-6129-11e9-9b5c-024763de08b1.png)

**Comment by MattyBurton** [comment]
thank you for that seems to be working :)

**Comment by ritwickdey** [comment]
Which one is working? have yoi tried both? 

please let me know? i will deploy the build in production

**Comment by MattyBurton** [comment]
This one 
 https://github.com/ritwickdey/vscode-live-server/releases/download/v5.6.0/LiveServer-v5.6.0-osx.modifed.vsix

**Comment by skourismanolis** [comment]
> Hi. please one more try
> 
>     1. https://github.com/ritwickdey/vscode-live-server/releases/download/v5.6.1/LiveServer-v5.6.1-osx.modified.vsix
> 
>     2. https://github.com/ritwickdey/vscode-live-server/releases/download/v5.6.1/LiveServer-v5.6.1-osx.vsix
> 
> 
> One of them should work

Both work perfectly for me, quick note, I tried no. 1 first and got a notification for the new stuff in version 5.6.x. After, I uninstalled, tried no. 2 and didn't get the notification. SO I'm not sure if there was an issue with the notification that broke the extension host or not.

**Comment by ritwickdey** [comment]
That's okay. because it checks that the msg is already shown or not...

**Comment by ritwickdey** [comment]
New version is published. Please try to install from store. It should work. If not, please let me know

**Comment by juanguerra079** [comment]
![image](https://user-images.githubusercontent.com/38590411/74797184-23589e80-5290-11ea-9211-4bd5dad239ee.png)
Alguien puede Ayudarme, cuando quiero ejecutar Live Server me da este error 
Can someone help me, when I want to run Live Server I get this error

**Comment by Nasren1988** [comment]
this is not work to me

**Comment by JoeEL1506** [comment]
The live server extension keeps Disable itself from my extensions once I quit or minimize the VsCode
