### ISSUE TITLE
Visual studio code When i install live server i am prompted with this message 'Extension host terminated unexpectedly'

### ISSUE THREAD

**Issue by MattyBurton** [ritwickdey/vscode-live-server#432]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

I have searched around for a while now and have not found the solution to my issue. I keep getting this message "Extension host terminated unexpectedly". Every time I enable live server I have tried installing an older version of live server v4.0 I stop getting the message but then live server does not auto update any idea?

## Expected behavior

Live Server to operate properly

## Environment

```html
Browser:

- [ X] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: v5.6.0 
- Platform: Mac
- Visual Studio Code: 1.33.1
```

## Others
When I open developer tools this is what is display?

![When I open developer tools this is what is display?](https://user-images.githubusercontent.com/46603982/56280410-0a2c1200-6102-11e9-8d27-ea79df0279a6.png)

**Comment by ritwickdey** [comment]
Thank you for report. Issue tracking #431
