### ISSUE TITLE
showing this error in vscode live server

### ISSUE THREAD

**Issue by amrutsawant** [ritwickdey/vscode-live-server#44]
![untitle](https://user-images.githubusercontent.com/21061040/32984438-a4046308-cccc-11e7-9283-2ff1dfd7edf3.png)

**Comment by ritwickdey** [comment]
Can you show to your settings for live server?

**Comment by elvis1** [comment]
HI @ritwickdey  what am I doing wrong ?

![qshuusp 1](https://user-images.githubusercontent.com/706946/35178189-221deb6a-fd65-11e7-9e25-f5e0eaed5af0.png)

Regards

**Comment by ritwickdey** [comment]
Hi, @elvis1, Sorry for late! 

Make sure `5500` is not used by other application. Try to set any other port number (set 0 if you want random port)


All the setting are listed here : https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

Another thing I've noticed. You wrote wrong way 'CustomBrowser' setting.  There is no space in between `firefox --remote...`  and you've entered new line in between json key value pair.

**Comment by mxschmitt** [comment]
@elvis1 
I'm closing this for now. Feel free to tag me if you have any issues and I will reopen this.
