### ISSUE TITLE
Using Chromium and Chrome Debugger On Linux

### ISSUE THREAD

**Issue by David-Else** [ritwickdey/vscode-live-server#45]
UPDATE! I got your extension to open Chromium OK and connect to the debugger :):

Maybe you could comment if I did this the best way, and also if there is a way for the Chromium tab to close when the live-server connection is closed? THANKS.

```
"liveServer.settings.AdvanceCustomBrowserCmdLine": "/usr/bin/chromium-browser --remote-debugging-port=9222"
```
```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Attach",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "url": "http://127.0.0.1:5500/",
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

Hello,

I am trying to use live-server and chrome debugger on Linux with Chromium. If I want to use Chromium rather than Chrome in the debugger my settings used to look something like:

```
{
    "version": "0.2.0",
    "configurations": [{
        "type": "chrome",
        "runtimeExecutable": "/usr/bin/chromium-browser",
        "runtimeArgs": [
            "--remote-debugging-port=9222"
        ],
        "request": "launch",
        "name": "Chromium against localhost",
        "url": "http://localhost:8080",
        "webRoot": "${workspaceRoot}",
        "sourceMaps": false,
        "smartStep": false
    }]
}
```
but in live server when I try to make it open changing the preferences to:
```
"liveServer.settings.ChromeDebuggingAttachment": true,
"liveServer.settings.CustomBrowser": "chrome",
```

then nothing happens as live-server can't know to open Chromium.

Can you add an option for Chromium, or is there something I can do? If I type 'chromium' on my command line it does not run at the moment as it's not in the PATH. I can fix that if needed, but being able to point to the executable in your extension could be cool too.

Cheers!

**Comment by ritwickdey** [comment]
Thanks for posing your confusion. I am sorry, I did not able to answer quickly.

[Seriously I'm now busy for my exam. In case your is resolved, you can close the issue, if not, free feel to ask me]

**Comment by David-Else** [comment]
Good luck with the exam! I won't disturb you further...

**Comment by ritwickdey** [comment]
No no... I feel happy to help others :) ....

**Comment by DzenetanMassart** [comment]
So... and now, can we use Live Server with Chromium?

**Comment by David-Else** [comment]
@DzenetanMassart Yes, I have been using it for ages on Fedora. In VS Code settings I have:

```
"liveServer.settings.ChromeDebuggingAttachment": true,
"liveServer.settings.AdvanceCustomBrowserCmdLine": "/usr/bin/chromium-browser --remote-debugging-port=9222",
```
