### ISSUE TITLE
extensions crash

### ISSUE THREAD

**Issue by Anonymous11351** [ritwickdey/vscode-live-server#451]
![Screenshot (10)](https://user-images.githubusercontent.com/47074649/56731293-ffc7d480-670e-11e9-8160-54b4133bc0ec.png)
![Screenshot (10)](https://user-images.githubusercontent.com/47074649/56731298-035b5b80-670f-11e9-9504-461004490d0b.png)

Issue Type: <b>Bug</b>

every time I use the @import the extensions crash "Restart host "  Live Server Emmit Sass Compiler.  Steps to the issue -> Use @import 

Extension version: 5.6.1
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.97GB (6.51GB free)|
|Process Argv|C:\Users\Administrator\Desktop\Natours|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Icesofty** [comment]
@Anonymous11351 Hi, you closed this issue but can you explain how you resolve this? Thanks
