### ISSUE TITLE
Live Server does not wortk

### ISSUE THREAD

**Issue by livia7916** [ritwickdey/vscode-live-server#456]
It's been happening for about a month. I can't open live server on command (alt+L, alt +O). It doesn't show on bottom of task bar.  I restart Visual Code more than twice to get live server to start. Also when I right-clikc, the live server option is not stated/ its not an option. Please help me solve this issue. I am wasting valuable time trying to find a solution. 
Thank you.

**Comment by DariaShvakh** [comment]
After upgrading to 5.6.1
I have the same problem
Go Live button is missing

**Comment by ritwickdey** [comment]
If you do uninstall & install?

**Comment by ritwickdey** [comment]
or if you delete live server folder from

C:\Users\<USERNAME>\extensions\ritwickdey.liveserver-5.6.1\

**Comment by DariaShvakh** [comment]
Ritwickdey !!! 
thank!!!
It all worked!!!

**Comment by markrazorx** [comment]
In mine the live server launches **outside** Visual studio? Also it does not run my index.php file. Was this only meant for html files?

**Comment by livia7916** [comment]
I am confused. So I uninstalled and reinstalled live server at Visual Code. Nothing happened. The only error-- Open a folder or workspace (File-->Open  Folder).
I am going to try to delete from C: Users now. I'll give you an update.
Also is live server only meant for HTML's only? I'm in the process of learning Javascript and it requires Live Server as per my tutorial.

**Comment by livia7916** [comment]
So I checked for live server in the C drive: users, etc... There is no live server extension. But this is installed in Visual code. What did I do wrong? Please advise.

**Comment by ritwickdey** [comment]
Live Server is static files (Means HTML, CSS & JS).... (yaa it supports php, but that needs different configurations. Check for 'Live Server Browser Extension' 


@livia7916 can you please share a screenshot of the directory?

**Comment by livia7916** [comment]
![image](https://user-images.githubusercontent.com/50123304/56972396-e7a1ec00-6b38-11e9-87f3-6e20b3cbd01d.png)

![image](https://user-images.githubusercontent.com/50123304/56972421-f4bedb00-6b38-11e9-9033-ff32e23f9569.png)

**Comment by ritwickdey** [comment]
C:\Users\<YOUR_USERNAME>\extensions\ritwickdey.liveserver-5.6.1

**Comment by livia7916** [comment]
I do not have -- \extensions\ritwickdey.liveserver-5.6.1 in my C drive.

**Comment by livia7916** [comment]
Should I delete Microsoft Visual Code and reinstall? What is your advice?

**Comment by ritwickdey** [comment]
yaa.. You can. meanwhile you can take a look into it https://www.google.com/search?q=windows+user+directory&oq=windows+user+direc&aqs=chrome.1.69i57j0l3.9785j0j9&client=ms-android-xiaomi&sourceid=chrome-mobile&ie=UTF-8

**Comment by livia7916** [comment]
Hi 
I uninstall and reinstall Microsoft Visual Code and there's still no LIVE SERVER. What is the next step?
Thank you for your patience I am a newbie.

**Comment by livia7916** [comment]
![image](https://user-images.githubusercontent.com/50123304/56980379-32782f80-6b4a-11e9-8703-7c36ccdc985b.png)

![image](https://user-images.githubusercontent.com/50123304/56980406-4459d280-6b4a-11e9-8623-db7f145fb126.png)

**Comment by livia7916** [comment]
OK so I restart and followed the open a folder. And the GO LIVE button is on the bottom task bar. But when I open file and it does not show in browser as you can see. What am I doing wrong?

![image](https://user-images.githubusercontent.com/50123304/56980835-699b1080-6b4b-11e9-98b5-211180b4de40.png)

**Comment by livia7916** [comment]
FINALLY FIGURED OUT MY ERROR. Thanks you.

**Comment by kevwinstanley** [comment]
I cant delete ritwickdey.liveserver-5.6.1 it won't let me
