### ISSUE TITLE
Is there anyway to set delay before reload?

### ISSUE THREAD

**Issue by justforuse** [ritwickdey/vscode-live-server#49]
Awesome plugin!
I face a problem,  I use webpack to generate js file, and the html use its budled js. but I find I should reload twice to see the changes, I think live-server reload when bundle.js deleted. Is there anyway to set delay before reload? like 1s. 
Thanks a lot.

**Comment by ritwickdey** [comment]
Thank You for the suggestion. For now, it is not possible but definitely it'll come after December ( - may be it is not a big deal as this feature is able in library but sorry! I am really busy due to exam)

**Comment by ritwickdey** [comment]
This features is already added in v3.1.0.  (Sorry, I forget to close it)

**Comment by justforuse** [comment]
@ritwickdey Nice!
