### ISSUE TITLE
Enable setting of launch switches on the browser

### ISSUE THREAD

**Issue by obkalu** [ritwickdey/vscode-live-server#5]
Hi there,

I commend your effort on creating this v nice/useful extension. Hey, can you consider allowing users to set launch switches on the custom browser setting? i.e. "liveServer.settings.CustomBrowser": "chrome --remote-debugging-port=9222". This will add further usefulness, as it will now also enable chrome debugging from within VSCode via attaching to the running Chrome browser (as supported by the VS Code debugger for Chrome). What do you think?

**Comment by ritwickdey** [comment]
okay! I'm looking for it. :)

**Comment by ritwickdey** [comment]
Hi, I added a new settings `"liveServer.settings.ChromeDebuggingAttachment: true"`. When it is `true`, you don't have to open a new window for debugging. You have to choose `Attach to Chrome` from debugging window. And `Debugger For Chrome` will do rest of the work, it will inject debugging feature into same instance.

Did you mean that exactly?

Anyway, I've not pushed the feature to VS Code Marketplace. First, let me know, if you meant that or not.

BTW, A LOT OF THANKS AGAIN FOR THE SUGGESTION :)

**Comment by ritwickdey** [comment]
Hi, I don't get any further response from you. So, I've pushed the update to Marketplace and for now, I am closing the issue. If you've more suggestion or if you en-count any bug, feel free to suggest/report me :)

**Comment by obkalu** [comment]
Hi RitwickDey,
Thanks for your super-fast response. Wow, you operate on lightning-speed; that's awesome 👍 So, I have seen the update/fix which you deployed to marketplace and hv tested/tried it out. The new setting you've added, i.e. "liveServer.settings.ChromeDebuggingAttachment: true/false", doesn't seem to make much of a difference to the way the extension operates. For example, even if I set it to false, I am still able to launch VSCode Debugger for Chrome to attach to a running Chrome browser. The only issue here is that, I have to open a new Chrome browser window, running Chrome Canary (not the regular, mainstream Chrome, which your extension launches). Why I use Canary is because, unfortunately, the 'Debugger for Chrome' doesn't seem to work with regular Chrome. Also, interestingly, vscode-live-server still works with the Chrome Canary browser window, which I manually launch open (using cmdline as c:\>chromecan --remote-debugging-port=9222. Here is what I suggest, instead of adding the new setting, rather, fully use the already existing setting you have provided for user to enter any CustomBrowser cmd string, including switches if they need. i.e. "liveServer.settings.CustomBrowser": "chrome --remote-debugging-port=9222" or "liveServer.settings.CustomBrowser": "chromecan --remote-debugging-port=9222" or "liveServer.settings.CustomBrowser": "chrome --headless" or "liveServer.settings.CustomBrowser": "firefox --remote-debugging-port=9001" or "liveServer.settings.CustomBrowser": "edge --frameset=off" etc. Do you get the idea? What do you think? Once again, thanks for your great work. Sorry this is too long. :)

**Comment by ritwickdey** [comment]
Okay! I understand!..

But that are all advance settings. I don't want any beginners face any trouble to setup vscode-live-server as chrome has different naming in difference platform.

Example : Windows : chrome, Linux : Google-Chrome, Mac : Google Chrome.

So, I give Enum (chrome,firefox) and I handled that by code base on environment. I thought begginger may have face problem while setting up default browser. (I am not also PRO, it has been 1.5 years that I started programming).

I'm thinking now, if I make an other settings, that'll accept full qualified line (ie chromecan --remote-debugging-port=9222) and that'll also override the other two settings.

What about it?

**Comment by obkalu** [comment]
Great, you got it, man! :)
And you're right; it will be an advanced setting. For experienced developer using VS Code and want live-server-reloading using this extension, that will be just perfect. That way, they can specify a customized string as value of the setting, for the extension to just launch it. Hopefully, they know what they're doing :) Though, for the extension, it just assumes the person has entered a valid/correct browser startup command string. If it cannot launch the cmd, it just shows an error (e.g. Error: Your custom browser cmd, "chromecan --remote-debugging-port=9222" could not be launched. Please check your custom browser setting"). So, your proposed solution sounds good! Thanks again for your great work, mate. Btw, wow, 1.5 years. You're doing great, man. Have fun! 👍 It's a great time to be alive as a programmer.

**Comment by ritwickdey** [comment]
I have published a new version with the feature :) . Let me know if you like that or not! :D 

For now, I'm closing the issue :)

**Comment by obkalu** [comment]
Looks good!
Thanks dude.

**Comment by amrutsawant** [comment]
showing this error plzz help me
![untitle](https://user-images.githubusercontent.com/21061040/32984433-7cd082bc-cccc-11e7-966b-2bf6cecc5e36.png)

**Comment by ritwickdey** [comment]
Hi amrutsawant, can you show me the settings?

**Comment by ritwickdey** [comment]
Hi @amrutsawant, thanks for opening new issue request! All the conversion regarding your issue will be made here #44
