### ISSUE TITLE
browsersync browser not open..

### ISSUE THREAD

**Issue by amrutsawant** [ritwickdey/vscode-live-server#50]
[12:43:47] Starting 'js'...
[12:43:47] Starting 'sass'...
[12:43:47] Starting 'fa'...
[12:43:47] Starting 'fonts'...
[12:43:47] Finished 'fa' after 232 ms
[12:43:47] Finished 'js' after 317 ms
[12:43:48] Finished 'fonts' after 502 ms
[12:43:49] Finished 'sass' after 1.51 s
[12:43:49] Starting 'serve'...
[12:43:49] Finished 'serve' after 139 ms
[12:43:49] Starting 'default'...
[12:43:49] Finished 'default' after 40 μs
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:8080
    External: http://192.168.1.101:8080
 --------------------------------------
          UI: http://localhost:8081
 UI External: http://192.168.1.101:8081
 --------------------------------------
[Browsersync] Serving files from: ./src

browser not open... 

when i made changes

**
     * Decide which URL to open automatically when Browsersync starts. Defaults to "local" if none set.
     * Can be `true`, `local`, `external`, `ui`, `ui-external`, `tunnel` or `false`
     * @property open
     * @type Boolean|String
     * @default true
     */
    open: ""local",

TO

**
     * Decide which URL to open automatically when Browsersync starts. Defaults to "local" if none set.
     * Can be `true`, `local`, `external`, `ui`, `ui-external`, `tunnel` or `false`
     * @property open
     * @type Boolean|String
     * @default true
     */
    open: false,

**Comment by ritwickdey** [comment]
Sorry! I don't get that. What is the issue? Please be specific!

**Comment by rjoydip** [comment]
@amrutsawant I think this is not related to vscode-live-server

**Comment by rjoydip** [comment]
I am closing this issue because this an invalid issue
