### ISSUE TITLE
Add browser support for Blisk

### ISSUE THREAD

**Issue by chill-fish** [ritwickdey/vscode-live-server#51]
https://blisk.io/

I am not affiliated with Blisk. 

I've been using it for a day and really appreciate it's features. It's a Chromium based app so there shouldn't be any compatibility issues.

**Comment by ritwickdey** [comment]
Ok! I'll add in next update! but you can still add it as default browser of live server though `liveServer.settings.AdvanceCustomBrowserCmdLine` settings.

Checkout the setting page: https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

Even in this settings you can give full path of executable `Blisk`. #31
