### ISSUE TITLE
Can I do a URL rewriting?

### ISSUE THREAD

**Issue by kenshinman** [ritwickdey/vscode-live-server#52]
Hi I am using this plugin and it has saved me a lot of troubles. Thanks.
I want to know if there is a way to do a URL rewriting so that my app can always be run through the index.html like .htaccess in apache server

**Comment by ritwickdey** [comment]
Sorry? What is URL rewriting? Are you talking about SPA?

**Comment by Mikael-Sundstrom** [comment]
No, you must run a server such as: xampp for example, to host the server script as .htaccess and php. However, it is possible to add live reload feature to the xampp app with this browser [add-on](https://github.com/ritwickdey/live-server-web-extension). It will work along with .htaccess on xampp.

**Comment by rjoydip** [comment]
@kenshinman I am closing this issue because of since long time didn't got any response from issue reporter.

**Comment by ritwickdey** [comment]
I think, url rewriting means handling 404 error. (For spa)

Checkout the settings page. There is now new settings called `file`... for handling 404 error

**Comment by rjoydip** [comment]
It could be file mount.

**Comment by marcodafonseca** [comment]
Typically URL Rewriting means just that. URL Rewriting. It's used a lot for making urls easier to read for users.

A simple, and probably most common example, would be for removing extensions from URLs. So, an "about" url could look something like this: "http://localhost:8080/about" which the URL Rewriter would change to "http://localhost:8080/about.html" in order for the correct file to be returned to the browser without requiring the input of the file extension in the address bar.

Is this possible to setup with this extension?

**Comment by marcodafonseca** [comment]
Nudge

**Comment by Romvnly-Gaming** [comment]
AGGRESSIVE NUDGE!

**Comment by mjprogramation** [comment]
Sorry for that late, but maybe you're talking about this: `liveServer.settings.file` (Path to the entry point file. Useful for SPA)

**Comment by marcodafonseca** [comment]
That will resolve the issue for SPA's however that won't resolve the scenario I highlighted three years ago. 

> Typically URL Rewriting means just that. URL Rewriting. It's used a lot for making urls easier to read for users.
> 
> A simple, and probably most common example, would be for removing extensions from URLs. So, an "about" url could look something like this: "http://localhost:8080/about" which the URL Rewriter would change to "http://localhost:8080/about.html" in order for the correct file to be returned to the browser without requiring the input of the file extension in the address bar.
> 
> Is this possible to setup with this extension?

**Comment by mjprogramation** [comment]
> Hi I am using this plugin and it has saved me a lot of troubles. Thanks.
> I want to know if there is a way to do a URL rewriting so that my app can always be run through the index.html like .htaccess in apache server

You said you want your app to run through the index.html, so you can do so by specifying the `liveserver.settings.file = index.html` And use a package for routing such as `react router dom`, if you’re using React.

**Comment by LadyDefile** [comment]
So, I'm going to resurrect this thread because it's something I was actually hoping to see and didn't. What the OP is talking about is URL Rewriting. URL Rewriting is when you can type "domain.com/index" instead of "domain.com/index.html". This is usually done in the '.htaccess' file of the website on an Apache2 server and would look something like this:

```
RewriteEngine on

RewriteCond %{REQUEST_FILENAME}.html -f
RewriteRule ^(.*?)/?$ /$1.html [L]
```
RewriteCond works like this
%{REQUEST_FILENAME} is the file address (i.e. /index)
The appended ".html" after that *adds* the html to turn "/index" into "/index.html"

RewriteRule just defines how to rewrite the the address using regex.

Essentially it says "if the file ./index doesn't exist but ./index.html does exist, get ./index.html instead".
This allows you to use links like "domain.com/index" instead of "domain.com/index.html"

**Comment by takkbbl** [comment]
> So, I'm going to resurrect this thread because it's something I was actually hoping to see and didn't. What the OP is talking about is URL Rewriting. URL Rewriting is when you can type "domain.com/index" instead of "domain.com/index.html". This is usually done in the '.htaccess' file of the website on an Apache2 server and would look something like this:
> 
> ```
> RewriteEngine on
> 
> RewriteCond %{REQUEST_FILENAME}.html -f
> RewriteRule ^(.*?)/?$ /$1.html [L]
> ```
> 
> RewriteCond works like this %{REQUEST_FILENAME} is the file address (i.e. /index) The appended ".html" after that _adds_ the html to turn "/index" into "/index.html"
> 
> RewriteRule just defines how to rewrite the the address using regex.
> 
> Essentially it says "if the file ./index doesn't exist but ./index.html does exist, get ./index.html instead". This allows you to use links like "domain.com/index" instead of "domain.com/index.html"

but that doesn't answer the question, does it?

**Comment by LadyDefile** [comment]
> but that doesn't answer the question, does it?

Obviously not. I'm clarifying what the OP and I were hoping to get an answer on because people were suggesting that OP meant "SPA", file mounting, handling 404, etc. My comment contributes to the topic, yours is just rude, argumentative, and also doesn't answer the question either. I feel like I should be giving you a slow clap for being so impressively arrogant and idiotic.

**Comment by Andrey-Svetlichny** [comment]
Up

**Comment by ShortTimeNoSee** [comment]
I achieved URL rewriting by adding the following configuration to `settings.json`

```
{
    "liveServer.settings.mount": [
        ["/about", "./about.html"],
        ["/vision", "./vision.html"],
        ["/issues", "./issues.html"],
        ["/contact", "./contact.html"],
        ["/ ", "./index.html"],
    ]
}
```

`Ctrl`-`,` to open settings, then press the 📄 icon near the top right to open the JSON. If you have any other configurations in settings, format it like so:
```
{
    "liveServer.settings.mount": [
        ["/about", "./about.html"],
        ["/vision", "./vision.html"],
        ["/issues", "./issues.html"],
        ["/contact", "./contact.html"],
        ["/ ", "./index.html"]
    ],
    "other.setting.configuration": true
}
```

The space in `"/ "` is required or else the CSS and JS for every page breaks except on the first page listed (in my case, `about.html`)
