### ISSUE TITLE
Is it possible to make the server available ouside?

### ISSUE THREAD

**Issue by Darksoulsong** [ritwickdey/vscode-live-server#53]
Is there any way to make Live Server available to other computers in my network? Supplying  a "0.0.0.0" setting, maybe?

**Comment by ritwickdey** [comment]
Actually, the server is binding 0.0.0.0 by default.. try out with your IP

 https://github.com/ritwickdey/vscode-live-server/blob/master/docs/faqs.md#how-to-access-the-server-from-mobile

**Comment by Darksoulsong** [comment]
Thanks for the reply. But I have another "node server" up in my PC and I can access it from outside, but can't do the same with Live Server. Is there any additional configuration I'm supposed to pass to it?

**Comment by ritwickdey** [comment]
No! you don't need any further configuration. 

Connect you mobile & PC on same WiFi.  Open terminal and try `ipconfig` (for Win) and `ifconfig` (Mac/Linux) to know your IPv4 address.

 Open mobile browser and try `http://ip-address:port`

**Comment by raselmahmudbd** [comment]
not working for me...my phone can not find address.does my phone need to change any setting or what?

**Comment by Jannis033** [comment]
So I have to be in the same network? If port forwarding (udp + tcp) is enabled for port 5500, I can't connect from another network...

**Comment by rjoydip** [comment]
@raselmahmudbd [PR:116](https://github.com/ritwickdey/vscode-live-server/pull/116) has been merged hopefully this feature will come soon.

**Comment by rjoydip** [comment]
I am closing this issue. This feature is now live on vscode marketplace. Please feel free to reopen if you faced any issue further
