### ISSUE TITLE
Error on port 5500

### ISSUE THREAD

**Issue by domjrobinson** [ritwickdey/vscode-live-server#54]
I've only been using vs code for about a week now. Just when I've started to get used to it I'm getting a error on port '5500 please change in settings' alert when I attempt to use the live server extension.

**Comment by ritwickdey** [comment]
Have you tried to change port ? 

https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

**Comment by Jsnurr** [comment]
How exactly do you change the setting? I'm new to VS Code.

**Comment by ritwickdey** [comment]
- Live Server FAQS:  https://github.com/ritwickdey/vscode-live-server/blob/master/docs/faqs.md#how-to-configure-the-settings-in-my-project

- Live Server settings : https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

> (official vscode docs : https://code.visualstudio.com/docs/getstarted/setting)

**Comment by ritwickdey** [comment]
Is the issue still there? 
Let me know if I can help further ?

**Comment by kapunahelewong** [comment]
Another option is to kill what's running on port 5500. 

At the command line:
`lsof -i :5500` <--tells you what's running on 5500, returning a PID (process ID).
`kill -9 ###` where `###` is the PID. 

Then go back into VSC and start Live Server again. Works for me.

**Comment by wcisco17** [comment]
Hey I'm having a problem, I tried changing the port to 0 and I'm still getting error's. I even tried to kill the running port on the command line and it's still not working. What should I do?

**Comment by thisLinda** [comment]
Same problem for me. Now what?

![lsof](https://user-images.githubusercontent.com/34631602/39639156-78e14f68-4f96-11e8-923c-78b110b59385.PNG)

**Comment by mxschmitt** [comment]
@thisLinda lsof is a command for Linux, not Windows. No clue how the command is on windows. Try to google with "windows netstat openend ports command"

**Comment by thisLinda** [comment]
aHa!!!!

Thank you. I'll continue searching.

**Comment by thisLinda** [comment]
Solved itself after I ran the VSC update.

**Comment by ritwickdey** [comment]
For Windows: (To kill 5500 Port)

> Run command-line as an Administrator.

`netstat -ano | findstr :5500`
`taskkill /PID typeyourPIDhere /F`


 Reference: https://stackoverflow.com/a/39633428/6120338

**Comment by Gennady-G** [comment]
> Have you tried to change port ?
> https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md
**ritwickdey**, thank You much!)

**Comment by arhoyFin** [comment]
@kapunahelewong thanks! I want to run two ports at same time though.

**Comment by LU-House** [comment]
Hello Guys, I changed my port Number of my Live Server to 0. However, it tells me Server is now offine after I run it. What should I do?

**Comment by LU-House** [comment]
> Hello Guys, I changed my port Number of my Live Server to 0. However, it tells me Server is now offine after I run it. What should I do?

Sorry, it's offline!

**Comment by LU-House** [comment]
![image](https://user-images.githubusercontent.com/60131103/91109521-2a84bd00-e6b6-11ea-9937-fa02928f19b1.png)

**Comment by Abdurrahman081** [comment]
pls can i use liveserve offline?

**Comment by PedroJSBezerra** [comment]
I also had problems with the port 5500, in my case it was the firewall, I solved the problem here => https://help.ubuntu.com/community/UFW
====== in terminal =====
sudo ufw allow 5500
====================

**Comment by sarthu858** [comment]
I followed all the steps but not found the solutions
