### ISSUE TITLE
@-Sign not working with LiveServer Extension on mac

### ISSUE THREAD

**Issue by nakedtoast** [ritwickdey/vscode-live-server#55]
ALT + L on a mac should produce an @-sign. This is not working while the extension is active.

**Comment by ritwickdey** [comment]
#38 duplicate....

**Comment by ritwickdey** [comment]
This issue has been resolved with v3.0.2.  Please update the extension and thanks for the reporting.

If you like the extension, [please drop a review to vscode marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer#review-details).

& let me know if it's still does not work for you. (I don't have MAC).
