### ISSUE TITLE
proxy  Can you configure it like webpack？

### ISSUE THREAD

**Issue by LengYXin** [ritwickdey/vscode-live-server#56]
proxy  Can you configure it like webpack？
Just want to surrogate XHR, it seems that it can't be realized

**Comment by ritwickdey** [comment]
Sorry.. can you give me an example regarding thik issue? (I'M NOT MUCH FAMILIAR WITH WEBPACK)

**Comment by rjoydip** [comment]
@LengYXin would you config proxy by webpack like configuration json file?

**Comment by LengYXin** [comment]
@ritwickdey @rjoydip Yes, but in the end, the configuration information is introduced from webpack to go through the plug-in agent. I don't understand your meaning very well. I'm not good at English, but in the end, I want to do some cross domain processing in the open page.

**Comment by rjoydip** [comment]
As per i understand, I think you want to config proxy settings through some configuration file. Like webpack do from `webpack.config.json` or `webpack.config.js`

**Comment by LengYXin** [comment]
@rjoydip Thank you very much. I remember there was no such option at the beginning.
