### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by pvmhoang** [ritwickdey/vscode-live-server#57]
After update to latest vs code stable version (1.19.0), Live Server stop working and give the following error when open browser:
```
Error: connect ECONNREFUSED 127.0.0.1:80
at Object.exports._errnoException (util.js:1050:11)
at exports._exceptionWithHostPort (util.js:1073:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

Please help me. Thanks

**Comment by ritwickdey** [comment]
Are you sure Port `80` is available? Have you tried to change the port? By default it opens port of 5500.

**Comment by pvmhoang** [comment]
still not work, i have change to like this:
 "liveServer.settings.proxy": {
        "enable": true, //switch on :)
        "baseUri": "/", //from where you want to proxy (live server).  
        "proxyUri": "http://127.0.0.1:5500" //the actual server url (NOT live server).
    },

**Comment by ritwickdey** [comment]
Hi, @pvmhoang, You're missing the point. 

Can I know, why you need proxy setup?

**Comment by selviolet** [comment]
Hi,I'm just encountering the same Error in vscode's extension(jupyter),NOT this extension, and I finally 
 solved this problem.You can reference the follow steps i used:
1. Reinstall the extension
2. open the 'hosts’ file,which located in ‘C:\Windows\System32\drivers\etc’,and add a sentence like this:
127.0.0.1 http://localhost
 then save it .
Thanks.

**Comment by mxschmitt** [comment]
As far as I seen, this issue is solved for now. If not feel free to tag me and I will reopen it.

**Comment by kirti2602** [comment]
> Hi,I'm just encountering the same Error in vscode's extension(jupyter),NOT this extension, and I finally solved this problem.You can reference the follow steps i used:
> 
> 1. Reinstall the extension
> 2. open the 'hosts’ file,which located in ‘C:\Windows\System32\drivers\etc’,and add a sentence like this:
>    127.0.0.1 http://localhost
>    then save it .
> 
> Thanks.

hey, I am facing the same issue in VS code, can you please specify how to open the "hosts" file? I am on windows.

**Comment by ayushkr7** [comment]
The host file can be opened with notepad. 
This is the file content that showed for me.
![liveserver host file](https://user-images.githubusercontent.com/51288637/144030342-e47eae92-17c9-4b12-90ac-c98d56ed123c.PNG)

**Comment by aaditya-cpu** [comment]
> > Hi,I'm just encountering the same Error in vscode's extension(jupyter),NOT this extension, and I finally solved this problem.You can reference the follow steps i used:
> > 
> > 1. Reinstall the extension
> > 2. open the 'hosts’ file,which located in ‘C:\Windows\System32\drivers\etc’,and add a sentence like this:
> >    127.0.0.1 http://localhost
> >    then save it .
> > 
> > Thanks.
> 
> hey, I am facing the same issue in VS code, can you please specify how to open the "hosts" file? I am on windows.

You can simply right click and open it with  notepad

**Comment by jagger2048** [comment]
> 

Hi, you can simply copy the hosts file to your desktop, edit it and update it. Then copy it from the desktop to the original location, overwriting the source file and thus circumventing the file permissions issue.

**Comment by sudipsharma826** [comment]
![Screenshot 2023-10-22 073034](https://github.com/ritwickdey/vscode-live-server/assets/90665217/8893794e-2851-4343-87f1-21ae988ee611)


I had seen all the process to solve the problem. But cannot be able to solve the problem.
