### ISSUE TITLE
Hi, you requested feedback on my comment on the marketplace.

### ISSUE THREAD

**Issue by Mikael-Sundstrom** [ritwickdey/vscode-live-server#58]
## Marketplace comments
+ I wrote - "Good work! The Firefox extension works really well with the VS Code extension.
It took a while before I realized how to set my settings, but now that I get it, I'm thrilled."
+ You respond - "Hey Mikael Sundström!  Thanks a lot for the try and feedback.
I understand the browser extension is little bit confusing! 
Would you like edit the documentation or make a tutorial so that others can get it very easily ? (and yes, if you've free time)"

## Issue
First of all, I did not know if PHP was running in connection with the "Go Live"-button and whether it was self-hosted by the extension. So I had to figure it out first. I did not know if it would be as easy as .html-document, and I did not know what the meaning of the browser extension was.
 
The biggest misunderstanding was the _placeholder_ in the browser extension for the Actual Server Address: `http://localhost:80/app`. I did not understand if `/app` was default and if the VS Code extension created a symbolic environment in the` /app` directory. I tried to visit both `http://localhost/app` and `http://localhost/`, without successful results.

In the end, I tested to fill in the field with `http://localhost/` for Actual Server Address.  
I run Apache with [AppServ](https://www.appserv.org/) on standard port and then I moved the workspace folder to `C:\AppServ\www\my_workspace`.

My browser extension settings is:
+ Actual Server Address: `http://localhost/`
+ Live Server Address: `http://127.0.0.1:5500/`

I think these settings should be standard and if you need other settings, enter them.

## My knowledge
I am an amateur/hobby programmer and my understanding of programming concepts and workflow might not be accurate and correct. There may also be handling errors from my side.

**Comment by ritwickdey** [comment]
hey @Mikael-Sundstrom, Thanks a lot for the response.

I under about the placeholder, I'll change it. 

But I need a person who will write good docs or youtube video. https://github.com/ritwickdey/live-server-web-extension/issues/4.

I've build the extension. So, I know clearly how to setup it. But you were fresh mind and didn't know how to setup it and finally after few times of try, you able to setup it. 

This is why I'm asking you (if you've time), would you like to like help me to write docs or make a new youtube video. [Honestly, my english is not good]

[The repo of the browser extension is here https://github.com/ritwickdey/live-server-web-extension]


Thanks Again!

**Comment by ritwickdey** [comment]
If you're interested & if you need help to do it, I'll help you 200% personally 😃
