### ISSUE TITLE
Live-server starts but it doesnt open browser automatically

### ISSUE THREAD

**Issue by doncocobongo** [ritwickdey/vscode-live-server#583]
## I'm submitting a...

```html
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

As I type "Open with live server" or i click the "Go Live" button (it used to work like 3 weeks ago). Nothing happens. It says that live-server started on the default port but the browser does not open automatically. I have to type the localhost address and go manually. I deleted all the settings related with live-server. Uninstalled the extension (i also deleted the extensions folder) and installed it again but it keeps without prompting the browser automatically. I also tried to add default/custom browser on the settings but stills without opening it automatically. 

## Expected behavior

Browser should open automatically as I click "Go Live" button or in "Open with live server" panel

## Environment

```html
Browser:

- [x] Chrome (desktop) version 77.0.3865.90
- [x] Firefox version 69.0.2
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 5.6.1<!-- Check which version is installed --> 
- Platform: Windows 10 (1903) <!-- Mac, Linux, Windows -->
- Visual Studio Code: 1.38.1<!-- `code --version` -->
```

## Others

Also I deleted live-sass compiler which could have been causing problems on vs-code but keept without working. Its weird because on my laptop (same OS and VS-Code versions) it works well.

**Comment by doncocobongo** [comment]
Same bro tried all and didnt works. On my laptop works with no problem and I have same version and all.

**Comment by abhishekpakhare97** [comment]
I am also facing same issue the as @doncocobongo  is facing. Is there any solution regarding this issue?

**Comment by doncocobongo** [comment]
> 
> 
> I am also facing same issue the as @doncocobongo is facing. Is there any solution regarding this issue?

I've been investigating and I think my issue could be caused because browser is installed on a different directory than vs-code. I'll reinstall OS this week and see if this solves the issue once I install all correctly.

What i cant understand is why 2 months ago the extension worked and now it isnt, when I didnt touch directories or something.

**Comment by abhishekpakhare97** [comment]
But my browser is installed on default location still facing the same issue. I have updated my windows few days ago. Can this be the issue of live server not working. Did you update your system recently?

**Comment by doncocobongo** [comment]
Formatting my PC resolved this issue, now the extension works without problems. I assume it was because (I dont know why) I had Program Files (x86) and normal in spanish and Program Files in english also, so I think having this bad folder setup was causing the issue. (I usually just have it in Spanish).

**Comment by htayhtaylail** [comment]
I tried many times by clicking the live server option after installing the extension in vs code , it's connecting but my browser is not opening.
C
![error_vscode_liveserver](https://user-images.githubusercontent.com/51523509/97129923-71eb0080-176e-11eb-82f4-ccfb4cb5f726.PNG)

an anybody solve this problem. I don't know how to solve it . Please help me.

**Comment by zelizabeth** [comment]
https://www.youtube.com/watch?v=VqW50Y7RSfQ

the video above worked for me
