### ISSUE TITLE
live server doesnt update changes to the browser result

### ISSUE THREAD

**Issue by khun84** [ritwickdey/vscode-live-server#6]
Hi, Im able to view the html page on my browser when I start the server. However, when Im starting to edit the html file, the changes were not reflected on the browser on live basis. 

Am I doing it wrong? Or am I missing any other extensions that are required to make the live update works?

**Background:**
- OS: OSX Sierra
- Live Server Preview 0.0.4
- Safari browser
- Port: 3500

**Comment by ritwickdey** [comment]
Nope! it does not have any other dependency...

Anyway, `<body></body>` or `<head></head>` tag is required for live update. Make a sure that you're using that.

And please try Chrome.............. I don't have Mac. So, I don't about Safari.... But it should work on Safari as well.

**Comment by khun84** [comment]
I have tried again using chrome this time. Aint getting the live update though.

URL shown in browser:
`http://127.0.0.1:3500//test.html`

HTML script:
```
<!DOCTYPE html>
<html>
    <head>

    </head>

    <body>
        <p>test</p>
    </body>
</html>
```

**Comment by ritwickdey** [comment]
okay! please try `http://127.0.0.1:3500/test.html` ........... Are you getting any message from Live Server to browser console such as "Live reload enabled."? Check `View Source Page`. Have there any additional extra JS Code ?

**Comment by ritwickdey** [comment]
The code will look like 
``` JavaScript

<!-- Code injected by live-server -->
  // <![CDATA[  <-- For SVG support
  if ('WebSocket' in window) {
  (function() {
 function refreshCSS() {
.........................
........................
.........................
}
```

**Comment by khun84** [comment]
I have to manually change the url to `http://127.0.0.1:3500/test.html` after the page was launched in the browser.

Yes, I do see the "Live reload enabled" in the console.

Below is the code from `View Source Page`
```
<!DOCTYPE html>
<html>
    <head>

    </head>

    <body>
        <p>teste</p>
    <!-- Code injected by live-server -->
<script type="text/javascript">
	// <![CDATA[  <-- For SVG support
	if ('WebSocket' in window) {
		(function() {
			function refreshCSS() {
				var sheets = [].slice.call(document.getElementsByTagName("link"));
				var head = document.getElementsByTagName("head")[0];
				for (var i = 0; i < sheets.length; ++i) {
					var elem = sheets[i];
					head.removeChild(elem);
					var rel = elem.rel;
					if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
						var url = elem.href.replace(/(&|\?)_cacheOverride=\d+/, '');
						elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
					}
					head.appendChild(elem);
				}
			}
			var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
			var address = protocol + window.location.host + window.location.pathname + '/ws';
			var socket = new WebSocket(address);
			socket.onmessage = function(msg) {
				if (msg.data == 'reload') window.location.reload();
				else if (msg.data == 'refreshcss') refreshCSS();
			};
			console.log('Live reload enabled.');
		})();
	}
	// ]]>
</script>
</body>
</html>
```

**Comment by ritwickdey** [comment]
Honestly speaking, I've no idea. Everything is okay. Just now I tried from Linux, there is no such problem.

**Comment by khun84** [comment]
Hmm I was wondering if theres any missing library or wrong global settings from my end here. Ive tried plenty of HTML preview in VSCODE market place, non of them work for me on the live update feature. However Markdown preview extension does the job for my markdown file though.

**Comment by ritwickdey** [comment]
oh,.......`Markdown preview` extension? VSCode has build in Markdown Preview features. Which are you taking about? Can you send me link of the extension?

Anyway, I published v1.6.4 and v1.6.5 with lot of bug fix. Let me know if it works for you or not.

**Comment by TheGhost999** [comment]
Hi there, 
I'm getting the same issue.
Here is a very short video I've put into my dropbox account that illustrates this
(Only 1min 52 sec long).

Really hope you can advise me with what is wrong here.... just can't get the live update of changes to display on the webpage.
Link is here for video;
https://www.dropbox.com/s/xzb8xq6tbc9szgn/live%20server%20doesn%27t%20update.mp4?dl=0

I'm using version 2.1.1 of liveserver,,,, andf visualstudio code is version 1.16.1 x64,,, using windows 10 x64 pro

Help!!!! :-)
Many thanks
Yours sincerely
JC

**Comment by ritwickdey** [comment]
Hi, @TheGhost999. I've just noticed, you're not saving the file. 

When you are starting live server again, the extension is saving all the dirty file.

**Comment by TheGhost999** [comment]
Many thanks for your swift reply ritwickdey.

I've created 1 small video again, in reply.
Are you saying I must go to file/save,,,,to save any changes 1st,, then open a new tab in my browser window?
So basically it won't display changes made on the fly like say dreamweaver 2017 cc?
Here's a link to show exactly what I mean;
https://www.dropbox.com/s/lsjlnbhtl7shhpz/live-preview-realtime.mp4?dl=0

Hope you can advise ritwickdey.
It's a great plugin,, but would be awesome if it could have the same functionality of DW.
image relating to video is here also
https://imgur.com/a/5n5Wl

Best regards
JC

**Comment by ritwickdey** [comment]
Hi, @TheGhost999. I understand. I'm taking it as a suggestion. If it is possible for me, I'll definitely add the feature in future.  (Actually, DW or Bracket works totally different way).

For now, after making some changes, just press **`ctrl+s`** (I think it is most easier way to save a file and also it is a great practice - I believe), browser will refresh the page automatically. (you don't have refresh browser window manually or start server again).  

If you're feeling that saving every-time is boring, you can use the vscode's autosave feature.
```json
{
  "files.autoSave" : "afterDelay",
    //OR
  "files.autoSave": "onFocusChange",
    //OR
   "files.autoSave": "onWindowChange"
}
```

_Just Start Server -> Made some change -> ctrl+s -> Browser will refresh automatically. ([Short Video](https://www.youtube.com/watch?v=_4TraiVJDe0))_

Thanks You

**Comment by TheGhost999** [comment]
Hi ritwickdey!
Many thanks again for your reply.
Yes,, a suggestion! :-)
A good 1 I feel? :-)

Brackets do it, DW do it,,, ritwickdey's 'Live Server' can do it! :-)
Really hope you can impliment this feature request asap,, it really is a must have,,,, very handy!

Keep up the great work Ritwickdey!
Best regards
JC
