### ISSUE TITLE
does loading the page require ethernet bandwidth ?

### ISSUE THREAD

**Issue by medilies** [ritwickdey/vscode-live-server#602]
I'm a noob dev and new to VSC and I don't know if I must do any extra setting on the extension!

I'm simply trying to load a simlpe html page with one header (h1) but the chrome tab opened on loacalhost keep showing the loading icone with no results while brackets live preview works perfectly.

is there something i'm missing ?

**Comment by LukeWolfGames** [comment]
To better understanding your situation, please provide your code and screenshots of what you are seeing.

**Comment by medilies** [comment]
![image](https://user-images.githubusercontent.com/35309918/68713772-dda87d80-059e-11ea-83f4-73f3a5bf516f.png)


![image](https://user-images.githubusercontent.com/35309918/68713468-3a576880-059e-11ea-902c-4790fc47d75f.png)

**Comment by LukeWolfGames** [comment]
I'm a bit concerned about why the local host page is still loading when you took this screenshot.

A few questions:

1) How long was it loading the page for before you took the screenshot?
2) May seem like an obvious one but have you tried closing VS code, opening it up again and trying again?
3) When you press shift + I in the browser, are you getting any errors in the console?

**Comment by medilies** [comment]
sorry for the long absences but I found the problem :)

it's a matter of firewall ! I just tried to disable the firewall on windows and silnce avast... now everything works perfectly and pages load very fast.
