### ISSUE TITLE
No 'Open with Live server' option

### ISSUE THREAD

**Issue by thrallez** [ritwickdey/vscode-live-server#604]
## I'm submitting an issue 

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

Visual Studio is not showing the Open with live server option, which was there last time I used the extension, no problem.

## Expected behavior

Showing the option to open with live server; I've tried reinstalling the extension, but nothing.

## Environment

```html
Browser:

- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 5.6.1
- Platform:  Mac
- Visual Studio Code: 1.40.0
```

## Others

I'll try to upload an image showing that the option is _not_ there.

**Comment by tranvansu522** [comment]
Live server not running browser :
Chrome 
Firefox
Edge
 I've tried reinstalling the extension, but nothing. also reinstalling VScode , nothing

**Comment by thrallez** [comment]
I believe that I've found the reason and I've managed to make the extension work again: It has something to do with autosaving option enabled _and_ the use of workspaces; When using a workspace (which I found out is nothing more than a folder) the extension works like a charm - working outside of it, it doesn't seem to work. Also, I must have the parent folder open for the extension to work... I don't know why, but it's working again.
