### ISSUE TITLE
mac not auto-updating?

### ISSUE THREAD

**Issue by michaeldesu** [ritwickdey/vscode-live-server#61]
Hi, I'm trying your extension on Windows & Mac side-by-side, and on Windows auto-updates occur as advertised, but not on the Mac. I can only see an update on Mac if I force it via "Open with Live Server". I'm using VSCode 1.19.1 and Sierra OS and Live Server 3.0.2. Is this extension a Windows only one? Let me know if more info is needed.

**Comment by ritwickdey** [comment]
Hi @michaeldesu, this extension should work in Mac.

Sorry, What do you mean by "auto-updating"? Are you referring Live Reloading?

**Comment by michaeldesu** [comment]
Hi @ritwickdey happy new year BTW. Yes I meant Live Reloading. Thanks for your confirmation. Well, I just tried it on my Yosemite laptop and it's ok. I seem to have an issue with my desktop - I will investigate.. Apologies. Thanks alot for providing this great extension.

**Comment by ritwickdey** [comment]
Yes! Happy New Year. 

Btw, If you need any help, you can ask me. If you see any error regrading this extension on vscode console _(help -> toggle developer tools)_ or browser console, take a screenshot and drop here. 
-  And be ensure that your HTML file has `body` tag. 
- And last (but not least 😸 ), when you open the HTML page through Live Server, you will see extra JavaScript code which is responsible for live-reload.   `<!-- Code injected by live-server -->`

**Comment by michaeldesu** [comment]
Thanks for your time. I've created the same simple HTML & JS test on 3 machines (PC, and Mac x 2). Just a h1 tag and alert/console string emission. I can see the code injection. The only difference I can see between the 3 is in the attached, i.e. I get a warning and no other 'change detected' message on the machine that's having a problem. The other 2 machines show 'change detected messages in the respective file.
![screen shot 2018-01-01 at 9 29 58 pm](https://user-images.githubusercontent.com/11791450/34467383-7d28d5ac-ef3b-11e7-9184-cb45b18ca785.png)

**Comment by ritwickdey** [comment]
Ok, Can you send me the two snapshot of your workspace with opened the `app.js` and the `index.html`?

**Comment by michaeldesu** [comment]
Is this what you wanted? BTW I noticed I could get a 'change detected' message but only after saving the file, but the update was not reflected in the live browser.

![screen shot 2018-01-01 at 10 21 21 pm](https://user-images.githubusercontent.com/11791450/34467607-3e7467ca-ef42-11e7-8799-6665c289aec7.png)
![screen shot 2018-01-01 at 10 21 33 pm](https://user-images.githubusercontent.com/11791450/34467608-3eae76d6-ef42-11e7-8068-17ca4cd20062.png)

**Comment by ritwickdey** [comment]
Oh yes! That is expected behavior.. You've to save file to live reload on browser. 

> If you don't like to save everytime, then turn on vscode's auto save feature.

**Comment by michaeldesu** [comment]
OMG - that was simple, and a relief. Sorry for inconvenience. It may be worth to add in a doc or FAQ that the 'live' function needs auto-save enabled in the editor, though I guess it's rather obvious in retrospect. Thanks so much again.
