### ISSUE TITLE
Proxy Origin and Referer

### ISSUE THREAD

**Issue by elias-garcia** [ritwickdey/vscode-live-server#64]
Hi! It would be a very interesting feature that when you use the proxy the `Origin` header of the HTTP request also changes to the proxied url. Because for example, I want to use the proxy to skip the CORS in a customer API that doesn't allow CORS.

This is the response I'm getting:

`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:5500' is therefore not allowed access.`

So as I can see the proxy only changes the destination url, but not the Origin and the Referer. This could be a very interesting feature to easy skip CORS.

**Comment by ritwickdey** [comment]
Yep! CROS is not enabled. It's coming in upcoming update

**Comment by elias-garcia** [comment]
Nice to hear that! 😄

**Comment by blurdylan** [comment]
As of now I use a chrome extension to enable CORS.
https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi

**Comment by ritwickdey** [comment]
This features is already added in v3.1.0.  (Sorry, I forget to close it)
