### ISSUE TITLE
Status Code:405 Method Not Allowed

### ISSUE THREAD

**Issue by upaccount** [ritwickdey/vscode-live-server#66]
Request Method:POST
Status Code:405 Method Not Allowed

the GET Method is ok,but post does not work and error occurred,other web server is ok

**Comment by ritwickdey** [comment]
Hi @upaccount, Is the issue solved?

**Comment by Adamoc14** [comment]
I'm trying to post data from one HTML form on site A to site B.
I'm still getting the error message indicated above 
Request Method: POST
Status Code:405 Method Not Allowed
Can you please try and fix this, at the moment I'm having to test out my whole payment system and it is in very tedious steps where I publish to a Heroku server via GitHub and then I can see whether changes I made are as desired. Would love to do it through your Live server extension(Which I love btw), can you please update the server settings to be able to handle post requests

**Comment by donner-dev** [comment]
Issue is still ongoing!
