### ISSUE TITLE
live server不能正确识别文件路径

### ISSUE THREAD

**Issue by YuJianghan** [ritwickdey/vscode-live-server#686]
Issue Type: <b>Bug</b>

在将多个文件夹添加到工作区时，使用live server预览一个文件夹中的Html代码时，一些情况下不能正确识别文件路径。例如：命名一个文件夹：1和文件夹：10，添加到同一工作区，选择文件夹：10中的Html文件右键open with live server，它会因名称的bug定位到文件夹：1，从而无法预览文件夹：10中的文件。类似的，命名为Test20、Test21、Test22……的文件夹也都会错误定位到Test2。

Extension version: 5.6.1
VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.19582

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (24.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by lipanpan-hub** [comment]
确实存在这个问题

**Comment by end-cycle** [comment]
请问怎么解决的呢
