### ISSUE TITLE
How to Kill Liver Server Once Editor Window is Closed?

### ISSUE THREAD

**Issue by stevenloe** [ritwickdey/vscode-live-server#69]
How can I stop the live server when the editor tab has been closed? Sometimes I have live server running, then I close the browser tab containing the code that it was running. Now if I try to start the server on another tab it fails  -- there is already a server running. Is there a command to stop the server?

btw: live-server is awsome!

**Comment by ritwickdey** [comment]
Have you check this section https://github.com/ritwickdey/vscode-live-server#shortcuts-to-startstop-server ?

**Comment by stevenloe** [comment]
Got it! Thanks!
