### ISSUE TITLE
Error to open browser

### ISSUE THREAD

**Issue by DonInMedford** [ritwickdey/vscode-live-server#7]
Hello, thank you for your hard work! I am having a minor issue, with Live Server 1.6.5. When I open live server it gives me the "Error to open browser"  It does work, just does not open the window like it should. I have to open the browser of my choice manually and go to the http://localhost:5500/.  I am on Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit). 
Making a .vscode folder with settings.json file to Firefox has the same result. index.html is at the root of the folder and not inside any other folders. 
{
    "liveServer.settings.CustomBrowser" : "firefox"
}
![error_to_open_browser](https://user-images.githubusercontent.com/11590466/28694775-4fb3b84e-72e0-11e7-9c6d-fbcdf74e206a.png)

**Comment by ritwickdey** [comment]
ok! I got your problem! I need a few more information. 
1. Is the chrome working for you?
2. Have you change anything to this settings - `liveServer.settings.AdvanceCustomBrowserCmdLine:null`?

**Comment by ritwickdey** [comment]
I tried from my LINUX MINT. It is working. 

Make a sure that, you have not chnaged this settings `liveServer.settings.AdvanceCustomBrowserCmdLine`.

And what about when you open terminal and enter 'firefox' .... does the firefox get started?

**Comment by cobola** [comment]
<img width="997" alt="2017-07-28 17 47 31" src="https://user-images.githubusercontent.com/4435875/28712346-706a19b0-73bd-11e7-8f0f-1ec78d3afb28.png">
<img width="548" alt="wx20170728-175225 2x" src="https://user-images.githubusercontent.com/4435875/28712420-a335f3f0-73bd-11e7-975e-098d6653caee.png">


my file under ``C:\Users\xiangxiang\Documents>``  got the error 

in other dirctory is ok

**Comment by ritwickdey** [comment]
Hi @cobola... Is the related to Live Server?

**Comment by cobola** [comment]
yes ,Live Server

**Comment by ritwickdey** [comment]
sorry, I don't get that. Are you facing same issue?

**Comment by DonInMedford** [comment]
@ritwickdey thank you so much for the work!  No it was a new install to test coding on Ubuntu. I did not make any changes to vs code or live server. Firefox launched from command line just fine. Chrome kept freezing at odd times so I installed Chromium and that was freeze free. I have gone back to VS Code on Windows 10 as my main OS instead of fighting with it and Live Server 1.6.5 works perfectly. If you have tested it on Mint and it works I believe you.  If @cobola has no issue, you may close this. Thank you again, Don

**Comment by ritwickdey** [comment]
Sorry,  I can't understand what @cobola is saying. Please say more details about the error. When/How it is occurring?

**Comment by DonInMedford** [comment]
I will go ahead and mark this closed. I appreciate the work you have done.
