### ISSUE TITLE
Error - command 'extension.liveServer.goOnline' not found

### ISSUE THREAD

**Issue by chadamodio** [ritwickdey/vscode-live-server#70]
When I try to run I get a VS Code "Warn" that says "command 'extension.liveServer.goOnline' not found"
and nothing happens. Also, the button [Go Live] is not showing.

VS Code Version 1.19.2
Node 7.9.0

**Comment by ritwickdey** [comment]
Seems like, extension is failed to start!

Have you tried to uninstall/install again?

**Comment by chadamodio** [comment]
Yes, I completely uninstalled and reinstalled.

**Comment by ritwickdey** [comment]
Is this still not working? if yes! please send me a screenshot of Developer tools console (helps -> toggle developer tools) after open a folder with at least one html file!

**Comment by chadamodio** [comment]
![image](https://user-images.githubusercontent.com/16690679/35887050-08de3d58-0b61-11e8-8ad5-6bc7b293d05d.png)

**Comment by chadamodio** [comment]
Hello,
Not sure if you did anything but it is working now! Thanks!
