### ISSUE TITLE
live reload is not working

### ISSUE THREAD

**Issue by sfn101** [ritwickdey/vscode-live-server#71]
every time i chang somting i need to save it don't reload automatical

**Comment by ritwickdey** [comment]
Thanks for the report. I need more info! Which OS you're using?

& make sure that you've open a folder (file -> open folder) and your `html` file must have `body` or `head` tag

**Comment by sfn101** [comment]
windows 7  
yes i open folder and my .html have body i think its not issue to be fair 
i com from brackets and i start using vscode and your live server in brackets we don't save to reload and see the changes in the server its live real-time edit reload so i don't think it is possible  to do that in vscode

and this video he don't save (ctrl+s) at all he just type and he can see it live 
https://www.youtube.com/watch?v=Nhvj1NYC3Uc

**Comment by larrykkk** [comment]
it is possible in vscode 
select the option at file>autosave 
at least it is work to me

**Comment by sfn101** [comment]
@larrykkk yes but you end with save file in brackets your file don't save so you will see if it work before save so it will never affect the file if you mess up but autosave better than nothing

**Comment by rjoydip** [comment]
Closed due to invalid feature required.

**Comment by abmestri25** [comment]
getting notification as started as port 5500

**Comment by rjoydip** [comment]
@abmestri25 What kind of notification?

**Comment by Edmund1645** [comment]
> windows 7
> yes i open folder and my .html have body i think its not issue to be fair
> i com from brackets and i start using vscode and your live server in brackets we don't save to reload and see the changes in the server its live real-time edit reload so i don't think it is possible to do that in vscode
> 
> and this video he don't save (ctrl+s) at all he just type and he can see it live
> https://www.youtube.com/watch?v=Nhvj1NYC3Uc

Hello, I have this same problem presently, The problem is that the Live reload feature is not really working on windows machine, I was using a Linux VM and it works fine there even on Mac too, The problem is that it doesn't work with VSCode on windows machine.
