### ISSUE TITLE
command 'extension.liveServer.goOnline' not found

### ISSUE THREAD

**Issue by Rishika-Raveendran** [ritwickdey/vscode-live-server#712]
I am just learning web designing and using vscode,the browser is not opening with the Open with Live Server option and the above warning is shown when the shortcut keys are used. I tried all the previous suggestions for this problem but with no luck.
Vscode version 1.44

**Comment by bassamanator** [comment]
I too am getting this error on Manjaro.

command 'extension.liveServer.goOnline' not found
