### ISSUE TITLE
Is router support？

### ISSUE THREAD

**Issue by cdswyda** [ritwickdey/vscode-live-server#72]
Some project use virtual directory, how can I make it work ?

**Comment by cdswyda** [comment]
Maybe it is related width  #39

**Comment by cdswyda** [comment]
I send an pull request #73 

add config :

```js
"liveServer.settings.mount": [
        ["/ep920", "./"]
 ]
```

out put at vscode's console:

![image](https://user-images.githubusercontent.com/13060680/35898976-b78bbd3c-0c04-11e8-92d5-9e10331cd88d.png)

and it works well.

**Comment by ritwickdey** [comment]
I think https://github.com/ritwickdey/vscode-live-server/issues/52 is also same ?

**Comment by ritwickdey** [comment]
Wait a min! I think #52 & #39 is talking about SPA url rewriting (instead of throwing 404, returns main `html` file, so that SPA can handle the route).

Is not it ?

**Comment by mpkelly** [comment]
@ritwickdey I think they are and I also have the same problem. The server launches fine but when refreshing to a child route I get a 404 because the server can not find a file for <root>/child/path. In my case, this route should be handled by React Router. Can you add a config option that allows the user to specify a default file instead of returning a 404? Defaulting to the file the user used to launch Live Server would be a good idea, too.

**Comment by Evertvdw** [comment]
Yep, having the same problem here, I want my index.html to be loaded on every url that is requested.

**Comment by cdswyda** [comment]
Maybe the `middleware` option of live-server is useful.

```js
var liveServer = require("live-server");

var params = {
	port: 8181, // Set the server port. Defaults to 8080.
	host: "0.0.0.0", // Set the address to bind to. Defaults to 0.0.0.0 or process.env.IP.
	root: "/public", // Set root directory that's being served. Defaults to cwd.
	open: false, // When false, it won't load your browser by default.
	ignore: 'scss,my/templates', // comma-separated string for paths to ignore
	file: "index.html", // When set, serve this file (server root relative) for every 404 (useful for single-page applications)
	wait: 1000, // Waits for all changes, before reloading. Defaults to 0 sec.
	mount: [['/components', './node_modules']], // Mount a directory to a route.
	logLevel: 2, // 0 = errors only, 1 = some, 2 = lots
	middleware: [function(req, res, next) { next(); }] // Takes an array of Connect-compatible middleware that are injected into the server middleware stack
};
liveServer.start(params);
```

If it has `middleware` support , we can use `res.redirect` ,  but that require a function type ,  how can I config a function type in vscode's settings ?

**Comment by Evertvdw** [comment]
That should do the job yes :)

**Comment by cdswyda** [comment]
A pr for file option support #118 .

**Comment by rjoydip** [comment]
@cdswyda Thanks for this PR. These feature is now available in new release. I am closing this issue
