### ISSUE TITLE
Error on Port 80

### ISSUE THREAD

**Issue by fwzmhmd** [ritwickdey/vscode-live-server#74]
Cannot set live server on port 80.

**Comment by Fall1ngStar** [comment]
Can you be a bit more precise ? Which system are your using ? Do you have a web server running ?

**Comment by ritwickdey** [comment]
You can set port 80, if it is available. [Most of case, you'll not]

**Comment by rjoydip** [comment]
@fwzmhmd IMO it will be better if you avoid port 80. Thank you for reporting issue. I am closing this issue right now.
