### ISSUE TITLE
"This site can't be reached" using Windows 10 and WSL2

### ISSUE THREAD

**Issue by einarpersson** [ritwickdey/vscode-live-server#760]
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior
1. Create new folder.
2. Add new `index.html`
3. Click "Go live!"
4. Chrome opens `http://127.0.0.1:5500/index.html` but I get a **This site can’t be reached. 127.0.0.1 refused to connect.**

## Expected behavior
I expect the site to be loaded correctly.

## Environment

```html
Browser:

- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:

- Live Server: 5.6.0 
- Platform:  Windows 10
- Visual Studio Code: 1.44.2
```

## Others
**WSL2 (Windows subsystem for Linux) Ubuntu 18.04**
With the official WSL extension for VScode

**Comment by einarpersson** [comment]
(If I write `npx http-server .` in the VSCode bash terminal the site is served correctly on 8080.)

**Comment by einarpersson** [comment]
(Have also tried uninstalling and reinstalling the extension)

**Comment by einarpersson** [comment]
Did some more investigation. If I set `"liveServer.settings.useLocalIp": true` it works. I guess this has something to do with WSL2. 

Any ideas why localIp might work but not else?

**Comment by einarpersson** [comment]
Seems to be a problem with WSL2 rather than this extension. 
https://github.com/microsoft/WSL/issues/4636

**Comment by uverpro** [comment]
I ran powershell as admin and ran "wsl --shutdown" and it worked for me once. But then it stopped working.
