### ISSUE TITLE
Doesn't update favicon in Google Chrome

### ISSUE THREAD

**Issue by zl-kolev** [ritwickdey/vscode-live-server#77]
Strangely, Live Server caches an old version of the favicon my website is using, even though it's not declared in the HTML at all. I have to explicitly declare a new icon in order to get it changed. It gets even more frustrating when I comment out that declaration and the favicon is still there, but only in Google Chrome. As expected, in Firefox it doesn't show.

I'm using Windows 10 x64, VS Code 1.20.0, Live Server 3.2.0.

Feel free to ask for more information, would be glad to assist.

**Comment by ritwickdey** [comment]
Okk!! it's not about live server! This is about the browser cache! 

just try the trick (it may works):
`<link rel="icon" href="favicon.ico?v=2" type="image/x-icon"/>`

`?v=ANYTHING` will remove the cache.

**Comment by Arnie97** [comment]
Seems to be a known Chrome bug.
https://superuser.com/questions/375321/how-to-refresh-bookmark-favicons-in-chrome
