### ISSUE TITLE
I can't open Go Live 

### ISSUE THREAD

**Issue by monwell57** [ritwickdey/vscode-live-server#79]
Hi - i been using Live Server for over a month with no issues. This morning, i just received this message: "Error on port 5500. Please try to change the port through settings or report on GitHub."

**Comment by ritwickdey** [comment]
Have to tried to change the port?

**Comment by monwell57** [comment]
I should have mentioned, i'm new to vs code, & coding in general. I did go to vs code's "Settings" - "Live Server Config", but i don't know what to do.?

**Comment by ritwickdey** [comment]
open user settings, 
```
{
"liveServer.settings.port" : 0 
}
```

(this setting will make the port random)

* All Settings: 
https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

**Comment by monwell57** [comment]
Now i get "Error on port 0. Please try to change the port through settings or report on GitHub."

**Comment by ritwickdey** [comment]
Ok! I'm sorry for your issue! I need few more info!

Please remove the settings and restart vscode.. now try to open the live server with port 5500 (Default).

Even if it is showing error. Try to open the address on browser. "http://127.0.0.1:5500/" .. Let me know, is this working or not?

**Comment by monwell57** [comment]
I actually reinstalled Live Server before i got your reply. It appears to be working. Now it's opening up at port 61220, by default. Does that sounds ok to you?

**Comment by ritwickdey** [comment]
Ok! I've no problem if you're happy with random port.

if you don't want random port, then just remove the port setting.

**Comment by ritwickdey** [comment]
Anyway, thanks for the report!

If you really like the extension, please drop a review in vscode marketplace.
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer
