### ISSUE TITLE
Live server does not work

### ISSUE THREAD

**Issue by kmdrGroch** [ritwickdey/vscode-live-server#80]
"command 'extension.liveServer.goOnline' not found"
Even after reinstall, issue still exists
Also i don't see that shortcut on the bottom.

**Comment by ritwickdey** [comment]
Sorry for that! Still the reason is unknown to me! please try it, it should work. => #78

**Comment by kmdrGroch** [comment]
Deleting that content worked. And yes, i think it's VScode issue. It wasn't like that before :/

**Comment by ritwickdey** [comment]
Hi @kmdrGroch, Thanks for the report. 👍

**Comment by djkenneth** [comment]
i have a problem in live server extension when i click the go live it will open a directory in chrome and then when i click the file it will download it not open it. please help me!

**Comment by taiwocode** [comment]
"command 'extension.liveServer.goOnline' not found"

help me
