### ISSUE TITLE
Server Side Includes?

### ISSUE THREAD

**Issue by peterbenoit** [ritwickdey/vscode-live-server#81]
Is there support (or planned support) for SSIs?

**Comment by ritwickdey** [comment]
Are you talking about HTTPS?

**Comment by peterbenoit** [comment]
No, Server Side Includes

https://en.m.wikipedia.org/wiki/Server_Side_Includes

**Comment by rjoydip** [comment]
@peterbenoit yes you can do SSI which php support. [Link](https://people.goshen.edu/~paulmr/physix/326/ssi.php).

**Comment by rjoydip** [comment]
I think you got isolation. I am closing this issue now. Thank you for reporting this issue.

**Comment by nitech** [comment]
Is server side includes possible in vscode live server?

**Comment by dapertutto** [comment]
@rjoydip SSI is server feature, It has nothing to do with PHP. Regarding php actual mature (apache, nginx, etc) server must be set up. If its on why bother with Live Server at all. So the question is: will Live Server support SSI in the future. I choose Live Server for html layout, support for SSI would be nice feature.

**Comment by nitech** [comment]
I wanted SSI in Live Server so I could develop a static HTML-site without repeating code all over. Since it is not supported in Live Server, I ended up creating a little "client side includes" javascript snippet. If anyone is interested, please feel free to use: 

Note that it will only allow you to load stuff between the `<body>`-tags. Tested on IE11, and evergreen version of FireFox and Chrome.

### Usage in HTML

```html
<!-- Partial: Hero with Carousel -->
<div data-include="partials/hero-with-carousel.html"></div>
```

### Script

```js
$(function() {
    // process "client side includes"
    processPartials($("div[data-include]"), function() { 
        // continue with the rest of the "on DOM ready" functionality
        processSite()
    });

    function processPartials(selector, callback){
        jQuery.ajaxSetup({async:false});
        
        var partials = selector.toArray();

        while(partials.length > 0){

            // get first item
            var el = $(partials[0]);

            // get contents of include
            $.get(el.data("include"), function(data) {
                var $newElement = $(data);
                el.replaceWith($newElement);
                
                // process possible includes
                $newElement.find("[data-include]").each(function(index, item){
                    partials.push(item);
                });
            }).always(function(){
                // remove this item from partials list
                partials.splice($.inArray(partials[0], partials),1);
            });
        }

        callback();
    }
});
```

**Comment by fedegonzal** [comment]
> I wanted SSI in Live Server so I could develop a static HTML-site without repeating code all over. Since it is not supported in Live Server, I ended up creating a little "client side includes" javascript snippet. If anyone is interested, please feel free to use:
> 
> Note that it will only allow you to load stuff between the `<body>`-tags. Tested on IE11, and evergreen version of FireFox and Chrome.
> 
> ### Usage in HTML
> ```
> 
> <div data-include="partials/hero-with-carousel.html"></div>
> ```
> 
> ### Script
> ```js
> $(function() {
>     // process "client side includes"
>     processPartials($("div[data-include]"), function() { 
>         // continue with the rest of the "on DOM ready" functionality
>         processSite()
>     });
> 
>     function processPartials(selector, callback){
>         jQuery.ajaxSetup({async:false});
>         
>         var partials = selector.toArray();
> 
>         while(partials.length > 0){
> 
>             // get first item
>             var el = $(partials[0]);
> 
>             // get contents of include
>             $.get(el.data("include"), function(data) {
>                 var $newElement = $(data);
>                 el.replaceWith($newElement);
>                 
>                 // process possible includes
>                 $newElement.find("[data-include]").each(function(index, item){
>                     partials.push(item);
>                 });
>             }).always(function(){
>                 // remove this item from partials list
>                 partials.splice($.inArray(partials[0], partials),1);
>             });
>         }
> 
>         callback();
>     }
> });
> ```

Works well, thanks! but **should be** a native feature on this plugin..

**Comment by designly1** [comment]
> I wanted SSI in Live Server so I could develop a static HTML-site without repeating code all over. Since it is not supported in Live Server, I ended up creating a little "client side includes" javascript snippet. If anyone is interested, please feel free to use:
> 
> Note that it will only allow you to load stuff between the `<body>`-tags. Tested on IE11, and evergreen version of FireFox and Chrome.
> 
> ### Usage in HTML
> ```
> 
> <div data-include="partials/hero-with-carousel.html"></div>
> ```
> 
> ### Script
> ```js
> $(function() {
>     // process "client side includes"
>     processPartials($("div[data-include]"), function() { 
>         // continue with the rest of the "on DOM ready" functionality
>         processSite()
>     });
> 
>     function processPartials(selector, callback){
>         jQuery.ajaxSetup({async:false});
>         
>         var partials = selector.toArray();
> 
>         while(partials.length > 0){
> 
>             // get first item
>             var el = $(partials[0]);
> 
>             // get contents of include
>             $.get(el.data("include"), function(data) {
>                 var $newElement = $(data);
>                 el.replaceWith($newElement);
>                 
>                 // process possible includes
>                 $newElement.find("[data-include]").each(function(index, item){
>                     partials.push(item);
>                 });
>             }).always(function(){
>                 // remove this item from partials list
>                 partials.splice($.inArray(partials[0], partials),1);
>             });
>         }
> 
>         callback();
>     }
> });
> ```

How would lazy loading parts of a web page effect SEO? Wouldn't Lighthouse complain about above the fold content being lazy loaded? Also creates unnecessary HTTP requests. Would make much more sense to use SSG. Not sure why live server doesn't support SSIs still in 2024. I guess there's not a demand for it anymore as everyone uses frameworks.

**Comment by malaudha** [comment]
This would be a really interesting feature, is this planned in the future?
