### ISSUE TITLE
Does not react to CSS file changes

### ISSUE THREAD

**Issue by dnistreanu** [ritwickdey/vscode-live-server#85]
**VS CODE v1.21.0**
**Windows 10** 

**Description:** 
- It's not refreshing page when changing .css file.

**Details:**
- Name of html file: **index.html**
- Name of css file: **styles.css**
- Files are in the same folder.

**Comment by udiNur** [comment]
> liveServer.settings.fullReload: : By Default Live Server inject CSS changes without full reloading of browser. You can change this behviour by making this setting as true.
> Default:  false


source link: https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

**Comment by rjoydip** [comment]
@dnistreanu i am closing this issue because of "no feedback from your end". Reopen it if you still facing this issue.

**Comment by cbolik** [comment]
Thanks @psmass this worked for me as well, by activating this setting globally, from Settings/Extension/Live Server Config and in the put the check mark next to "Full Reload".

**Comment by zeniff81** [comment]
> > liveServer.settings.fullReload: : By Default Live Server inject CSS changes without full reloading of browser. You can change this behviour by making this setting as true.
> > Default:  false
> 
> source link: https://github.com/ritwickdey/vscode-live-server/blob/master/docs/settings.md

Great. This worked for me.
