### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by farhan2077** [ritwickdey/vscode-live-server#859]
- Issue type: `Bug`
- Extension Name: `LiveServer`
- Extension version: `5.6.0`
- Platform:  `Windows 10 Pro, Version-1703, OS Build-15063.0`
- Visual Studio Code: `1.46.0`

Log: [ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/4776695/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)

**Comment by Spectrum-Beta** [comment]
`<p><b>Same Here</b></p>`
