### ISSUE TITLE
Go Live now only works with safari

### ISSUE THREAD

**Issue by mclamanna** [ritwickdey/vscode-live-server#86]
Im a little lost, Ive been using live server for weeks with chrome and then all of a sudden I'm getting the:
"The webpage at http://127.0.0.1:5500/index.html might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED"

Message, so I switched my default browser to Safari and now it works, but it still doesn't work in chrome and firefox any idea?

Thanks

**Comment by mclamanna** [comment]
I found the issue, nothing wrong with Live Server.

**Comment by scianci** [comment]
@mclamanna Could you please explain what you did to address your issue? I'm facing the same issue currently. Thanks.

**Comment by mclamanna** [comment]
scianci, I was testing out a service worker and the JS was conflicting with chrome and Firefox, little did I know at the time service workers were not supported by safari so it didn't register the JS error.

**Comment by ritwickdey** [comment]
Live Server is not specific for any browser. Any browser who supports `ws` protocol (ACTUALLY ALL BROWSER), can be used for live server.
