### ISSUE TITLE
Live server is not working properly with a non-tradicional HTML structure.

### ISSUE THREAD

**Issue by morissonmaciel** [ritwickdey/vscode-live-server#90]
Hi, I'm developing a superset markup language based on HTML for my company and I'm using Live Server for RAD refresh and continue coding.

However, one of the superset markup premises is not to use tradicional HTML tags, except `<script>` and `<style>`. So, when I launch Live Server, the plugin tries to inject bad structural code into HTML parser. This issue happens for every modern browser.

This is an ordinary superset code sample:

```
<script src="../src/XAMLParser.js"></script>
<page>
    <flexpanel dock="fill">
        <panel id="panel1"></panel>
        <panel id="panel2"></panel>
    </flexpanel>
</page>
```

**For instance:** 
(Request in Live Server cropped the result as shown below)
![screenshot_1](https://user-images.githubusercontent.com/11509104/37463937-82c6eeb2-2835-11e8-8099-27b233b61270.png)

(When using comments in an entire HTML element, code is injected inside comments)
![screenshot_2](https://user-images.githubusercontent.com/11509104/37463980-b18181fe-2835-11e8-92f2-f04468d8251b.png)

For now, I'm using `Preview in Web Server` plugin as a workaround but I would like to back to Live Server  for faster refresh and better HTML render fidelity.

**Comment by rjoydip** [comment]
I am closing this issue because this is not looks like an issue. Thank you for reporting.
