### ISSUE TITLE
Works on Mozilla Firefox but doesn't work on Chrome

### ISSUE THREAD

**Issue by ygspasov** [ritwickdey/vscode-live-server#92]
The autorefresh feature works in Firefox but on Chrome I have to press refresh each time a change is made in the HTML.

**Comment by ritwickdey** [comment]
I'm not sure why, it is not depended on any specific browser.  
May be it is related with Chrome. You can give a try to reset chrome.

For now I'm closing the issue. Let me know if it works for you or not. If not, I'll reopen the issue.
