### ISSUE TITLE
Live Server is not auto reloading page!

### ISSUE THREAD

**Issue by MaceGood** [ritwickdey/vscode-live-server#931]
Hello, when I installed live server 2 months ago everything was fine, but after some time the live server stopped auto reloading the page, I tryied to fix it with different methods, even I reinstalled VSC and it still didnt work,please help thank you

**Comment by Igli7** [comment]
the same thing with me used live server for a long time and just 2 weeks ago it stopped reloading. I tried everything I could from reinstalling VSC, reinstalling live server, going through settings, and nothing seem to work. I'd really appreciate it if somebody gonna give me a solution about it

**Comment by MaceGood** [comment]
> the same thing with me used live server for a long time and just 2 weeks ago it stopped reloading. I tried everything I could from reinstalling VSC, reinstalling live server, going through settings, and nothing seem to work. I'd really appreciate it if somebody gonna give me a solution about it

In settings search for "useWebExt" and check you DON'T have it enabled. I just unchecked this and now it's working!

**Comment by Igli7** [comment]
yoo you just saved my life XD, quickest respond I've ever gotten. Thank man much appreciated, been struggling with this for the past two weeks
