### ISSUE TITLE
cursor position

### ISSUE THREAD

**Issue by Hunlongyu** [ritwickdey/vscode-live-server#96]
After saving, the cursor appears at the end of the code and can not appear at the location of the last editor. It's really too much trouble.

**Comment by mxschmitt** [comment]
@Hunlongyu 
Can you please disable all extensions except live-server, because I can't reproduce this issue. I think an other extension is causing this behaviour.

**Comment by Hunlongyu** [comment]
Errors caused by this plug-in：JS-CSS-HTML Formatter.

https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter
