### ISSUE TITLE
Extension issue liveserver give me the  error unresponsive it doesn't work 

### ISSUE THREAD

**Issue by amirho1** [ritwickdey/vscode-live-server#969]
- Issue Type: `Bug`
- Extension Name: `LiveServer`
- Extension Version: `5.6.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.47.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by saami97** [comment]
Hi Amir,

Did you got any resolution to your issue, or are you still stuck with it.
