### ISSUE TITLE
Dynamic page support for Firefox.

### ISSUE THREAD

**Issue by L0stLink** [ritwickdey/vscode-live-server#97]
Since Live Server now supports dynamic pages on Chrome via the [extension](https://github.com/ritwickdey/live-server-web-extension), It would be nice if a similar extension was made available for Firefox for those who use Firefox for development instead of Chrome.

**Comment by miloskroulik** [comment]
It seems to be available: https://addons.mozilla.org/en-US/firefox/addon/live-server-web-extension/

**Comment by L0stLink** [comment]
I don't know how I missed that.
